### ISSUE TITLE
Document `pg_table_size`, `pg_indexes_size`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1003]
https://github.com/risingwavelabs/risingwave/pull/9013

`table` can even the internal tables as listed here: https://www.risingwave.dev/docs/current/sql-show-internal-tables/

**Comment by hengm3467** [comment]
`pg_relation_size` doesn't work. So I'm narrowing the scope to only pg_table_size and pg_indexes_zie.
