### ISSUE TITLE
Document `pg_shadow`

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1014]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10860

### Which part(s) of the docs might be affected or should be updated? And how?

Add `pg_shadow` to PostgreSQL catalogs. 

### Reference

https://www.postgresql.org/docs/current/view-pg-shadow.html

**Comment by CharlieSYH** [comment]
This belongs to the release after v1.0.0. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main
