### ISSUE TITLE
Document `sign()`

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1015]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10819

### Which part(s) of the docs might be affected or should be updated? And how?

Document `sign()` under mathematical functions.

### Reference

https://www.postgresql.org/docs/9.1/functions-math.html

**Comment by CharlieSYH** [comment]
This belongs to the release after v1.0.0. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main
