### ISSUE TITLE
Document `publication.name` and `publication.create.enable` parameters for PG CDC

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1016]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10804

### Which part(s) of the docs might be affected or should be updated? And how?

Document `publication.name` and `publication.create.enable` parameters for CREATE TABLE

**Comment by StrikeW** [comment]
Hello, please add more description for the recommended ways to use postgres-cdc connector.

> We recommend users to create the publication in the postgres in advance, then supply the publication name to create a table via `publication.name` WITH option. Otherwise, when create multiple CDC tables, some tables may not function as expected.

You may help to refine my language, thanks.

**Comment by CharlieSYH** [comment]
This belongs to the release after v1.0.0. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main

**Comment by StrikeW** [comment]
> This belongs to the release after v1.0.0. See [risingwavelabs/risingwave@v1.0.0...main](https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main)

But the pr has been picked to v1.0 (https://github.com/risingwavelabs/risingwave/pull/10845). cc @lmatz

**Comment by CharlieSYH** [comment]
> > This belongs to the release after v1.0.0. See [risingwavelabs/risingwave@v1.0.0...main](https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main)
> 
> But the pr has been picked to v1.0 ([risingwavelabs/risingwave#10845](https://github.com/risingwavelabs/risingwave/pull/10845)). cc @lmatz

So how do we judge if a PR belongs to v1.0.0?
Is this accurate: https://github.com/risingwavelabs/risingwave/compare/v1.0-rc...v0.19.0-rc
