### ISSUE TITLE
Document `left()` and `right()`

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1017]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10765

### Which part(s) of the docs might be affected or should be updated? And how?

Document `left()` and `right()` under string functions.

### Reference

https://www.postgresql.org/docs/9.1/functions-string.html

**Comment by CharlieSYH** [comment]
Not v1.0.0. It's in the next release.
