### ISSUE TITLE
Document `START TRANSACTION/BEGIN`, `COMMIT` commands

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1022]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10735

### Which part(s) of the docs might be affected or should be updated? And how?

Document the experimental `START TRANSACTION/BEGIN`, `COMMIT` commands. `START TRANSACTION` and `BEGIN` have the same functionality. 

### Reference

https://www.postgresql.org/docs/current/sql-start-transaction.html
https://www.postgresql.org/docs/current/sql-begin.html
https://www.postgresql.org/docs/current/sql-commit.html

**Comment by CharlieSYH** [comment]
This is not a v1.0.0 feature. It's after it. See https://github.com/risingwavelabs/risingwave/compare/v1.0.0...main.
