### ISSUE TITLE
Document `SHOW CLUSTERS` command

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1025]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10656

### Which part(s) of the docs might be affected or should be updated? And how?

Document `SHOW CLUSTERS` command

**Comment by yezizp2012** [comment]
@emile-00 , FYI the command will be changed to `SHOW CLUSTER` in this PR: https://github.com/risingwavelabs/risingwave/pull/10932.

**Comment by CharlieSYH** [comment]
> @emile-00 , FYI the command will be changed to `SHOW CLUSTER` in this PR: [risingwavelabs/risingwave#10932](https://github.com/risingwavelabs/risingwave/pull/10932).

Checked with @neverchanje and @huangjw806, and this syntax change can only be included in the next release and should be introduced as a breaking change. So it's still `SHOW CLUSTERS` for this version.

Opened an issue to track this change: https://github.com/risingwavelabs/risingwave-docs/issues/1063
