### ISSUE TITLE
Document `BYTES` as a new data format

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1028]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10592

### Which part(s) of the docs might be affected or should be updated? And how?

Document `BYTES` as a new data format. Currently only Kafka source is tested, confirm if other sources also support BYTES data format.

**Comment by st1page** [comment]
because we also update the create source syntax in this version, so we might can doc it only with the new syntax after https://github.com/risingwavelabs/risingwave-docs/pull/1011 merged
