### ISSUE TITLE
Document Delta Lake sink

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1030]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10374
https://github.com/risingwavelabs/risingwave/pull/10580

### Which part(s) of the docs might be affected or should be updated? And how?

Document Delta Lake sink

**Comment by andreale28** [comment]
Hi Committers, @emile-00 , sorry for pinging this merged PR. Do we have any compatibility matrix among RisingWave, Delta-spark, and Spark? The docs does not mention it so it is quite confused when reading the Delta Sink docs. 

I have asked the same questions on discussion and Slack but I think I should ask here for correctness. Sorry if it's spamming.

**Comment by emile-00** [comment]
@andreale28 I see that your question was answered on Slack by the developer of this feature. We are testing the compatibility between these 3 technologies and will update the documentation accordingly soon.
