### ISSUE TITLE
Update the `date_trunc()`, `extract()`, and `date_part()` functions

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1032]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10480

### Which part(s) of the docs might be affected or should be updated? And how?

Update the `date_trunc()`, `extract()`, and `date_part()` functions to be:
- date_trunc(field_string, input_timestamptz, zone_string) = timestamptz
- extract(field_string, input_timestamptz, zone_string) = decimal 
- date_part(field_string, input_timestamptz, zone_string) = double precision

**Comment by CharlieSYH** [comment]
This is not included in v1.0.0.
