### ISSUE TITLE
Document EXCEPT clause for SELECT statement

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1034]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10438

syntax change: https://github.com/risingwavelabs/risingwave/pull/10723

### Which part(s) of the docs might be affected or should be updated? And how?

Document EXCEPT clause for SELECT statement

**Comment by CharlieSYH** [comment]
Update:

https://github.com/risingwavelabs/risingwave/pull/10723 changes the syntax.

Will document this in the next release (the one after v1.0).
