### ISSUE TITLE
Document GROUPING SETS clause

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1043]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10807

### Which part(s) of the docs might be affected or should be updated? And how?

Document the GROUPING SETS clause under Sets operators. 

### Reference

https://www.sqltutorial.org/sql-grouping-sets/

**Comment by CharlieSYH** [comment]
Not v1.0.0.

**Comment by hengm3467** [comment]
Close as completed in #1168
