### ISSUE TITLE
Update ROW FORMAT syntax for CREATE SOURCE/CREATE TABLE

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1044]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10561

### Which part(s) of the docs might be affected or should be updated? And how?

Update the ROW FORMAT syntax. Old keywords, such as MESSAGE, ROW SCHEMA LOCATION, etc., are now options. 
`ROW FORMAT CSV WITHOUT HEADER DELIMITED BY ',';''')` is now `ROW FORMAT CSV (delimiter = ',', without_header = true);''')`.

**Comment by CharlieSYH** [comment]
This is actually included in v1.0.0.

**Comment by hengm3467** [comment]
The changes were included in #1011
