### ISSUE TITLE
Document how to manually upgrade the cluster

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1047]
### Related code PR

The document needs to provide the information below:

1. Steps to upgrade a RisingWave cluster.
2. The service will be temporarily unavailable during the upgrade.
3. The upgrade from v0.x to v1.0 is not backward compatible. Therefore, we recommend recreating a new cluster and all the associated database objects. From v1.0 on, we will ensure backward compatibility and provide the migration tool when there are inevitable breaking changes.

@arkbriar Please elaborate the operations for upgrading the k8s cluster.

### Which part(s) of the docs might be affected or should be updated? And how?

This doc should be placed under 'Manage'.

**Comment by arkbriar** [comment]
> @arkbriar Please elaborate the operations for upgrading the k8s cluster.

For open-source users right?

**Comment by neverchanje** [comment]
Yes. For OSS users. For cloud users it will just be a button I guess, which does not require a doc then.

**Comment by arkbriar** [comment]
> Yes. For OSS users. For cloud users it will just be a button I guess, which does not require a doc then.

Upgrading can be simply done by the following command:

```bash
kubectl patch risingwave <risingwave_name> --type='merge' -p '{"spec": {"image": "new_image"}}'
```

, where `<risingwave_name>` is the RisingWave's name and `new_image` is the new image. And by design, downgrading isn't restricted but will cause unexpected behaviours. So it requires the users attention to take their own risk.

The completion of upgrading can be verified by `kubectl describe risingwave <risingwave_name>`. In the result, the upgrading condition should be false or not exist.

If you need help on elaboration on the doc, please let me know when there's a PR so I can help with it.

**Comment by hengm3467** [comment]
@arkbriar Can you provide examples of <risingwave_name> and <new_image>?

I assume the image address would be: https://github.com/risingwavelabs/risingwave-operator/releases/download/v0.5.0/risingwave-operator.yaml or is it the risingwave image (not the operator image)?

Thanks.

**Comment by arkbriar** [comment]
> @arkbriar Can you provide examples of <risingwave_name> and <new_image>?
> 
> I assume the image address would be: https://github.com/risingwavelabs/risingwave-operator/releases/download/v0.5.0/risingwave-operator.yaml or is it the risingwave image (not the operator image)?
> 
> Thanks.

<risingwave_name>: like `risingwave` or `risingwave-in-memory`, typically any words, depending on the user. In our doc, we used `risingwave`.

<new_image>: `ghcr.io/risingwavelabs/risingwave:v0.19.3`

> is it the risingwave image (not the operator image)

Yes.
