### ISSUE TITLE
Experiment: Try out Owlbot for AI Doc

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1049]
### Which part(s) of the docs might be affected or should be updated? And how?

https://developers.deepgram.com/docs

I once tried deepgram's AI document bot and it perfectly answered my question. Back then I was asking for a usage that no document described. For example, I wanted it to load file from a local directory, while their docs only described how to load file from a Web URL. The AI bot perfectly solved this problem by tweaking a small part of the existing example to adapt to my question.

Therefore, I wonder if it's also possible for us to use this technology to optimize our user experience. The AI bot service they used is https://www.owlbot.ai/#features.

**Comment by CharlieSYH** [comment]
Thanks, @neverchanje. We'll explore the possibility! Looks really cool.

BTW, https://supabase.com/docs has a similar chatbot along with the search. But it doesn't provide the referenced material.

<img width="1133" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/44f9b486-af1a-4e39-9280-a522dc7a47bd">
<img width="896" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/d02ea54f-08bf-4e5e-8098-217060ce8779">

Deepgram's AI document bot provides the links to the full article in the docs. That's GOOD.
<img width="440" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/d874741d-37b0-4a5a-afa3-5ac651164ef1">

**Comment by CharlieSYH** [comment]
@mrayees proposed https://docsbot.ai/ in Slack. We'll explore it as well.

**Comment by Ad-Bean** [comment]
![image](https://github.com/risingwavelabs/risingwave-docs/assets/54789193/e84a33a1-9a2c-4191-a1b0-f3ec83e80ced)

I've tried the owlbot ai on our docs, but the UI looks quite different from Deepgram (they are using the readme framework).

**Comment by neverchanje** [comment]
Thank you Adbean. Perhaps they have used different themes or may have customized their own styling. However, I couldn't find any document for Owlbot in the internet. Maybe you can ask for their techinical support.

**Comment by Ad-Bean** [comment]
> Thank you Adbean. Perhaps they have used different themes or may have customized their own styling. However, I couldn't find any document for Owlbot in the internet. Maybe you can ask for their techinical support.

Yes, I am reaching owlbot.ai for further help in implementing our chatbot. I am still confused about whether the owlbot chatbot on the deepgram is the same as owlbot.ai. The sure thing is that deepgram is using a different framework (they are using [readme](https://readme.com/) and we are using [docusaurus](https://docusaurus.io/)), and the readme framework supports owlbot chatbot natively.
