### ISSUE TITLE
Need document for TVF and TUMBLE window

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#105]

**Comment by hengm3467** [comment]
@TennyZhuang I assume we can use this document as reference for creating user docs. Correct? 
https://singularity-data.quip.com/p3yOAMmxR7b9/RFC-Windowing-TVF-in-RisingWave

**Comment by fuyufjh** [comment]
> @TennyZhuang I assume we can use this document as reference for creating user docs. Correct? https://singularity-data.quip.com/p3yOAMmxR7b9/RFC-Windowing-TVF-in-RisingWave

agree!

**Comment by hengm3467** [comment]
@TennyZhuang @fuyufjh @neverchanje @xiangjinwu Please review the how-to guide about time windows: https://singularity-data.quip.com/HfLyA2JJHFvH/Window-functions-in-review
