### ISSUE TITLE
Document configuring the Kubernetes cluster to use GCS

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1057]
https://www.risingwave.dev/docs/current/risingwave-kubernetes/#deploy-a-risingwave-instance

Parallel to s3, minio and hdfs.

**Comment by lmatz** [comment]
One thing I am confused when trying the GCS deployment
https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/manifests/risingwave/risingwave-gcs.yaml#L6-L21
 is:

whether we should specify `ServiceAccountCredentials` in the yaml file or similar to the s3 deployment documentation ```kubectl create secret generic ``` 
Therefore I did both and it worked. Not sure if this is the right way to do it? @arkbriar

**Comment by arkbriar** [comment]
> One thing I am confused when trying the GCS deployment https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/manifests/risingwave/risingwave-gcs.yaml#L6-L21 is:
> 
> whether we should specify `ServiceAccountCredentials` in the yaml file or similar to the s3 deployment documentation `kubectl create secret generic ` Therefore I did both and it worked. Not sure if this is the right way to do it? @arkbriar

Either is enough.
