### ISSUE TITLE
Document the database management tool DBeaver 

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1073]
https://www.notion.so/risingwave-labs/DBeaver-3eaf852d75764484b78c3a8b59d909dd

**Comment by hengm3467** [comment]
@lmatz It looks like the support for DBeaver will be included in the next version. Right?
I'm using 1.0.0 alpha and got the error when expanding any list. 
![image](https://github.com/risingwavelabs/risingwave-docs/assets/100685635/348c86c0-a073-49b4-8c8f-516f2b6c2ac3)

**Comment by lmatz** [comment]
I think `1.0.0` should have supported a somewhat older version of Dbeaver

I just tested the latest version and run into the same problem, let me open an issue to the main Repo

**Comment by neverchanje** [comment]
The doc draft: https://www.notion.so/risingwave-labs/Connecting-DBeaver-to-RisingWave-draft-4628b4bd90274a0c961f69fa798c9695?pvs=4 

Btw, this issue duplicates with https://github.com/risingwavelabs/risingwave-docs/issues/1086

---- 

Oh, I didn't notice that we already have a draft: https://www.notion.so/risingwave-labs/DBeaver-3eaf852d75764484b78c3a8b59d909dd

**Comment by hengm3467** [comment]
Closed as duplicated with #1086
