### ISSUE TITLE
Change required: How to use dbeaver to connect rasingwave

### ISSUE THREAD

**Issue by ChenpiDog** [risingwavelabs/risingwave-docs-legacy#1086]
### Which part(s) of the docs might be affected or should be updated? And how?

Docker deploys rasingwave, how to use dbeaver to connect rasingwave, how to set the environment, such as database name, user name, password, etc., is it the same as postgre? I tried it, but I couldn’t connect.
![image](https://github.com/risingwavelabs/risingwave-docs/assets/55483982/78f235fa-727e-46d2-9c81-d62e3ca5094b)
![image](https://github.com/risingwavelabs/risingwave-docs/assets/55483982/8d49246a-4ef5-4670-9cac-02eb775f2a4a)
![image](https://github.com/risingwavelabs/risingwave-docs/assets/55483982/0bff43b9-1048-4b26-881a-37ec325460d5)
![image](https://github.com/risingwavelabs/risingwave-docs/assets/55483982/aae06717-336d-407f-b18d-24b450e4fa7d)

**Comment by lmatz** [comment]
Yes, we can use dbeaver to connect to Risingwave just like Postgres in most of cases. It has been used by many RW users.

In this particular case, I suspect that `POSTGRES_DB` env variables do not take effect.

We have an issue: https://github.com/risingwavelabs/risingwave-docs/issues/1073
that is going to demo the steps in detail.

**Comment by ChenpiDog** [comment]
> Yes, we can use dbeaver to connect to Risingwave just like Postgres in most of cases. It has been used by many RW users.
> 
> In this particular case, I suspect that `POSTGRES_DB` env variables do not take effect.
> 
> We have an issue: #1073 that is going to demo the steps in detail.

I don't have permission to access this link. I want to use dbeaver to connect to rasingwave. What should I do.

**Comment by lmatz** [comment]
Could you try to `psql` into Risingwave and then create database `edw`?

> I suspect that POSTGRES_DB env variables do not take effect.

Or use the default `dev` database, and after connect by `dbeaver` and then create a new database via `dbeaver`

**Comment by neverchanje** [comment]
Hi, @ChenpiDog 

Thanks for your feedback. I think the doc improvement will be applied to the quick start page: https://www.risingwave.dev/docs/current/get-started/ Here we have described the way to connect to RisingWave:

```
psql -h localhost -p 4566 -d dev -U root
```

`-p` indicates port, `-d` for database, and `-U` for user.
I admit that it's not friendly enough for users who are unfamiliar with the parameters of psql. So I think we can add more description regarding the connection options.

However, in terms of the environment variables, such as POSTGRES_USER, I don't think RisingWave should be 100% compatible with Postgres. And such usage is not documented anywhere, after all. Thus, the results of the misuse will not be considered as a bug.

Furthermore, our doc for DBeaver will come soon. Please stay tuned.
https://github.com/risingwavelabs/risingwave-docs/issues/1073

**Comment by ChenpiDog** [comment]
@neverchanje OK

**Comment by neverchanje** [comment]
The doc draft: https://www.notion.so/risingwave-labs/Connecting-DBeaver-to-RisingWave-draft-4628b4bd90274a0c961f69fa798c9695?pvs=4
