### ISSUE TITLE
add a guide for `emit on window close` 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#1100]
Need to explain the semantics, usage, internals about `emit on window close `

**Comment by hengm3467** [comment]
@fuyufjh

Now that we already have a guide, did you intend to create a new guide? 

https://docs.risingwave.com/docs/current/emit-on-window-close/

Othewise, we can close this issue.

**Comment by fuyufjh** [comment]
The issue's target is that doc. Just forgot to close
