### ISSUE TITLE
add a summary of schema evolution

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#1104]
The implementation has not been done yet. Just note it down here. 

The "schema revolution" comprises multiple things:

- [x] Alter a table without connector
- [ ] Alter a table with connector (WIP)
- [ ] Alter a source (WIP)
- [ ] Update external schema i.e. Schema registry

**Comment by neverchanje** [comment]
I didn't notice this issue. It'll eventually be covered by https://github.com/risingwavelabs/risingwave-docs/issues/1196.

**Comment by CAJan93** [comment]
For all the non-sql wizards: I know what schema evolution is, but what is schema revolution?

**Comment by yingjunwu** [comment]
Should be "schema evolution"

**Comment by fuyufjh** [comment]
schema revolution! ✊🔥🗽

**Comment by CAJan93** [comment]
Hahahahaha Okay. Fair enough 😁
