### ISSUE TITLE
Document `created_at` and `initialized_at` from RW relations

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1119]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/11199

### Which part(s) of the docs might be affected or should be updated? And how?

Document how users can select `created_at` and `initialized_at` from RW relations (sources, sinks, tables, etc) under RW catalogs

**Comment by hengm3467** [comment]
Close as completed. See the changes on this page:
https://www.risingwave.dev/docs/current/rw_catalog/
