### ISSUE TITLE
Document `set_config()`

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1121]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/11147

### Which part(s) of the docs might be affected or should be updated? And how?

Document `set_config()` under System administration functions

### Reference

https://www.postgresql.org/docs/current/functions-admin.html

**Comment by hengm3467** [comment]
Close as completed in a separate update. The changes can be seen from this page:

https://www.risingwave.dev/docs/upcoming/sql-function-sys-admin/
