### ISSUE TITLE
Document `GROUPING()`

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1127]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/11006

### Which part(s) of the docs might be affected or should be updated? And how?

Document `GROUPING()` under Aggregrate functions. Also note how `GROUPING()` is used with the `GROUPING SETS` clause (documented with this [issue).](https://github.com/risingwavelabs/risingwave-docs/issues/1043) 

### Reference

Table 9-53: Grouping Operations: https://www.postgresql.org/docs/9.5/functions-aggregate.html

**Comment by hengm3467** [comment]
Close as completed in #1168
