### ISSUE TITLE
Bug: Docs markdown link couldn't be resolved

### ISSUE THREAD

**Issue by Ad-Bean** [risingwavelabs/risingwave-docs-legacy#1130]
### Where's the bug?

https://www.risingwave.dev/docs/upcoming/watermarks

### Describe the bug

[Overview of data types] https://www.risingwave.dev/docs/upcoming/watermarks/sql-data-types.md/ leads to a wrong page, which should be https://www.risingwave.dev/docs/upcoming/sql-data-types/

![image](https://github.com/risingwavelabs/risingwave-docs/assets/54789193/56209fa5-08a8-465d-9d94-be632d5ae3ee)

**Comment by emile-00** [comment]
Link on watermarks page now works.
