### ISSUE TITLE
Docs for watermark and `emit on window close`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#1136]
### Related code PR

risingwavelabs/risingwave#9622 and many others.

### Which part(s) of the docs might be affected or should be updated? And how?

Now we have a [summary of Emit on window close](https://github.com/risingwavelabs/risingwave-docs/pull/1124) and watermark documents, some other docs can be updated accordingly and linked to them. 

Following docs need to be updated to reflect the watermark and `emit on window close`. Please mark them as experimental as well.

- [ ] [CREATE SOURCE](https://www.risingwave.dev/docs/current/sql-create-source/): needs to mention watermark definition
- [ ] [CREATE SINK](https://www.risingwave.dev/docs/upcoming/sql-create-sink/) needs to mention that `emit on window close` can help to build an append-only sink.
- [ ] [GROUP BY clause](https://www.risingwave.dev/docs/upcoming/query-syntax-group-by-clause/) needs to mention that `emit on window close` can help to make an append-only output and avoid some unnecessary computation
- [ ] Window functions (no docs yet) needs to mention that `emit on window close` can help to make an append-only output and avoid some unnecessary computation

**Comment by CharlieSYH** [comment]
related: https://github.com/risingwavelabs/risingwave/pull/11454
