### ISSUE TITLE
Bug: `warning` not rendered correctly

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1142]
### Where's the bug?

https://www.risingwave.dev/docs/upcoming/meta-backup/

### Describe the bug

![SCR-20230807-ko6](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/b05acade-b282-4b39-9feb-77d0ff74454d)

`:::warning`

**Comment by hengm3467** [comment]
Fixing it.

**Comment by hengm3467** [comment]
Fixed:

![image](https://github.com/risingwavelabs/risingwave-docs/assets/100685635/72bab1f8-8f5b-4223-8960-708eba74ed4b)
