### ISSUE TITLE
Document that Superset can connect to Risingwave without plugin

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1156]
On the latest `main` branch of Risingwave (not `v1.1`), Superset can connect to Risingwave without installing a plugin first: https://www.risingwave.dev/docs/current/superset-integration/#add-the-sqlalchemy-risingwave-driver

Theoretically, it should work smoothly as the plugin is only needed during
1. connect to database
2. figure out tables/MVs in the database
3. create dataset

These three steps have been tested locally with Apache Superset 2.1

I suggest we can label this as experimental support as it is much more convenient but potentially more unstable.

**Comment by emile-00** [comment]
closed via https://github.com/risingwavelabs/risingwave-docs/pull/1363
