### ISSUE TITLE
Document max_concurrent_creating_streaming_jobs

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave-docs-legacy#1170]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/11601

### Which part(s) of the docs might be affected or should be updated? And how?

Support system parameters `max_concurrent_creating_streaming_jobs` to control the number of creating streaming jobs.
Should be updated here: https://www.risingwave.dev/docs/current/view-configure-system-parameters/

**Comment by hengm3467** [comment]
Close as completed in #1219
