### ISSUE TITLE
Document: feat: support grant/revoke privileges for tables

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1181]
This issue tracks the documentation update needed for the merged PR #11725.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/11725
Source PR Merged At: 2023-08-17T09:00:17Z

**Comment by hengm3467** [comment]
Updated in #1206 and #1208. Closing this issue as completed.

See the changes in these two topics:
https://docs.risingwave.com/docs/upcoming/sql-grant/
https://docs.risingwave.com/docs/upcoming/sql-revoke/
