### ISSUE TITLE
Document ingesting MongoDB CDC data

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#1183]
### Related code PR

Currently, we have a topic about the CDC formats we support. It doesn't align with our guidelines that arrange content based on end systems (not internal impelementation techniques). Let's refactor it so that it's obvious that we support MongoDB, etc. 

Let's tackle MongoDB CDC first. 

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/create-source-cdc/

**Comment by neverchanje** [comment]
https://www.notion.so/risingwave-labs/Ingest-data-from-MongoDB-CDC-Draft-131974d443c84cdaa7143815114af870?pvs=4 The MongoDB CDC draft

**Comment by hengm3467** [comment]
Let's narrow down the scope of this PR to MongoDB CDC guide. Will be creating separate issues for TiDB CDC and SQL Server CDC.
