### ISSUE TITLE
Document deploying RisingWave using Helm

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1185]
### Which part(s) of the docs might be affected or should be updated? And how?

We expect to use helm to replace the previous pure kubectl approach: https://www.risingwave.dev/docs/current/risingwave-kubernetes/ 

The draft: 
https://www.notion.so/risingwave-labs/Deploy-RisingWave-in-a-Single-Kubernetes-Cluster-Draft-bea9851e05084e5180b98b69484a1155?pvs=4

**Comment by hengm3467** [comment]
Close as completed in #1367
