### ISSUE TITLE
Document the standalone mode of Risingwave.

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1187]
I will describe more details when it is completely done.

**Comment by CharlieSYH** [comment]
Any updates on the standalone mode? @lmatz 
I noticed the dev guide is already updated: https://github.com/risingwavelabs/risingwave/pull/12828/files, but the PR is not marked with the `user-facing-changes` label.

**Comment by lmatz** [comment]
@CharlieSYH thanks for reminding me.

Let me write a paragraph for the standalone mode. I am also submitting a PR to support this mode via `docker-compose`: https://github.com/risingwavelabs/risingwave/pull/13233

In short, we will support standalone mode when users use `docker-compose` or deploy Risingwave on Kubernetes via `risingwave-operator`(https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/manifests/risingwave/risingwave-standalone.yaml) or via helm chart (but I didn't find how users can use standalone mode in its Repo: https://github.com/risingwavelabs/helm-charts)

The standalone mode can optionally put each component of RW, including compute node, frontend node, meta node, and compactor node, into one single process. They are executed in different threads.
Previously, we had to start each component as a separate process.

The benefits are that:
1. users do not need to understand why there are different components. Risingwave presents itself as an all-in-one service.
2. better resource control. CPU and memory resources are shared among different components. Memory resources are bounded due to the compute node's eviction mechanism.


We intend to suggest users use `standalone` mode as the default one.
But we have some work to finish first, more details can be found at: 
https://github.com/risingwavelabs/risingwave/issues/13235
https://github.com/risingwavelabs/risingwave/issues/12861

I will keep this post updated, hope I don't forget it again.

**Comment by CharlieSYH** [comment]
https://github.com/risingwavelabs/risingwave/pull/13133

**Comment by CharlieSYH** [comment]
https://github.com/risingwavelabs/risingwave/pull/13133
