### ISSUE TITLE
document: Source and Table Schema evolution (WIP)

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1196]
### Related code PR

The PR is still under review.

https://github.com/risingwavelabs/risingwave/pull/11710
https://github.com/risingwavelabs/risingwave/pull/11350

### Which part(s) of the docs might be affected or should be updated? And how?

The draft is WIP: https://www.notion.so/risingwave-labs/Source-and-Table-Schema-evolution-Draft-de1ecbefc8ad430794c57010f8ca0436?pvs=4

**Comment by hengm3467** [comment]
This was already published at: https://docs.risingwave.com/docs/current/modify-schemas/
