### ISSUE TITLE
Remind user to deploy etcd on a good-quality disk

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1220]
`etcd` on a low-quality disk can lead to many instabilities. And it is out of RW's control

**Comment by CAJan93** [comment]
Do we have a definition of "good quality disk"? If I am a user, how do I know if my disk is good enough?

**Comment by lmatz** [comment]
We can remind users to refer to the official doc https://etcd.io/docs/v3.3/op-guide/hardware/#disks.
This can be done first.

It also depends on the experience of the engineers who have integrated ETCD into Risingwave and debugged related issues. We can give recommended config based on our experience, 
cc: @shanicky as @shanicky has already helped many users who ran into this issue. 

i.e. if on AWS/GCP/self-deployement, what type of disk is recommended? A rough idea is enough

**Comment by CAJan93** [comment]
> etcd will also incrementally checkpoint its state to disk so it can truncate this log. If these writes take too long, heartbeats may time out and trigger an election

That explains why a slow disk leads to cluster instability...

**Comment by shanicky** [comment]
It seems like a basic SATA SSD is still essential. If it’s a cloud environment, based on experience, it is advised to use types above gp3 at a minimum, as small capacity gp2 appears to be insufficient currently.

**Comment by lmatz** [comment]
And don't co-locate with minio if minio is used.

Increase "meta_leader_lease_secs" if there is only a single meta node.

**Comment by CAJan93** [comment]
> And don't co-locate with minio if minio is used.

Why should we not co-locate ETCD and MinIO? Is this just in case the underlying VM has an issue?

**Comment by lmatz** [comment]
They both consume disk bandwidth.

If MinIO suddenly starts to work and it may add a few milliseconds to ETCD's current operation, ETCD is likely to break.

And I suppose most users won't do disk bandwidth isolation if both components are co-located
