### ISSUE TITLE
Discussion: discourage using Risingwave via `Docker Compose`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1232]
![SCR-20230831-sor](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/654bf635-b3bf-499a-b422-e5496b9e9b12)

![SCR-20230831-sot](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/f64dbc43-ee98-441c-bb93-e1abcb2f85c2)

![SCR-20230831-sow](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/d65682bf-cb74-4155-a872-4727ad167d80)

Although the description here is correct, I think we'd better only suggest users use `kubernetes` and `risingwave cloud`.

Running via `docker compose` is simply not as robust as others. We don't want to diagnose these issues that can be otherwise avoided.

**Comment by hengm3467** [comment]
@lmatz Did you mean remove the whole "Try out" (https://docs.risingwave.com/docs/current/risingwave-trial/) section? Or it's only the Docker & Docker Compose option?

**Comment by lmatz** [comment]
I am thinking if we should remove "docker compose" from the "caution" section

**Comment by hengm3467** [comment]
Now I see your point.

**Comment by hengm3467** [comment]
Removed Docker Compose from the recommended options to persist data. 

https://docs.risingwave.com/docs/current/risingwave-trial/?method=homebrew

Close as completed.
