### ISSUE TITLE
Document: feat(sink): Support Nats sink (append_only)

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1236]
This issue tracks the documentation update needed for the merged PR #11924.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/11924
Source PR Merged At: 2023-08-31T08:40:11Z

**Comment by hengm3467** [comment]
@yufansong Please provide a draft document for the NATS sink support. We'll edit and then publish it to the documentation. Thanks!

**Comment by neverchanje** [comment]
https://www.notion.so/risingwave-labs/Sinking-Data-to-NATS-from-RisingWave-Draft-90c13329ca1a4e0b925510f4d19b7747?pvs=4 Here is the draft doc for NATS sink
