### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave-docs-legacy#1249]
### Where's the bug?

https://docs.risingwave.com/docs/current/sink-to-postgres

### Describe the bug

e.g. 
 I noticed that there is a [typo/misused term/inconsistency/ambiguity] in [this sentence/paragraph/figure/section/screenshot]. 
 [This] is incorrect because [...]. 
 I think you folks should replace [this] with [that]. 
 If you take a look at [this reference] you will agree with me. 
 Cheers.

**Comment by hengm3467** [comment]
@StrikeW Can you describe the issue? Thanks.

**Comment by StrikeW** [comment]
Sorry, accidentally create duplicate issue.
