### ISSUE TITLE
document elasticsearch sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1292]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10357
https://github.com/risingwavelabs/risingwave/pull/10415

### Which part(s) of the docs might be affected or should be updated? And how?

here is the draft: 

https://www.notion.so/risingwave-labs/Sinking-Data-to-Elasticsearch-from-RisingWave-Draft-879f4f51acf9433ebc5e92891896b8ac?pvs=4

**Comment by neverchanje** [comment]
@hzxa21 @wugouzi Please help review the draft and see if there is features that I didn't cover. Thanks!

**Comment by wugouzi** [comment]
Added another pr. Primary keys are concatenated by `delimiter` to be used as `id` of each record. Default `delimiter` is `_` and is configurable by `delimiter = `
