### ISSUE TITLE
Document: feat(meta): expose hummock pinned versions and snapshots via rw_catalog

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1297]
This issue tracks the documentation update needed for the merged PR #12285.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/12285
Source PR Merged At: 2023-09-13T13:55:00Z

**Comment by zwang28** [comment]
This feature is to facilitate troubleshooting for developers.
