### ISSUE TITLE
Document: feat(agg): support streaming `bool_and` and `bool_or` agg

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1301]
This issue tracks the documentation update needed for the merged PR #11956.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/11956
Source PR Merged At: 2023-09-14T05:29:25Z

**Comment by hengm3467** [comment]
Since we already documented the two functions, and didn't mention that it's only for batch queries, there's no need to update the doc to say these functions are now supported in streaming queries.
Closing this issue as completed.

https://docs.risingwave.com/docs/current/sql-function-aggregate/
