### ISSUE TITLE
Document: feat(dashboard): add memory profiling

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1313]
This issue tracks the documentation update needed for the merged PR #12052.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/12052
Source PR Merged At: 2023-09-18T08:42:13Z

**Comment by hengm3467** [comment]
@neverchanje Please help evaluate if we need to document this change. Heap profiling is more of an internal setting to me. What do you think?
