### ISSUE TITLE
document type casting of jsonb and bytea

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1320]
### Related code PR

The latest type casting table. It was auto-generated by a python script. https://gist.github.com/neverchanje/8726bf4c544b0262fe77431321bcc76b

### Which part(s) of the docs might be affected or should be updated? And how?

| From/To | boolean | smallint | integer | bigint | numeric | real | double | varchar | date | timestamp | timestamp with time zone | time | interval | bytea | jsonb | rw_int256 |
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|--|
| boolean |  | ✖️ | 🔷 | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |
| smallint | ✖️ |  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟢 |
| integer | 🔷 | 🟠 |  | 🟢 | 🟢 | 🟢 | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟢 |
| bigint | ✖️ | 🟠 | 🟠 |  | 🟢 | 🟢 | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟢 |
| numeric | ✖️ | 🟠 | 🟠 | 🟠 |  | 🟢 | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |
| real | ✖️ | 🟠 | 🟠 | 🟠 | 🟠 |  | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |
| double | ✖️ | 🟠 | 🟠 | 🟠 | 🟠 | 🟠 |  | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |
| varchar | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 |  | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 |
| date | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 |  | 🟢 | 🟢 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |
| timestamp | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | 🟠 |  | 🟢 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ |
| timestamp with time zone | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | 🟠 | 🟠 |  | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ |
| time | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | ✖️ | ✖️ | ✖️ |  | 🟢 | ✖️ | ✖️ | ✖️ |
| interval | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | ✖️ | ✖️ | ✖️ | 🟠 |  | ✖️ | ✖️ | ✖️ |
| bytea | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |  | ✖️ | ✖️ |
| jsonb | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🔷 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |  | ✖️ |
| rw_int256 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | 🔷 | 🟠 | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ | ✖️ |  |

**Comment by hengm3467** [comment]
@neverchanje Thanks for the script. It's super clever. 

The pages are updated:
https://docs.risingwave.com/docs/current/data-type-casting/
https://docs.risingwave.com/docs/dev/data-type-casting/

**Comment by hengm3467** [comment]
Closing as completed.
