### ISSUE TITLE
Bug: demos may need to switch from `timestamp` to `timestamptz` according to current tests

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave-docs-legacy#1330]
### Where's the bug?

(see table below)

### Describe the bug

We initially designed the demos using `timestamp`, and then switched to `timestamptz` for better zone-agnostic support. The demo repo (now integration tests folder) has been switched to use `timestamptz` for most cases (started https://github.com/risingwavelabs/risingwave-demo/pull/40 latest status [here](https://github.com/risingwavelabs/risingwave/tree/main/integration_tests)) but the doc is still using old queries with `timestamp`.

All impacted demos:
|doc page|latest test|
|-|-|
|https://docs.risingwave.com/docs/current/real-time-ad-performance-analysis/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/ad-ctr/create_source.sql|
|https://docs.risingwave.com/docs/current/server-performance-anomaly-detection/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/cdn-metrics/create_source.sql|
|https://docs.risingwave.com/docs/current/fast-twitter-events-processing/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/twitter/create_source.sql|
|https://docs.risingwave.com/docs/current/clickstream-analysis/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/clickstream/create_source.sql|
|https://docs.risingwave.com/docs/current/live-stream-metrics-analysis/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/livestream/create_source.sql|
|https://docs.risingwave.com/docs/current/use-risingwave-to-monitor-risingwave-metrics/|https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/prometheus/create_source.sql|

cc @neverchanje

**Comment by xiangjinwu** [comment]
I tried to follow the demo and encountered some other issues. Still figuring them out. These may need a fix in the main repo.
* ~~My local docker version was too old and unable to parse the docker-compose.yml files.~~
* Docker compose starts compactor using 1.2.0 but compute/frontend/meta using 1.0.0
* compactor/compute/frontend exits immediately with error: `invalid value 'info' for '--metrics-level <METRICS_LEVEL>': invalid digit found in string`

**Comment by hengm3467** [comment]
Thanks for identifying this issue! @xiangjinwu . I also ran into issues, and I think @wcy-fdu is fixing the version compatibility issue.

**Comment by hengm3467** [comment]
@xiangjinwu I just tried one of the examples (real-time ad performance analysis), and it works fine now. 
i'll update the docs to use `timestamptz`.

**Comment by hengm3467** [comment]
@CharlieSYH Please help make the updates. Remember to validate the examples work in the environment. Thanks.
