### ISSUE TITLE
Deprecate the term connector-node in the dev version

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1353]
### Related code PR

Please wait until https://github.com/risingwavelabs/risingwave/issues/12090 is done.

### Which part(s) of the docs might be affected or should be updated? And how?

Remove https://docs.risingwave.com/docs/current/key-concepts/#connector-node

**Comment by hengm3467** [comment]
@chenzl25 @lmatz Can we remove all descriptions of connector nodes in the documentation for v1.4?

**Comment by chenzl25** [comment]
Yes, we can. However, for binary part in `Run RisingWave for testing purposes` I think we should tell users to prepare a JRE(Java Runtime Environment) for RisingWave to ensure the embedded connector can initialize successfully.

https://docs.risingwave.com/docs/current/risingwave-trial/?method=binaries#optional-enable-the-connector-node

**Comment by hengm3467** [comment]
> Yes, we can. However, for binary part in `Run RisingWave for testing purposes` I think we should tell users to prepare a JRE(Java Runtime Environment) for RisingWave to ensure the embedded connector can initialize successfully.
> 
> https://docs.risingwave.com/docs/current/risingwave-trial/?method=binaries#optional-enable-the-connector-node

Thanks! @chenzl25  What are the required versions of JRE (or JDK if applicable)?

**Comment by chenzl25** [comment]
openjdk-11-jdk

**Comment by hengm3467** [comment]
@emile-00  You may start working on this one now: removing connector-related content, and adding a note about JRE version reuqirement for running RisingWave with binaries.

**Comment by hengm3467** [comment]
@emile-00  As I was working on #1492  that involved the changes of the risingwave-trial file, I made the changes in that PR. If you haven't started, you are off the hook now.
