### ISSUE TITLE
Require helm 3.7+ when deploying RisingWave k8s

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1413]
### Related code PR

I tried helm 3.5 and failed.

### Which part(s) of the docs might be affected or should be updated? And how?

https://docs.risingwave.com/docs/current/risingwave-k8s-helm/

### Reference

@arkbriar said that the helm chart depends on a 3.7+ helm function.

**Comment by arkbriar** [comment]
Kindly refer to the [FAQ](https://github.com/risingwavelabs/helm-charts#2-got-error-template-risingwavetemplatesmeta-stsyaml17974-executing-risingwavetemplatesmeta-stsyaml-at-subchartsminio-nil-pointer-evaluating-interface-minio-what-should-i-do) for detailed explanation.
