### ISSUE TITLE
document the flush command

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1451]
### Which part(s) of the docs might be affected or should be updated? And how?

It's been 2yrs since we introduced this command. Generally, we need to let users know that they need to call FLUSH every time they write data. Therefore, it requires both the sql command document and some updates to the INSERT/DELETE/UPDATE doc. 

As I discussed with @hzxa21 offline, I wonder if we can leverage partial checkpoint to enable more frequent flushes from the client, for example, flush on every insert command. As a result, it will allow us to get rid of the FLUSH command. cc @fuyufjh I'll bring up a technical discussion at the kernel side later.

**Comment by hengm3467** [comment]
My understanding is we'll document it for now but will remove the command in the future. Correct? @neverchanje
