### ISSUE TITLE
Document: chore: add a docker compose file for standalone mode

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1476]
This issue tracks the documentation update needed for the merged PR #13233.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13233
Source PR Merged At: 2023-11-03T07:30:36Z

**Comment by CharlieSYH** [comment]
In the latest code, the docker-compose file for the standalone mode is `docker-compose-standalone.yml`, and the distributed mode is `docker-compose.yml`.
In the next release, the standalone mode will be updated to `docker-compose.yml`, and the distributed mode will be `docker-compose-distributed.yml`.

**Comment by hengm3467** [comment]
Can we update the related topics now, or we need to wait for the changes to be implemented?

**Comment by neverchanje** [comment]
I suggest updating the topic in the dev branch. @lmatz I think it's ready, is it?

**Comment by lmatz** [comment]
> I suggest updating the topic in the dev branch. @lmatz I think it's ready, is it?

Although We haven't tested the standalone mode in all the testing pipelines, it has been used in some perf test pipelines since today.

No major issues have been found right now. @huangjw806 will continue working on that.

I feel both okay about whether to update it now.
