### ISSUE TITLE
Bug: some required fields were labelled optional

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1477]
### Where's the bug?

https://docs.risingwave.com/docs/current/sink-to-doris/

### Describe the bug

Doris sink
- doris.username
- doris.password
- doris.database
- doris.table

Iceberg sink
- table.name
- database.name
- warehouse.path

These fields are actually required.

This bug is found by the tool I introduced in https://github.com/risingwavelabs/risingwave/pull/13227

**Comment by CharlieSYH** [comment]
@neverchanje 

Regarding the Iceberg sink, the `warehouse.path` field appears to be conditional:

```
| warehouse.path  | Conditional. The path of the Iceberg warehouse. Currently, only S3-compatible object storage systems, such as AWS S3 and MinIO, are supported. It's required if the `catalog.type` is  `storage`.|
```

**Comment by neverchanje** [comment]
cc @liurenjie1024 Please kindly help review the iceberg options

**Comment by liurenjie1024** [comment]
Sorry, my mistake. the `warehouse.path` is not optional.
