### ISSUE TITLE
Document the default schema name

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#148]
It has been changed from "dev" to "public".
https://github.com/singularity-data/risingwave/pull/3166

**Comment by hengm3467** [comment]
Please note that this is the default scheme name, not the default database name.

**Comment by CharlieSYH** [comment]
@hengm3467 This change is already implemented in the docs. Close the issue if it's all good.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/100549427/183003796-f45b09e5-21ed-4f90-a5df-807f36299b88.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/100549427/183003760-e51636c5-b3cb-4563-a4d4-892b60364a74.png">
