### ISSUE TITLE
provide better examples for protobuf source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1483]
### Which part(s) of the docs might be affected or should be updated? And how?

The document only mentions `main_message`. However, the correct message name is `package.message_name`. Users may be unaware of the message convention.

```sql
CREATE SOURCE IF NOT EXISTS source_abc 
WITH (
   connector='kafka',
   topic='demo_topic',
   properties.bootstrap.server='172.10.1.1:9090,172.10.1.2:9090',
   scan.startup.mode='latest',
   scan.startup.timestamp_millis='140000000'
) FORMAT PLAIN ENCODE PROTOBUF (
   message = 'main_message',
   location = 'https://demo_bucket_name.s3-us-west-2.amazonaws.com/demo.proto'
);
```

**Comment by hengm3467** [comment]
@neverchanje  Thanks! This convension only applies to Protobuf or any source?

**Comment by neverchanje** [comment]
Just Protobuf for now:
https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/twitter/pb/create_source.sql Here is the demo where the package name is twitter.schema and the message name is twitter.schema.Event.

Avro's namespace is not required and so the message will simply be 'Event' by default. 
Here is the same demo but with Avro encoding: https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/twitter/avro/create_source.sql
I need some other test to see if the message name alone is not enough when there is a namespace.
