### ISSUE TITLE
Style: navbar dropdown is covered by logo section

### ISSUE THREAD

**Issue by cloudcarver** [risingwavelabs/risingwave-docs-legacy#15]
<img width="315" alt="Screen Shot 2022-03-23 at 10 47 16 AM" src="https://user-images.githubusercontent.com/52522981/159614435-932b4e17-1d45-4e0b-b893-7294b69ffa31.png">

Sometime when you try to move the cursor down to click the dropdown menu, the dropdown will be closed so that you cannot click it.

**Comment by ghost** [comment]
this bug was fixed.
