### ISSUE TITLE
documents how protobuf any type maps to risingwave data type

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1508]
### Which part(s) of the docs might be affected or should be updated? And how?

https://docs.risingwave.com/docs/dev/protobuf-types/

**Comment by neverchanje** [comment]
@tabVersion Could please help check how any type is handled now?

**Comment by CharlieSYH** [comment]
Please also help check the entire table to ensure that the info is current and complete.
