### ISSUE TITLE
Document configurations for serving-only compute nodes

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1510]
https://github.com/risingwavelabs/risingwave/pull/13239

It is related to batch serving mode.
It is also related to performance tuning. 

Guess it can be referred to in both places.
I try to make the config file itself as self-contained as possible.
If I miss anything or express unclearly in the `toml` file, please let me know and I will fix that in the kernel repository too.

**Comment by hengm3467** [comment]
@lmatz  Questions:
- How to enable a serving-only compute node? I assume loading the toml file would be one of the steps. What are other requirements/prerequistes?
- About batch serving mode, I remember we don't have a manual switch to enable/disable the batch/streaming. But I guess we can remind people that they shouldn't do batch queries while a streaming job is running. Correct?

**Comment by lmatz** [comment]
>How to enable a serving-only compute node?

https://docs.risingwave.com/docs/current/dedicated-compute-node/

> we don't have a manual switch to enable/disable the batch/streaming

Correct

> But I guess we can remind people that they shouldn't do batch queries while a streaming job is running. Correct?

I would say that running together is fine as long as batch queries and streaming queries are not resource-intensive at the same time. 
We may recommend users to use `batch mode + streaming mode` in production while `both` is just for testing.
