### ISSUE TITLE
Document: fix(meta): fix ctrl c cancels streaming job

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1519]
This issue tracks the documentation update needed for the merged PR #13415.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13415
Source PR Merged At: 2023-11-14T11:03:57Z

**Comment by hengm3467** [comment]
We'll document this trick, and we'll also need to define what a streaming job is. 
A streaming job is a job that creates a materialized view, a source, or a table with connectors. @neverchanje Is my understanding correct?

**Comment by neverchanje** [comment]
Also includes indexes and sinks 😅🤣
