### ISSUE TITLE
Document: feat(frontend): support kill command

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1524]
This issue tracks the documentation update needed for the merged PR #13434.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13434
Source PR Merged At: 2023-11-15T08:25:54Z

**Comment by hengm3467** [comment]
This command is related to `show processlist`. Please add this command to the page that describes the `show processlist` command.

**Comment by neverchanje** [comment]
Close as done
