### ISSUE TITLE
Document: Different display format for array/struct with pg

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1525]
## Context
Source Issue URL: https://github.com/risingwavelabs/risingwave/issues/4769
Created At: 2022-08-21T10:47:41Z
Created By: xxchan
Closed At: 2023-11-15T09:07:05Z

**Comment by hengm3467** [comment]
This is a bit complex. @CharlieSYH Please evaluate if we have descriptions and examples in array/struct/jsonb topics that are impacted by the fix/change.

**Comment by neverchanje** [comment]
There is no need for additional documentation. The PR just ensured the consistency between PG and RW.
