### ISSUE TITLE
document the warpstream integration

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1534]
### Related code PR

https://docs.warpstream.com/warpstream/how-to/integrations/use-warpstream-with-risingwave
https://github.com/risingwavelabs/risingwave-tutorials/blob/main/docs/start/warpstream.md

### Which part(s) of the docs might be affected or should be updated? And how?

I noticed that we've supported the integration with Warpstream but we didn't document it officially. @fahadullahshah26 I am not sure if it's intended or just because you forgot. If it's latter case, I personally suggest just adding it to the integration table: https://docs.risingwave.com/docs/current/rw-integration-summary/ and refer readers to the tutorial page.

**Comment by hengm3467** [comment]
Hi @emile-00 , please work with Fahad to have this integration documented. Maybe you can give him a quick walkthrough about how to update docs. Thanks.
