### ISSUE TITLE
Remind users not to mix operator and helm chart when installing risingwave cluster

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1542]
saw the conversation in the trouble-shooting channel, what do you think cc: @arkbriar 
is it necessary

**Comment by hengm3467** [comment]
I don't see the conversation, but isn't this a common sense? 
We don't need to have a note about every possible mistake that people can make. I'm not being mad. Just my 2 cents. :)

**Comment by arkbriar** [comment]
> is it necessary

I don't think so. It's just because the user could not remember and didn't check his deployment. Mixing them is technically fine.

> We don't need to have a note about every possible mistake that people can make. I'm not being mad. Just my 2 cents. :)

🤣

**Comment by lmatz** [comment]
I see, if it is technically fine, then I am fine, I thought it was the wrong approach. 
cause people who intend to try Risingwave may not have too much background in Kubernetes, that was my intention.
