### ISSUE TITLE
Change required: RW doesn't support `bit(>1)` type for MySQL

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave-docs-legacy#1547]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/13546

### Which part(s) of the docs might be affected or should be updated? And how?

MySQL CDC source

**Comment by hengm3467** [comment]
Similarly, this will be a note or limitation to be added to the MySQL CDC topic.

**Comment by WanYixian** [comment]
<img width="997" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150207222/63eb7796-2b5d-4f90-bd00-2c725b76b831">
Checked with Heng, it's already mentioned in the doc, no need to add, so close the issue now.
