### ISSUE TITLE
Change required: `date`, `time` support range different with MySQL

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave-docs-legacy#1548]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/13546

### Which part(s) of the docs might be affected or should be updated? And how?

MySQL CDC source

| MySQL Type | RisingWave Type | MySQL Range | RisingWave Range |
| ------------- | ----------------- | --------------- | ------------------ |
| time | time | `-838:59:59.000000` to `838:59:59.000000` | `00:00:00` to `23:59:59` |
| date | date | `1000-01-01` to `9999-12-31` | `0001-01-01` to `9999-12-31` |
| datetime | timestamp | `1000-01-01 00:00:00.000000` to `9999-12-31 23:59:59.49999` | `1973-03-03 09:46:40` to `5138-11-16 09:46:40` |
| timestamp | timestamptz | `'1970-01-01 00:00:01.000000` to `2038-01-19 03:14:07.499999` | `0001-01-01 00:00:00` to `9999-12-31 23:59:59`  |

**Comment by hengm3467** [comment]
This would be a limitation or note to add to the MySQL CDC page.

**Comment by cyliu0** [comment]
There is a compatible issue with `datetime` type https://github.com/risingwavelabs/risingwave/issues/13582 . I'll update the above table once it's resolved
