### ISSUE TITLE
Bug: S3 docs missing key information

### ISSUE THREAD

**Issue by rotten** [risingwavelabs/risingwave-docs-legacy#1554]
### Where's the bug?

https://docs.risingwave.com/docs/0.1.16/create-source-s3

### Describe the bug

This page left me with more questions than answers:

- There is no prefix argument, so does this mean the source reads in all the objects in that S3 bucket?
- Do the objects have to be csv files?  If not, what are my other options?
- Can I create a column with the source file name?
- If new files show up in the bucket do they automatically get slurped in?
- Does this happen on some sort of configurable cadence or is it triggered somehow or is it just the once when I run the command?
- What happens when one file in the bucket is something unexpected (an image or something)?  Does it process everything except that file?  Does it fail completely?
- What happens when part of a file is poorly formatted?

**Comment by hengm3467** [comment]
@tabVersion @cyliu0 Could you please help take a look at the questions above? Thanks!

**Comment by tabVersion** [comment]
Hi @rotten, thanks for trying RisingWave

> There is no prefix argument, so does this mean the source reads in all the objects in that S3 bucket? 

We have designed a prefix arg for that. RisingWave relies on https://github.com/apache/incubator-opendal for both S3 source and GCS source and we are waiting for its prefix filter impl. It is expected to be released in the next two versions.
Of course, we will reach out to you as soon as the feature is done, cc @wcy-fdu 

>  Do the objects have to be csv files? If not, what are my other options?

Currently, we support csv files and [ndjson](https://ndjson.org/) files

> Can I create a column with the source file name?

We are planning for this feature, https://github.com/risingwavelabs/rfcs/pull/79

> If new files show up in the bucket do they automatically get slurped in?

Yes, RisingWave keeps querying file lists and detects if there are newly added files. Note that if you update a file, i.e. delete a  file and add a new file with the same name at the same time, RisingWave will not notice that. 

> Does this happen on some sort of configurable cadence or is it triggered somehow or is it just the once when I run the command?

source means the entry of the DAG, you need to create a mv from the source or create a table with s3 connector to read the data

```
create materialzied view mv as select * from s3_source;

create table t ( ... ) with ( connector = 's3_v2', ... ); // <- we encourage use 's3_v2', it uses a more efficient plan. We keep 's3' for compatibility reasons.
```

> What happens when one file in the bucket is something unexpected (an image or something)? Does it process everything except that file? Does it fail completely?

RisingWave is going to interpret the file in the given rules, seeing it as a csv or ndjson file, and try its best to parse each line and report warnings if it cannot be parsed. It is expected to have massive warnings in this case. 
RisingWave will not fail completely in the source part. 

> What happens when part of a file is poorly formatted?

Ditto. RisingWave will discard this part.

**Comment by rotten** [comment]
> > If new files show up in the bucket do they automatically get slurped in?

> Yes, RisingWave keeps querying file lists and detects if there are newly added files. Note that if you update a file, i.e. delete a file and add a new file with the same name at the same time, RisingWave will not notice that.

Does this mean there is a table in RisingWave that I can query which lists all of the files that have been consumed (perhaps with additional meta data about the file and consumption)?

**Comment by tabVersion** [comment]
> > > If new files show up in the bucket do they automatically get slurped in?
> 
> > Yes, RisingWave keeps querying file lists and detects if there are newly added files. Note that if you update a file, i.e. delete a file and add a new file with the same name at the same time, RisingWave will not notice that.
> 
> Does this mean there is a table in RisingWave that I can query which lists all of the files that have been consumed (perhaps with additional meta data about the file and consumption)?

Yes, the internal table is associated with s3 source. You can see all files in the task queue, which includes finished files, ongoing files and not started ones.
