### ISSUE TITLE
Document: test(connector): add kafka-cdc-sink compatible test

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1558]
This issue tracks the documentation update needed for the merged PR #13607.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13607
Source PR Merged At: 2023-11-23T05:22:15Z

**Comment by neverchanje** [comment]
@xuefengze Is there anything you want to document? If not, I suggest closing it for now

**Comment by lmatz** [comment]
There are a few incompatibilities as described in the issue

> unsupport type: array, struct
time, timestamp's precision is milliseconds, https://github.com/risingwavelabs/risingwave/issues/13564
In our implementation, [interval](https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/sink/formatter/debezium_json.rs#L285), [decimal](https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/sink/formatter/debezium_json.rs#L300)'s schema type can't convert by [Debezium JDBC](https://debezium.io/documentation/reference/2.4/connectors/jdbc.html#jdbc-field-types), so just use text type in PG.

Could you elaborate on the issues from the users' perspective @xuefengze ? e.g. if users are using RW CDC sink to Kafka, what should they be cautious about

**Comment by hengm3467** [comment]
Close as completed in #1565
