### ISSUE TITLE
Document: fix(integration_tests): use `timestamptz` for BigQuery, Cassandra and Redis

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1559]
This issue tracks the documentation update needed for the merged PR #13616.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13616
Source PR Merged At: 2023-11-23T10:22:29Z

**Comment by xiangjinwu** [comment]
Went through the doc for BigQuery, Cassandra and Redis. No examples need to be updated.
