### ISSUE TITLE
Document: fix(sink): ClickHouse DateTime64 should be timestamptz

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1570]
This issue tracks the documentation update needed for the merged PR #13672.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13672
Source PR Merged At: 2023-11-28T09:28:52Z

**Comment by hengm3467** [comment]
@neverchanje Can we ask someone from engineering to summarize the data type mapping between RisingWave and ClickHouse?

**Comment by WanYixian** [comment]
Hello @xxhZs, could you help summarize the data type mapping between RW and ClickHouse? I'll update the doc once it's done. Thanks!

**Comment by xxhZs** [comment]
rw => clickhouse
bool =>Bool,
smallint => UInt16 or Int16
int => UInt32 or Int32
bigint => UInt64 or Int64
real(float32) => Float32,
float(float64) => Float64,
decimal => Decimal,
date => Date32
varchar => String
timestamptz =>DateTime64
struct => Nested（Note that Nested is converted to a Array in clickhouse, and multiple nesting is not supported,  so the sink is written in the same way.）
list => Array
serial => UInt64 or Int64
