### ISSUE TITLE
reorganize the source formats and encodings

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1572]
### Which part(s) of the docs might be affected or should be updated? And how?

Our syntax was refactored several months ago but the document didn't update accodingly.

<img width="258" alt="Screenshot 2023-11-29 at 10 31 57" src="https://github.com/risingwavelabs/risingwave-docs/assets/6970676/e37790c6-8b3e-4301-9dfa-a7100965ed70">

I suggest reorg the section into multiple formats, each having multiple subitems that correspond to the supported encodings:

- PLAIN
  - BYTES
  - AVRO
  - JSON
  - PROTOBUF
- UPSERT
  - JSON
  - AVRO
- DEBEZIUM
  - JSON
  - AVRO
- DEBEZIUM_MONGO
  - JSON
- CANAL
  - JSON
- MAXWELL
  - JSON

We can also reduce the duplicate descriptions for each format-encoding pair, reusing one description for the format. Each encoding will only need their brief description.

**Comment by hengm3467** [comment]
I'll draft a summary of the refactoring, and provide it here.
