### ISSUE TITLE
Document: feat(streaming): flow control executor

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1573]
This issue tracks the documentation update needed for the merged PR #11919.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/11919
Source PR Merged At: 2023-08-29T14:58:29Z

**Comment by emile-00** [comment]
Not included in v1.5 release

**Comment by neverchanje** [comment]
> SET RW_STREAMING_RATE_LIMIT=2000;

This session variable is what essentially introduced in the PR.

**Comment by hengm3467** [comment]
@ShanlanLi  Please incliude this new runtime parameter "RW_STREAMING_RATE_LIMIT" when you update the runtime parameters table. Please check the comments at the botoom of the code PR page for the description of this parameter. 
It can be something similar to the summary below:

"The rate limit is the maximum number of records per second per source. The source here refers to an upstream source or snapshot read in the backfilling process."
