### ISSUE TITLE
Document: fix(integration_tests): use `timestamptz` for MySQL, TiDB, Doris and StarRocks

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1575]
This issue tracks the documentation update needed for the merged PR #13641.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13641
Source PR Merged At: 2023-11-29T08:35:43Z

**Comment by hengm3467** [comment]
We should update all data type mapping tables for these combinations. @WanYixian Since you are working on a related change (timestamp & timestamptz), I'm assigning the issue to you. Let me know if you have questions.

**Comment by WanYixian** [comment]
1. https://docs.risingwave.com/docs/dev/sink-to-elasticsearch/#data-type-mapping
2. https://docs.risingwave.com/docs/dev/sink-to-doris/#data-type-mapping
3. https://docs.risingwave.com/docs/dev/sink-to-cassandra/#data-type-mapping---risingwave-and-cassandra
4. https://docs.risingwave.com/docs/dev/sink-to-iceberg/#data-type-mapping
5. https://docs.risingwave.com/docs/dev/sink-to-bigquery/#data-type-mapping
6. https://docs.risingwave.com/docs/dev/ingest-from-postgres-cdc/#data-type-mapping
7. https://docs.risingwave.com/docs/dev/create-sink-kafka/#data-type-mapping---risingwave-and-debezium-json
8. https://docs.risingwave.com/docs/dev/sink-to-tidb/#data-type-mapping

Hi @xiangjinwu, above are the data mapping tables that mention `timestamptz`/`timestamp with time zone`. 

I'm not 100% sure if changes are required from the doc side. When you have time, could you help further check the rows of `timestamptz`/`timestamp with time zone` and see if their names are accurate, and if the data mapping is correct?

Let me know if any revision is needed and I'll make the necessary changes promptly. Thanks!

**Comment by xiangjinwu** [comment]
* MySQL/Doris: no update needed
* TiDB
  * As a canal json **source**, both `datetime` and `timestamp` from TiDB map to `timestamp` in RisingWave. This will be fixed later. https://github.com/risingwavelabs/risingwave/issues/13682
  * As a MySQL-compatible JDBS **sink**, `timestamptz` from RisingWave maps to `timestamp` in TiDB. This is same as MySQL source/sink.
* Elasticsearch / Cassandra / Iceberg / BigQuery / PostgreSQL / kafka connect json (debezium): not part of linked PR
