### ISSUE TITLE
Change required: add deltalake compatibility matrix

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave-docs-legacy#1599]
### Which part(s) of the docs might be affected or should be updated? And how?

In deltalake sink add compatibility matrix. The following version is supported after testing. 
delta     spark
2.4.x     3.4.x

2.3.x     3.3.x

2.2.x     3.3.x

2.1.x     3.3.x

**Comment by neverchanje** [comment]
@emile-00 please feel free to reassign someone else if you dont have the bandwidth. Thanks
