### ISSUE TITLE
Document: feat(expr): support streaming make_timestamptz

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1618]
This issue tracks the documentation update needed for the merged PR #13702.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13702
Source PR Merged At: 2023-12-07T21:46:42Z

**Comment by KeXiangWang** [comment]
Temporarily pause this issue. `make_timestamp` use a new mechanism of timezone, which is still under investigation. In case of future compatibility issues, let's first keep it stealth for now.

**Comment by WanYixian** [comment]
Keep it stealth for now, so no need to doc at this moment
