### ISSUE TITLE
Document filter clause for selective aggregates

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#163]
The related PR is https://github.com/singularity-data/risingwave/pull/3626
Please see the test queries for the syntax. Can also take a look at this page for reference: https://modern-sql.com/feature/filter

**Comment by hengm3467** [comment]
The feature is not completed yet. Its readiness depends on https://github.com/singularity-data/risingwave/pull/3683

**Comment by CharlieSYH** [comment]
We will document this feature in 0.1.11.
