### ISSUE TITLE
Document: feat: Add statement_timeout for query.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1642]
This issue tracks the documentation update needed for the merged PR #13933.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13933
Source PR Merged At: 2023-12-13T10:08:10Z

**Comment by neverchanje** [comment]
Related issue: https://github.com/risingwavelabs/risingwave-docs/issues/1642
We do not have an aggregated place for all session variables for now.

**Comment by hengm3467** [comment]
@neverchanje  session parameter = runtime parameter. Would this page work? https://docs.risingwave.com/docs/current/view-configure-runtime-parameters/
