### ISSUE TITLE
Document: feat: delay temporal filter && optimize dyn filter with always relax condition

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1655]
This issue tracks the documentation update needed for the merged PR #13985.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13985
Source PR Merged At: 2023-12-18T07:44:06Z

**Comment by hengm3467** [comment]
Please ping @st1page to write about this feature, and use that as the input. Thank you both! @st1page and @WanYixian
