### ISSUE TITLE
Change required: `SELECT DISTINCT ON` is not documented

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#1676]
### Related code PR

https://github.com/risingwavelabs/risingwave/issues/4617
https://github.com/risingwavelabs/risingwave/issues/10859

### Which part(s) of the docs might be affected or should be updated? And how?

This has been supported for long, but not documented

**Comment by st1page** [comment]
Some information about using `DISTINCT ON` and `ORDER BY` together
RW follow the PG's behavior, https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT 
> The DISTINCT ON expression(s) must match the leftmost ORDER BY expression(s). The ORDER BY clause will normally contain additional expression(s) that determine the desired precedence of rows within each DISTINCT ON group.

So when `ORDER BY` is specified, RW will give the first row in the distinct group with the ORDER BY's order.
In that case, It can be an alternative with group topN when "N=1"
https://docs.risingwave.com/docs/current/sql-pattern-topn/

```SQL
dev=> create table t(a int, b int, c int);
CREATE_TABLE
dev=> explain create materialized view mv as select distinct on (a) * from t order by b;
ERROR:  Failed to run the query

Caused by:
  Invalid input syntax: the SELECT DISTINCT ON expressions must match the leftmost ORDER BY expressions

dev=> explain create materialized view mv as select distinct on (a) * from t order by a,b;
                                                       QUERY PLAN                                                       
------------------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [a, b, c, t._row_id(hidden)], stream_key: [a], pk_columns: [a, b], pk_conflict: NoCheck }
 └─StreamGroupTopN { order: [t.a ASC, t.b ASC], limit: 1, offset: 0, group_key: [t.a] }
   └─StreamExchange { dist: HashShard(t.a) }
     └─StreamTableScan { table: t, columns: [a, b, c, _row_id] }
(4 rows)
```
