### ISSUE TITLE
Document: feat: introduce `include` clause to add additional connector columns

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1697]
This issue tracks the documentation update needed for the merged PR #13707.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13707
Source PR Merged At: 2023-12-20T06:31:20Z

**Comment by tabVersion** [comment]
let's do the doc work together with https://github.com/risingwavelabs/risingwave/pull/14215

**Comment by emile-00** [comment]
@tabVersion Should we not include this in v1.6 docs and wait until the other issue is closed?
