### ISSUE TITLE
Bug: Es sink doc don't write pk

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave-docs-legacy#1700]
### Where's the bug?

https://docs.risingwave.com/docs/current/sink-to-elasticsearch/

### Describe the bug

Our sink's primary_key needs to be specified manually in the with option, not inherited from mv.And please add primary_key to the with menu.

**Comment by xxchan** [comment]
> Our sink's primary_key needs to be specified manually in the with option

Seems described here. https://docs.risingwave.com/docs/current/data-delivery/#upsert-sinks-and-primary-keys

This also applys to ES

---

> RisingWave will use the first column in the sink definition as the Elasticsearch ID.

However, this part is true, and it's special to ES..

We don't know why we have this "feature". It looks like a bug.

> elasticsearch seems to act as if upsert, when unspecificed. Then primary_key should actually be required.
>
> https://github.com/risingwavelabs/risingwave/issues/9443#issuecomment-1758910077

cc @tabVersion @xiangjinwu

**Comment by xxchan** [comment]
> If the sink has a primary key (normally it is inherited from a materialized view), RisingWave will use the primary key as the Elasticsearch ID. If the sink doesn't have a primary key (in the case that the materialized view is append-only)

BTW, this sentence is indeed interesting and made me think what's the relationship between MV pk and sink pk. 

From https://github.com/risingwavelabs/risingwave/pull/12458 it seems sink pk can be anything and doesn't need to match MV pk. Is it correct? Does it affect any behavior?

And do we need to document the relationship somewhere like https://docs.risingwave.com/docs/current/data-delivery/#upsert-sinks-and-primary-keys? (i.e., what if MV is append-only/updatable, what if pk mismatch) (Well, if sink can work in all cases, maybe we don't have to document it)

cc @st1page  

---

Update: This might lead to UB. We'd better add warning in the doc

**Comment by xxchan** [comment]
Another minor doc bug is https://docs.risingwave.com/docs/current/data-delivery/ this page doesn't contain ES sink

**Comment by hengm3467** [comment]
> Another minor doc bug is https://docs.risingwave.com/docs/current/data-delivery/ this page doesn't contain ES sink

Did you miss it? @xxchan 
<img width="737" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100685635/602e28ca-a1e6-4a19-9f4b-d56788471bee">
