### ISSUE TITLE
Document: fix(sink): Set default es.type is '_doc', And fix pk bug 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1706]
This issue tracks the documentation update needed for the merged PR #14273.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14273
Source PR Merged At: 2023-12-29T14:43:59Z

**Comment by ShanlanLi** [comment]
This issue has been solved by pr: https://github.com/risingwavelabs/risingwave-docs/pull/1760
