### ISSUE TITLE
Document: chore(sink): exclude java iceberg and deltalake sink from connector node

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1708]
This issue tracks the documentation update needed for the merged PR #14277.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14277
Source PR Merged At: 2024-01-02T07:23:33Z

**Comment by CharlieSYH** [comment]
The current docs already reflect the latest change.
See https://docs.risingwave.com/docs/dev/sink-to-iceberg/ and https://docs.risingwave.com/docs/dev/sink-to-delta-lake/.
@wenym1 @neverchanje If there are no further changes, I'll close this issue.

**Comment by CharlieSYH** [comment]
Thanks, @WanYixian, for following up. Closing this issue right now.
