### ISSUE TITLE
Bug: refactor the MySQL and Postgres native CDC page

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave-docs-legacy#1726]
### Where's the bug?

https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/#create-a-table-using-the-native-cdc-connector-in-risingwave

### Describe the bug

Right now we have two sets of syntax to create a CDC table for two use cases. 
1. single table cdc
The syntax is 

```
CREATE TABLE [ IF NOT EXISTS ] source_name (
   column_name data_type PRIMARY KEY , ...
   PRIMARY KEY ( column_name, ... )
) 
WITH (
   connector='mysql-cdc',
   <field>=<value>, ...
)
[ FORMAT DEBEZIUM ENCODE JSON ];
```

3. multi-table cdc
- User needs to create a cdc source first via a simplified `CREATE SOURCE` syntax

```
    CREATE SOURCE mysql_mydb WITH (
    connector = 'mysql-cdc',
    hostname = '127.0.0.1',
    port = '8306',
    username = 'root',
    password = '123456',
    database.name = 'mydb',
    server.id = 5888);
```

- The create the cdc table based on the above cdc source

```
CREATE TABLE t1_rw (
    v1 int,
    v2 int,
    PRIMARY KEY(v1)
) FROM mysql_mydb TABLE 'mydb.t1';
```

I suggest to refactor the section of `Create a table using the native CDC connector in RisingWave` by organizing the **syntax** and **examples** corresponding to the above two use cases. Right now the `Example` sub section only shows a exmaple for single table cdc.
<img width="199" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/7338536/8d0927f8-d08f-4d3f-9bd5-0bb1abd09cbd">

**Comment by emile-00** [comment]
Closed via https://github.com/risingwavelabs/risingwave-docs/pull/1754
