### ISSUE TITLE
Document: feat(cdc): support transaction for shared cdc source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1732]
This issue tracks the documentation update needed for the merged PR #14375.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14375
Source PR Merged At: 2024-01-08T03:48:00Z

**Comment by CharlieSYH** [comment]
I will create doc version 1.6 after this issue is closed. @emile-00
