### ISSUE TITLE
Document the support of GCS source

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#1734]
### Which part(s) of the docs might be affected or should be updated? And how?

Ingest data - Supported sources -> (New topic) Google Cloud Storage

Syntax is similar to S3_v2, but the credentials are GCS-specific. @wcy-fdu  Please include details here. Thanks! 

```CREATE SOURCE [ IF NOT EXISTS ] source_name 
schema_definition
WITH (
   connector={ 's3' | 's3_v2' |'gcs' },
   connector_parameter='value', ...
)
FORMAT data_format ENCODE data_encode (
   without_header = 'true' | 'false',
   delimiter = 'delimiter'
); ```

### Reference

_No response_

**Comment by wcy-fdu** [comment]
GcsProperties refer to [here ](https://github.com/risingwavelabs/risingwave/blob/569b5897891ce50ce88809343f2e57db0f8516cf/src/connector/src/source/filesystem/opendal_source/mod.rs#L38), we need to add `bucket_name`, `credential`, `match_pattern` and `service_account` in Parameters, just like s3:
<img width="781" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/58715567/4de200a6-22c5-4b71-9b0d-8a433b33cabb">
