### ISSUE TITLE
Document the limitation of direct CDC from RDS 

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1746]
@StrikeW found out that
>There is a known issue (in case of  Debezium Streaming) regarding WAL sender error when decoding.
There is a workaround for this issue which is to turn off the write-through cache by modifying your parameter group, setting the rds.logical_wal_cache parameter to 0 and then restart your writer instance.

from https://groups.google.com/g/debezium/c/ix36mlmZjc0

In short, we suggest users to turn off the `wal write-through cache` option when using Risingwavee to CDC directly from RDS. Otherwise, they may lose data.

references: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Replication.Logical.html https://aws.amazon.com/blogs/database/achieve-up-to-17x-lower-replication-lag-with-the-new-write-through-cache-for-aurora-postgresql/

**Comment by StrikeW** [comment]
The affected versions: Aurora PostgreSQL versions 14.5, 13.8, 12.12, and 11.17.
ref: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-aurora-supports-postgresql-versions-logical-replication-cache/
