### ISSUE TITLE
Document that postgres-cdc won't drop replication slots on upstream

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave-docs-legacy#1747]
RisingWave won't drop replication slots on upstream, users need to drop the slot by themselves to prevent WAL files accumulated on the upstream Postgres.

https://docs.risingwave.com/docs/current/ingest-from-postgres-cdc/

**Comment by emile-00** [comment]
Closed via https://github.com/risingwavelabs/risingwave-docs/pull/1754
