### ISSUE TITLE
Document: feat: allow configure other additional columns for connectors

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1750]
This issue tracks the documentation update needed for the merged PR #14215.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14215
Source PR Merged At: 2024-01-10T15:20:18Z

**Comment by fuyufjh** [comment]
This part is a little bit complicated. Feel free to ask @tabVersion for help.

**Comment by emile-00** [comment]
Closed with #1875
