### ISSUE TITLE
Document: test(connector): add es-sink compatible test

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1763]
This issue tracks the documentation update needed for the merged PR #14522.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14522
Source PR Merged At: 2024-01-12T06:34:30Z

**Comment by xuefengze** [comment]
Already updated by https://github.com/risingwavelabs/risingwave-docs/pull/1760.
