### ISSUE TITLE
Bug: Broken links detected by ci but silenced

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave-docs-legacy#1764]
### Where's the bug?

https://docs.risingwave.com/docs/dev/rw-integration-summary/

### Describe the bug

> Available. See [Connect Metabase to RisingWave](https://docs.risingwave.com/guides/metabsase-integration.md/) for details.

The link is invalid and jumps back to the intro page. `metabase` was misspelled as `metabsase`.

There is actually a warning during github action run. Shall we make it a fatal error to help discover similar issues earlier?
https://github.com/risingwavelabs/risingwave-docs/actions/runs/7499692133/job/20416940572?pr=1756
```
Run yarn build --no-minify

Warning:  Docs markdown link couldn't be resolved: (/guides/metabsase-integration.md) in "/home/runner/work/risingwave-docs/risingwave-docs/docs/rw-integration-summary.md" for version current
Warning:  Docs markdown link couldn't be resolved: (/guides/metabsase-integration.md) in "/home/runner/work/risingwave-docs/risingwave-docs/docs/rw-integration-summary.md" for version current
...
Warning:  Docusaurus found broken links!
```
It actually reports many other broken links, for example https://docs.risingwave.com/docs/1.4/clickstream-analysis/ linking to https://docs.risingwave.com/docs/1.4/sql-function-datetime/sql-function-datetime/

**Comment by ShanlanLi** [comment]
Thanks for reminding! I'll correct it now.

**Comment by CharlieSYH** [comment]
Thanks for pointing out. We changed the setting of the broken link report from "error" to a non-disruptive "warning" a while ago (not sure why). But we do check all broken links when we create a new version for the docs.
I'll ask the web team to change the settings.

**Comment by CharlieSYH** [comment]
@luotianchun Please help change the warnings of broken links to errors that stop the CI process.

**Comment by xiangjinwu** [comment]
There are still some broken links: https://github.com/risingwavelabs/risingwave-docs/pull/1767#issuecomment-1891234805

The errors are still silenced.

**Comment by hengm3467** [comment]
@luotianchun Please take a look. Thanks!

**Comment by chrispaul-03** [comment]
Sry I just see this issue 👀, let me take a look

**Comment by xiangjinwu** [comment]
> @luotianchun Please help change the warnings of broken links to errors that stop the CI process.

We meant to change it back to `error`, rather than `ignore` as in #2009

**Comment by chrispaul-03** [comment]
> > @luotianchun Please help change the warnings of broken links to errors that stop the CI process.↳
> 
> We meant to change it back to `error`, rather than `ignore` as in #2009↳

OK @CharlieSYH cc, pls double check

**Comment by CharlieSYH** [comment]
Fixed in https://github.com/risingwavelabs/risingwave-docs/pull/2031
