### ISSUE TITLE
Bug: schema.registry.username | password is no longer a with-property

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1788]
### Where's the bug?

https://docs.risingwave.com/docs/current/ingest-from-kafka/#read-schemas-from-schema-registry

### Describe the bug

I think you need to update the docs for 1.6 kafka ingestion and schema registry:
schema.registry.username
schema.registry.password
Seems to be have moved down to where schema.registry is configured (which is nice!) :slightly_smiling_face:
Before:
```sql
create table answers_to_life with (
  connector='kafka',
  properties.bootstrap.server='localhost:9092',
  properties.sasl.username='xyz',
  properties.sasl.password='123',
  topic='all-answers',
  schema.registry.username='foo',
  schema.registry.password='bar',
) FORMAT DEBEZIUM ENCODE AVRO (
   schema.registry = 'https://schemaregistry/',
);
```
After:
```sql
create table answers_to_life with (
  connector='kafka',
  properties.bootstrap.server='localhost:9092',
  properties.sasl.username='xyz',
  properties.sasl.password='123',
  topic='all-answers',
) FORMAT DEBEZIUM ENCODE AVRO (
   schema.registry = 'https://schemaregistry/',
   schema.registry.username='foo',
   schema.registry.password='bar'
);
```

**Comment by hengm3467** [comment]
@WanYixian Please take a look. The change should be applied to both current (1.6) and dev(upcoming). Thanks.
