### ISSUE TITLE
Document: feat: Introduce jni catalog to support all catalogs

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1790]
This issue tracks the documentation update needed for the merged PR #14264.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14264
Source PR Merged At: 2024-01-18T11:46:00Z

**Comment by emile-00** [comment]
Feature not fully completed yet, not included in v1.7 doc updates

**Comment by emile-00** [comment]
Feature documented in https://github.com/risingwavelabs/risingwave-docs/pull/1978
