### ISSUE TITLE
Document: test(connector): add mysql-sink compatible test

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1795]
This issue tracks the documentation update needed for the merged PR #14688.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14688
Source PR Merged At: 2024-01-19T10:56:14Z

**Comment by xuefengze** [comment]
duplicated with https://github.com/risingwavelabs/risingwave-docs/issues/1778
