### ISSUE TITLE
Document: feat: add rw_fragment_parallelism and re-define rw_streaming_parallelism

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1807]
This issue tracks the documentation update needed for the merged PR #14789.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14789
Source PR Merged At: 2024-01-25T08:05:28Z

**Comment by WanYixian** [comment]
Just found that `rw_streaming_parallelism` wasn't documented earlier: https://github.com/risingwavelabs/risingwave-docs/issues/1713
Will check with Heng if `rw_fragment_parallelism` needs to be written.

Update: check done, needs to be documented here https://docs.risingwave.com/docs/dev/rw_catalog/#available-risingwave-catalogs
