### ISSUE TITLE
Bug: link of starrocks sink in integration summary page is not correct

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1809]
### Where's the bug?

https://docs.risingwave.com/docs/dev/rw-integration-summary/#other-databases

### Describe the bug

<img width="780" alt="Screenshot 2024-01-26 at 09 51 42" src="https://github.com/risingwavelabs/risingwave-docs/assets/6970676/7229213e-8989-488b-bd02-adea542ce487">

The doc link is perahsp incorrect and not rendered as expected.

**Comment by WanYixian** [comment]
Close this issue as it's already fixed in this [commit](https://github.com/risingwavelabs/risingwave-docs/commit/c804abe84f485172f1b73ea795a434ecadab1e9a) by Charlie. 

![image](https://github.com/risingwavelabs/risingwave-docs/assets/150207222/040473f4-4ac2-4478-8043-3a063743acb9)
