### ISSUE TITLE
Document: feat: merge config for auto scale & enable auto scale 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1831]
This issue tracks the documentation update needed for the merged PR #14873.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14873
Source PR Merged At: 2024-02-01T09:05:32Z

**Comment by neverchanje** [comment]
Adaptive scaling will be available for new streaming jobs by default since 1.7.
This can bring potential risks to some users who requires extreme readiness and stability. Users should be informed in the release note that they still have the option to disable this feature and stay the way it was via setting disable_automatic_parallelism_control to true. However, enabling this feature will give them a smoother experience in scaling. Eventually, we'll deprecate this option and make the new scaling mechanism always-on.

cc @shanicky

**Comment by hengm3467** [comment]
@neverchanje @shanicky If the default option is turned on, would it increase resources (scaling up or out) in a way that users don't expect?

**Comment by neverchanje** [comment]
https://www.notion.so/risingwave-labs/Scaling-Guide-Draft-fed952aafccf4f30aba5b9678af80429?pvs=4 This is the draft. Please help refine based on it.
