### ISSUE TITLE
Document: refactor(test): refactor sql udf test

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1837]
This issue tracks the documentation update needed for the merged PR #14941.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14941
Source PR Merged At: 2024-02-04T16:50:26Z

**Comment by ShanlanLi** [comment]
@xzhseh I think the [latest doc of sql udf example](https://docs.risingwave.com/docs/current/sql-create-function/#examples-1) is aligned with the latest test file. I remember I edited it according to the latest test file in v1.7 doc and ask you to check it.  Could you please help check it again and tell me if it needs to be changed?

**Comment by xzhseh** [comment]
> @xzhseh I think the [latest doc of sql udf example](https://docs.risingwave.com/docs/current/sql-create-function/#examples-1) is aligned with the latest test file. I remember I edited it according to the latest test file in v1.7 doc and ask you to check it. Could you please help check it again and tell me if it needs to be changed?

Yep it should've already been done, I'll close this issue as completed.
