### ISSUE TITLE
Document: fix(sql-udf): correctly handle `udf_binding_flag` & `udf_global_count`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1838]
This issue tracks the documentation update needed for the merged PR #14906.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14906
Source PR Merged At: 2024-02-04T18:11:27Z

**Comment by ShanlanLi** [comment]
Our doc already had the example in the code pr.
