### ISSUE TITLE
Document: fix: remove `privatelink.targets` from with_options in frontend

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1848]
This issue tracks the documentation update needed for the merged PR #14907.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14907
Source PR Merged At: 2024-02-04T04:53:51Z

**Comment by WanYixian** [comment]
Close this issue as no need to change the doc. Confirmed with Siyuan and Tao.
