### ISSUE TITLE
Backup Documentation Clarification of URL syntax

### ISSUE THREAD

**Issue by rotten** [risingwavelabs/risingwave-docs-legacy#1850]
### Where's the bug?

https://docs.risingwave.com/docs/current/meta-backup

### Describe the bug

It would be helpful if you provided an actual example of a URL and folder name.  I'm assuming it needs to be an S3 or S3-compatible URL?  

Can I use a google storage url, etc...?

I can make some guesses and do some experiments, so it isn't really a major problem, but it would be nice to have a 'real world' example on this page.

**Comment by hengm3467** [comment]
@rotten Thanks for reporting the bug! We'll improve the documentation accordingly.
