### ISSUE TITLE
Bug:  create sink into table bug

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave-docs-legacy#1855]
### Where's the bug?

https://docs.risingwave.com/docs/current/sql-create-sink-into/

### Describe the bug

CREATE SINK orders_sink0 FROM orders_s0 INTO orders;
CREATE SINK orders_sink1 FROM orders_s1 INTO orders;

need fix:
CREATE SINK orders_sink0 INTO orders FROM orders_s0 ;
CREATE SINK orders_sink1 INTO orders  FROM orders_s1 ;

**Comment by hengm3467** [comment]
@WanYixian Please take a look. Thanks.
