### ISSUE TITLE
Document: feat(frontend): support tab-completion for `[ALTER SYSTEM] SET`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1858]
This issue tracks the documentation update needed for the merged PR #15123.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/15123
Source PR Merged At: 2024-02-19T09:05:56Z

**Comment by ShanlanLi** [comment]
This doesn't need documentation update as users know it very well.
