### ISSUE TITLE
Bug: bullet points showing as numbered list items

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#1866]
### Where's the bug?

https://docs.risingwave.com/docs/current/dbeaver-integration/

### Describe the bug

<img width="801" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100685635/d655b7d9-3333-40a8-9f8e-8488fbd6891a">

**Comment by chrispaul-03** [comment]
@DZR-Github pls help check the markdown file, thanks

**Comment by DZR-Github** [comment]
Fixed, please preview at here: https://pr-1870.d2fbku9n2b6wde.amplifyapp.com/docs/current/dbeaver-integration/
![image](https://github.com/risingwavelabs/risingwave-docs/assets/105500267/b4f07524-ddfd-4158-b1b4-1d8cf20274e5)
