### ISSUE TITLE
document neon cdc 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1923]
### Related code PR

Neon is a serverless Postgres. I used to think that the CDC is not supported due to a distinct architecture with Postgres, but it turned out that our PG CDC works for it too. We can document it as another PG vendor. 

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.notion.so/risingwave-labs/Neon-CDC-with-RisingWave-4ba4712166ed469a906791e0f0d485bf?pvs=4

**Comment by emile-00** [comment]
Closed via https://github.com/risingwavelabs/risingwave-docs/pull/1994
