### ISSUE TITLE
Bug: Sink parameters naming is incorrect in the example

### ISSUE THREAD

**Issue by sumit1094** [risingwavelabs/risingwave-docs-legacy#1945]
### Where's the bug?

https://docs.risingwave.com/docs/current/sink-to-redis

### Describe the bug

e.g. 
 I noticed that there is a typo in the section. 
redis_key_format & redis_value_format doesn't work. key_format & value_format works.

Refer Line 41 in this code - https://github.com/risingwavelabs/risingwave/blob/b0325c56ffd053dc053b2345044adc8d53f1bad6/src/connector/src/sink/redis.rs#L58

```
CREATE SINK redis_sink_2
FROM bhv_mv WITH (
    primary_key = 'user_id',
    connector = 'redis',
    redis.url= 'redis://127.0.0.1:6379/',
) FORMAT PLAIN ENCODE TEMPLATE (
    force_append_only='true',
    redis_key_format = 'UserID:{user_id}',
    redis_value_format = 'TargetID:{target_id},EventTimestamp{event_timestamp}'
);
```

**Comment by hengm3467** [comment]
@sumit1094 Thanks for letting us know. We'll fix it soon.
