### ISSUE TITLE
add presto and trino to integration summary

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1947]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/14477

### Which part(s) of the docs might be affected or should be updated? And how?

We have tested the queryability through presto and trino. We don't have to write their tutorials respectively. Instead, we only need to refer readers to https://prestodb.io/docs/current/connector/postgresql.html and https://trino.io/docs/current/connector/postgresql.html

**Comment by hengm3467** [comment]
I updated the page in dev, but not in v1.7. Please replicate the change to v1.7 as well. Thanks! @ShanlanLi
