### ISSUE TITLE
Document: feat(udf): introduce `#[derive(StructType)]` for struct types in Rust UDF

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1962]
This issue tracks the documentation update needed for the merged PR #15372.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/15372
Source PR Merged At: 2024-03-14T12:03:51Z

**Comment by ShanlanLi** [comment]
The syntax of returning struct types in Rust UDF in this PR seems to have nothing different with [what our doc has](https://docs.risingwave.com/docs/dev/udf-rust/#:~:text=CREATE%20FUNCTION%20key_value,%7D%0A%24%24%3B) now. 
<img width="663" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150168166/83a8c262-d6c3-477b-90c7-7a835b48611e">
@wangrunji0408, could you please check if it needs to be updated?

**Comment by wangrunji0408** [comment]
This has been included in #1956. No need to update.
