### ISSUE TITLE
Document: refactor(storage): remove reading range tombstone in read path and compaction

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1966]
This issue tracks the documentation update needed for the merged PR #15613.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/15613
Source PR Merged At: 2024-03-15T14:38:36Z

**Comment by WanYixian** [comment]
Checked with @wenym1, it should be mentioned in v1.8 release note, no need for the specific doc. So close it.
