### ISSUE TITLE
Doc: SHOW PARAMETERS command

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1995]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/15113

### Which part(s) of the docs might be affected or should be updated? And how?

`show parameters` mentioned on https://docs.risingwave.com/docs/dev/view-configure-system-parameters/#how-to-view-system-parameters. Update table to include description column.

@hengm3467 Should we also have a separate SQL command page for `show parameters` as well?

**Comment by hengm3467** [comment]
@emile-00 Yes. Let's do that. We should aim to provide all available commands, unless there's a strong reason not to disclouse.
