### ISSUE TITLE
Doc: MQTT source connector

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#1996]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/15388

### Which part(s) of the docs might be affected or should be updated? And how?

Add doc for MQTT source connector

**Comment by hengm3467** [comment]
@fahadullahshah261 Since you have worked on MQTT before, you are the best person to add the documentation for MQTT. Please use the documentation of other sources as reference.
