### ISSUE TITLE
Document: feat(frontend): support AS OF syntax

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1999]
This issue tracks the documentation update needed for the merged PR #15849.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/15849
Source PR Merged At: 2024-03-22T07:25:01Z

**Comment by hengm3467** [comment]
The actual related PR is https://github.com/risingwavelabs/risingwave/pull/15866
