### ISSUE TITLE
Add search bar 

### ISSUE THREAD

**Issue by cloudcarver** [risingwavelabs/risingwave-docs-legacy#2]

**Comment by Ad-Bean** [comment]
Docusaurus has official support for [Algolia DocSearch](https://docsearch.algolia.com/), should we [apply to the DocSearch program](https://docsearch.algolia.com/apply)?

here is the docs: https://docusaurus.io/docs/search

**Comment by cloudcarver** [comment]
> 

Sure, RisingWave is an open source project. I think there should be no problem to apply that program.

**Comment by Sunt-ing** [comment]
Does anyone work on this?

**Comment by Ad-Bean** [comment]
> Does anyone work on this?

Still waiting for the apply, which Algolia DocSearch will crawl our docs. If it's emergency, maybe we should work on local search first.

**Comment by Sunt-ing** [comment]
No rush. Take your time please~
