### ISSUE TITLE
Document: feat(batch): support time travel for iceberg source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2013]
This issue tracks the documentation update needed for the merged PR #15866.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/15866
Source PR Merged At: 2024-03-26T09:00:59Z

**Comment by WanYixian** [comment]
This is resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2043, so close this one.
