### ISSUE TITLE
Change required: `usage-1-delete-and-clean-expired-data` use materialized view as examples

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2045]
### Which part(s) of the docs might be affected or should be updated? And how?

https://docs.risingwave.com/docs/current/sql-pattern-temporal-filters/#usage-1-delete-and-clean-expired-data

I suggest we use `create materialized view` for both `sales` and `user sessions` examples.
![SCR-20240408-ef5](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/5cb12c6c-2875-4b15-be1e-99ad9a610ca0)

Because the point of temporal filter is to let RW automatically maintain an MV to include records within a recent period at any given time.

Besides, I intend to add one sentence:
```
The records that become out of the time range defined by the temporal filter will be deleted from the storage and the storage space will be reclaimed.
```

The reason is that users typically want to use temporal filters as a way of TTL to save space. This can answer this common question directly.

**Comment by lmatz** [comment]
Another thing to answer is that users may wonder how a table can be TTLed via the temporal filter:


To define a table with TTL by the temporal filter, the trick is to `create source X` first.

Unlike a table,
the source will pull data from upstream only after some MVs are created and their definitions include this source. The source itself does not store any records.

Then we create the materialized view, i.e. the table we want:

```
create materialized view real_X_table as
select * from
X where X.timestamp > now() - interval '1 month';
```

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2178
