### ISSUE TITLE
Document filter clauses in aggregate functions (selective aggregation)

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#206]
### Related code PR

https://github.com/singularity-data/risingwave/pull/4114

### Which part(s) of the docs might be affected or should be updated? And how?

Now support filter clauses in aggregate functions.
Add aggregate function filters (filter clause) to https://www.risingwave.dev/docs/latest/sql-function-aggregate/
Base on https://github.com/singularity-data/risingwave-docs/issues/163

### Reference

https://www.postgresql.org/docs/14/functions-aggregate.html
Google 'aggregate function filters'

**Comment by hengm3467** [comment]
Fixed in https://github.com/risingwavelabs/risingwave-docs/pull/190
