### ISSUE TITLE
Document: feat(session_config): system wide session config by alter system set 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2065]
This issue tracks the documentation update needed for the merged PR #16062.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16062
Source PR Merged At: 2024-04-12T16:44:56Z

**Comment by hengm3467** [comment]
@ShanlanLi Can you be the mentor and show Chengyi how to update the documentation based on a feature? Thanks!
