### ISSUE TITLE
Bug: Margin Right not rendering on "Help us make this doc better!" section

### ISSUE THREAD

**Issue by agiron123** [risingwavelabs/risingwave-docs-legacy#2078]
### Where's the bug?

https://docs.risingwave.com/docs/current/intro

### Describe the bug

Screenshot:
![image](https://github.com/risingwavelabs/risingwave-docs/assets/1031759/08f318dd-5756-4eb5-9158-9ed98b152fe1)

I noticed that there is some missing margin right on the botom section here.

There is a margin right present, but the style is getting overridden:
![image](https://github.com/risingwavelabs/risingwave-docs/assets/1031759/ea86d3b8-5a86-493d-b4d1-5ca9e3d0c6ce)

**Comment by Ad-Bean** [comment]
fixed, thanks!
