### ISSUE TITLE
Bug: CMD+K would trigger both "Ask AI" and the search panel.

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#2085]
### Where's the bug?

https://docs.risingwave.com/docs/current/intro/

### Describe the bug

![image](https://github.com/risingwavelabs/risingwave-docs/assets/100685635/36d503d9-bc33-46bf-86b1-cca57bd4664d)

**Comment by chrispaul-03** [comment]
@hengm3467 Can we reach out to this LLM team to disable this shortcut?

**Comment by hengm3467** [comment]
@agiron123 and @cw75 , could you please help the cmd+K shortcut for triggering the Ask AI window. It conflicts with our search panel. Thanks!

**Comment by cw75** [comment]
Hey @hengm3467 , the keyboard shortcut is configurable [here](https://github.com/risingwavelabs/risingwave-docs/blob/main/docusaurus.config.js#L233), so feel free to update to another key of your choice. Let us know if you run into issues. Thanks!

**Comment by WanYixian** [comment]
Thanks for fixing it!
