### ISSUE TITLE
Document: feat: deprecate legacy s3 connector

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2087]
This issue tracks the documentation update needed for the merged PR #16337.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16337
Source PR Merged At: 2024-04-18T10:55:21Z

Will be resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2156

**Comment by WanYixian** [comment]
FYI, just saw Bohan already updated the doc https://github.com/risingwavelabs/risingwave-docs/pull/2156

**Comment by ShanlanLi** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2156.
