### ISSUE TITLE
Document: feat(source): use fragment id only as Kafka consumer group id

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2090]
This issue tracks the documentation update needed for the merged PR #16111.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16111
Source PR Merged At: 2024-04-19T09:29:29Z

**Comment by xxchan** [comment]
For this specific change, I think we don't need to update docs.

Some related changes needed:
- https://github.com/risingwavelabs/risingwave-docs/pull/2167
- Maybe add a section in Kafka source explain "monitoring" offsets.
- Later we will support custom consumer group id. That needs to be documented.
