### ISSUE TITLE
Document: feat(cdc): add a parameter to control timeout of cdc source waiting time

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2139]
This issue tracks the documentation update needed for the merged PR #16598.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16598
Source PR Merged At: 2024-05-07T20:02:53Z

**Comment by WanYixian** [comment]
This is resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2126
