### ISSUE TITLE
Document: refactor(object_store): refactor timeout and retry of object store interface

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2147]
This issue tracks the documentation update needed for the merged PR #16231.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16231
Source PR Merged At: 2024-05-08T18:00:23Z

**Comment by WanYixian** [comment]
Close the issue as mentioning it in the release note would be enough. Confirmed with @Li0k
