### ISSUE TITLE
Document: feat: impl `key encode` clause for sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2148]
This issue tracks the documentation update needed for the merged PR #16377.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16377
Source PR Merged At: 2024-05-08T22:05:44Z

**Comment by tabVersion** [comment]
We did not specify which connector to support the feature in the code. I think every connector with message-key concept can have this feature, including Kafka, Pulsar, Kinesis, Redis.
Is that correct? @xiangjinwu

**Comment by xiangjinwu** [comment]
https://github.com/risingwavelabs/risingwave/blob/5ea0b67dfc2639800c8fb76abfaa5fc8138e0f0e/src/frontend/src/handler/create_sink.rs#L802

In addition to Kafka, Pulsar, Kinesis and Redis, the list also includes ~~MQTT~~ (but it does not have key) and **PubSub**.

(Off-topic: Nats is also an MQ but have not been migrated to the `format-encode` syntax yet. It is still using `type = ` as other non-MQ sinks. #2103 Maybe we shall prioritize its migration. Nats does not have key either, similar to MQTT.)
