### ISSUE TITLE
Document Hex integration

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2152]
### Which part(s) of the docs might be affected or should be updated? And how?

Hex is a notebook platform (consider it a Notion for data science) that allows users to share/publish their data analyses.

> Hex is a collaborative data workspace that offers data analysis tools and workflows for users of all technical backgrounds. It includes features like SQL queries, Python, R, and no-code analysis, along with collaboration tools like version control and code commenting. Users can build dashboards and data apps with Hex.
By Google Gemini.

Now I have verified the integration with it using the RisingWave Cloud. It works with no noticable bugs.

First, we should add an item to https://docs.risingwave.com/docs/current/rw-integration-summary/#bi-and-data-analytic-platforms to the list of "BI and data analytic platforms".

Then we can include a simple notice in the "Availabiblity" cell, "Available. For this integration, you can directly use Hex's PostgreSQL [data connection](https://learn.hex.tech/docs/connect-to-data/data-connections/data-connections-introduction)."

As a further improvement, I suggest separating "BI and data analytic platforms" into a page, listing all visualizations tools in a grid/table layout. For prioritized integrations, users can click into the cell for detailed tutorials.

**Comment by ShanlanLi** [comment]
@neverchanje Hi tao, as for the improvement you suggested. 
> As a further improvement, I suggest separating "BI and data analytic platforms" into a page, listing all visualizations tools in a grid/table layout. For prioritized integrations, users can click into the cell for detailed tutorials.

We are considering doing this on [our landing page](https://pr-1019.d2fbku9n2b6wde.amplifyapp.com/), like this:

<img width="1184" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150168166/5547dc72-3e5f-4e2e-9c2e-fb868646602c">

Does this form correspond to what you described?  

The pr of the landing page is: https://github.com/risingwavelabs/risingwave-docs/pull/1019.
