### ISSUE TITLE
Change required: distinguish kernel and cloud in the search result

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#2187]
### Which part(s) of the docs might be affected or should be updated? And how?

I tried search "scaling". The result is confusing:

<img width="553" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/37948597/18fcb386-913a-40ce-8529-afd149cd69c0">

**Comment by hengm3467** [comment]
@Ad-Bean Please help take a look. Thanks!

**Comment by Ad-Bean** [comment]
> @Ad-Bean Please help take a look. Thanks!

I did some research, and it might need to upgrade the Docusaurus version first.

**Comment by Ad-Bean** [comment]
![image](https://github.com/risingwavelabs/risingwave-docs/assets/54789193/c822f43a-dd91-4518-b490-bdb4aa2759d3)

![image](https://github.com/risingwavelabs/risingwave-docs/assets/54789193/bf87dfc0-c417-4f5e-a460-b8c4299e95f5)

@hengm3467 @xxchan hi, I rewrote the crawler and added the tag on titles during indexing, is this okay?

**Comment by xxchan** [comment]
LGTM!
