### ISSUE TITLE
Document: fix: remove unused `r#type` field in GooglePubSubConfig

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2193]
This issue tracks the documentation update needed for the merged PR #16785.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16785
Source PR Merged At: 2024-05-21T12:48:31Z

**Comment by WanYixian** [comment]
Close this issue as `r#type` is not documented in the doc originally.
