### ISSUE TITLE
Document: feat(func): impl quote_literal & quote_nullable

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2197]
This issue tracks the documentation update needed for the merged PR #16807.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16807
Source PR Merged At: 2024-05-23T03:49:32Z

**Comment by hengm3467** [comment]
This one looks like an internal feature, but please check @ShanlanLi
