### ISSUE TITLE
Bug: Broken links undetected for removed section about kafka consumer group

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave-docs-legacy#2207]
### Where's the bug?

https://docs.risingwave.com/docs/current/ingest-from-kafka/#related-topics

### Describe the bug

Two issues to fix:

* The stale link on `ingest-from-kafka` page shall be removed. The relevant content has been removed by #2167
* The broken link detector in CI seems still not working as expected. This issue is better found before merging the PR above, rather than reported by a user. #1764

**Comment by hengm3467** [comment]
@luotianchun & @Ad-Bean Please help look at the broken link detector in CI.

**Comment by Ad-Bean** [comment]
> @luotianchun & @Ad-Bean Please help look at the broken link detector in CI.

@luotianchun has changed `onBrokenMarkdownLinks` from `ignore` to `throw`, and I verified locally that broken links will cause the building to fail (the `metabsase` example). Could you please give some examples of broken links that the current CI workflow cannot detect?

**Comment by xiangjinwu** [comment]
> Could you please give some examples of broken links that the current CI workflow cannot detect?

It is in the issue above. The page `ingest-from-kafka` includes a link to a faq section that was removed. Maybe it only detects invalid pages but not invalid anchors (within a valid page)?

**Comment by Ad-Bean** [comment]
> > Could you please give some examples of broken links that the current CI workflow cannot detect?
> 
> It is in the issue above. The page `ingest-from-kafka` includes a link to a faq section that was removed. Maybe it only detects invalid pages but not invalid anchors (within a valid page)?

Thanks for the explanation! sorry I didn't see the URL at first. After a close look, it turns out to be a broken anchor issue instead of broken link `#how-...`, that's why the CI cannot detect the error. We might need to upgrade our docusaurus version to 3.1.x or higher to resolve the issue since the config is not provided at `2.4.3`, which is the version we currently use. cc @hengm3467 should we upgrade the docusaurus version?

**Comment by hengm3467** [comment]
@Ad-Bean Yes. Please help upgrade the docusaurus version.
