### ISSUE TITLE
Document: feat(batch): support spill hash agg for the batch query

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2217]
This issue tracks the documentation update needed for the merged PR #16771.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16771
Source PR Merged At: 2024-05-29T12:00:16Z

**Comment by WanYixian** [comment]
Confirmed with @chenzl25, we only need to mention this in Release note.
