### ISSUE TITLE
Document: feat(parser): fix token location and print sql with cursor on parse error

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2218]
This issue tracks the documentation update needed for the merged PR #16959.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16959
Source PR Merged At: 2024-05-29T12:36:30Z

**Comment by ShanlanLi** [comment]
confirmed with @wangrunji0408, this doc issue just needs to be mentioned in the release note.
