### ISSUE TITLE
Document: feat(connector): add DynamoDB sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2228]
This issue tracks the documentation update needed for the merged PR #16670.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/16670
Source PR Merged At: 2024-06-04T04:30:20Z

**Comment by neverchanje** [comment]
# Usage Document

This guide describes how to sink data from RisingWave to DynamoDB using the DynamoDB sink connector in RisingWave.

Amazon DynamoDB is a fully managed, serverless, key-value NoSQL database designed to run high-performance applications at any scale. It provides consistent, single-digit millisecond response times and offers built-in security, backup and restore, and in-memory caching. For more information about DynamoDB, see the [DynamoDB official website](https://aws.amazon.com/dynamodb/).

## Syntax

```sql
CREATE SINK [ IF NOT EXISTS ] sink_name
[FROM sink_from | AS select_query]
WITH (
   connector = 'dynamodb',
   connector_parameter = 'value', ...
)
FORMAT data_format ENCODE data_encode [ (
    format_parameter = 'value'
) ];
```

## **Parameters**

| Field | Note |
| --- | --- |
| table | Required. Name of the DynamoDB table where you want to write the data. |
| primary_key | Required. A pair of columns representing the partition key and sort key of DynamoDB, e.g, `key1,key2`, seperated by comma. |
| aws.region | Required. AWS region where your DynamoDB table is hosted. |
| aws.endpoint_url | Optional. Custom endpoint URL for connecting to DynamoDB. Useful for testing with DynamoDB Local. |
| aws.credentials.access_key_id | Conditional. AWS access key ID for accessing DynamoDB. Must be specified when using access key ID and secret key for authentication. |
| aws.credentials.secret_access_key | Conditional. AWS secret access key for accessing DynamoDB. Must be specified when using access key ID and secret key for authentication. |
| aws.credentials.role.arn | Conditional. ARN of the IAM role to assume for accessing DynamoDB. Must be specified when using AssumeRole for authentication. |
| aws.credentials.role.external_id | Conditional. External ID for assuming the IAM role specified in `aws.credentials.role.arn`. |
| aws.profile | Optional. The name of the AWS CLI profile to use for accessing DynamoDB. This profile contains the AWS credentials and region configuration. If specified, it overrides the default profile. |
| dynamodb.max_batch_rows | Optional. Maximum number of rows to write in a single batch operation to DynamoDB. This helps optimize throughput and manage rate limits. Default is 1024. |


## Partition Key and Sort Key Mapping

For the DynamoDB sink to function correctly, it is required that the source table in RisingWave has a composite primary key comprising two columns, each corresponding to the partition key and sort key defined in the target DynamoDB table. 

For example, if you are sinking data into a DynamoDB table named `movies` that is configured with a partition key `title` and a sort key `year`, you must ensure that the RisingWave table schema also defines a composite primary key with the same columns. Below is an example schema definition for the RisingWave table:

```sql
CREATE TABLE IF NOT EXISTS movies (
    year integer,
    title varchar,
    description varchar,
    primary key (year, title)
);
```

This makes sure that the data structure in RisingWave aligns with the key definition in DynamoDB, thus preventing any further misoperations.

## **Data type mapping - RisingWave and DynamoDB**

RisingWave Data Type | DynamoDB Data Type
-- | --
boolean | Bool
smallint | number (N)
integer | number (N)
bigint | number (N)
numeric | number (N)
real | number (N)
double precision | number (N)
character varying (varchar) | string (S)
bytea | binary
date | string (S)
time without time zone | string (S)
timestamp without time zone | string (S)
timestamp with time zone | string (S)
interval | string (S)
struct | map (M)
array | list (L)
JSONB | string (S)

**Comment by jetjinser** [comment]
The `struct` datatype in RisingWave will map to `map (M)` in Dynamodb: https://github.com/risingwavelabs/risingwave/blob/88bb14aa6eb481f1dc0e92ee190bafad089d2afd/src/connector/src/sink/dynamodb.rs#L386 in a recursive way.
