### ISSUE TITLE
Bug: Missing permission for service account on pub/sub subscription

### ISSUE THREAD

**Issue by swapkh91** [risingwavelabs/risingwave-docs-legacy#2248]
### Where's the bug?

https://docs.risingwave.com/docs/current/ingest-from-google-pubsub

### Describe the bug

Apart from giving the service account `Pub/Sub Subscriber` permission on the subscription, we also have to give it `Pub/Sub Viewer` permission on that subscription.
Not giving the viewer permission returns the following error when creating source
```
error checking subscription validity: Status { code: PermissionDenied, message: "User not authorized to perform this action.", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 11 Jun 2024 06:12:19 GMT"} }, source: None }
```

**Comment by tabVersion** [comment]
Yes, RisingWave uses the privilege to seek to a timestamp when start up. Will update in the doc
https://github.com/risingwavelabs/risingwave/blob/5dc3861a15bb1047610de657fd1ef27033aaaf83/src/connector/src/source/google_pubsub/enumerator/client.rs#L59-L72
