### ISSUE TITLE
Change required: document `ON CONFLICT` clause for `CREATE TABLE`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave-docs-legacy#2249]
### Related code PR

https://github.com/risingwavelabs/risingwave/issues/15515

#1860 is a work in progress for documenting this feature. However, it appears to contain some sections that have not yet reached a consensus or been implemented. I think we should document the factual part of the feature first.

### Which part(s) of the docs might be affected or should be updated? And how?

We should document the `ON CONFLICT` clause for `CREATE TABLE` statement introduced in v1.9.0.

**Comment by ShanlanLi** [comment]
will be resolved by https://github.com/risingwavelabs/risingwave-docs/pull/1860/files#diff-f45e9d50a3a4a19e7f121f0f41995f5c9935e65de4db1cf648f3fbffbd35cf49
