### ISSUE TITLE
Document generate_series() function

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#226]
### Related code PR

https://github.com/singularity-data/risingwave/pull/4030

### Which part(s) of the docs might be affected or should be updated? And how?

SQL reference -> Functions and operators - > (Maybe) Set returning -> generate_series()

### Reference

https://www.postgresql.org/docs/current/functions-srf.html

**Comment by CharlieSYH** [comment]
Duplicate with https://github.com/singularity-data/risingwave-docs/issues/212 @hengm3467

**Comment by hengm3467** [comment]
I see. Let me close this one.
