### ISSUE TITLE
Document: feat(sink): enable sink_decouple by default for kafka, pulsar, kinesis, google pubsub, nats, mqtt clickhouse

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2269]
This issue tracks the documentation update needed for the merged PR #17221.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17221
Source PR Merged At: 2024-06-14T03:06:35Z

**Comment by xxhZs** [comment]
notes: With the latest update, clickhouse is not enabled by default.
