### ISSUE TITLE
Document: feat(connector): support avro default nan/inf/-inf

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2281]
This issue tracks the documentation update needed for the merged PR #17309.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17309
Source PR Merged At: 2024-06-18T09:22:31Z

**Comment by xiangjinwu** [comment]
This is a minor update and mentioning it in release notes is enough. There is nothing on the documentation website to be updated.

**Comment by ShanlanLi** [comment]
Close as it just needs to be listed in the release notes.
