### ISSUE TITLE
Document: feat(sqlparser): allow rhs of `AT TIME ZONE` to be non-literal

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2297]
This issue tracks the documentation update needed for the merged PR #17395.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17395
Source PR Merged At: 2024-06-21T10:44:47Z

**Comment by WanYixian** [comment]
Checked with @xiangjinwu, close it as mentioning this in release notes is enough.
