### ISSUE TITLE
Missing document for functional indexes

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#2326]
### Where's the bug?

https://docs.risingwave.com/docs/dev/sql-create-index

### Describe the bug

There should be some related descriptions in the `CREATE INDEX` page. 

https://github.com/risingwavelabs/risingwave/issues/8975

**Comment by chenzl25** [comment]
We have docs here https://docs.risingwave.com/docs/current/indexes/#indexes-on-expressions
