### ISSUE TITLE
Document: chore(grafana): relative Memory usage

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2327]
This issue tracks the documentation update needed for the merged PR #17467.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17467
Source PR Merged At: 2024-06-28T13:52:45Z

**Comment by ShanlanLi** [comment]
@CAJan93 Regarding this code pr(https://github.com/risingwavelabs/risingwave/pull/17467), could you give me some suggestions on where the doc needs to be updated? Thanks!

**Comment by ShanlanLi** [comment]
Internal change, no need to update doc.
