### ISSUE TITLE
Document workaround for high join amplifcation

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2330]
Let’s say there are a few join keys that can trigger high join amplification,

currently, it will lead to the congestion of the whole job because the high join amplification of a single key produces a large number of results and they have to be processed by a single actor of that join operator. 

Therefore, simply scaling does not work.

We can split the original MV into multiple MVs by adding filtering conditions to make the data of the same key distributed to more actors, (if the data pattern and workload allow us to do so)

Let’s say the original join condition is
```
select * from
     orders
inner join
    product_description
where
orders.product_id = product_description.product_id
```

and an update from stream product_description with `product_id=1` can match 100K rows from t1 because `product_id = 1` is a hot sale product

We can try to split the MV into multiple MVs:
1. one MV with filtering conditions such as `orders.user_id % 7 = 0`, and then do the join
2. the second MV with filtering conditions such as `orders.user_id % 7 = 1`
...
...
N. the nth MV with filtering conditions `orders.user_id % 7 = 1`.

7 in total etc.

(If the `user_id` is not a number that can be applied with module operation, it needs to be processed by some hash function first. In the case when the hash function can return a negative value, we remark that in both PostgreSQL and RW, -1 % 7 = -1 instead of 6, therefore we need to include more MVs where `hash_function(orders.user_id) % 7 = -1/-2/-3/-4/-5/-6))

Finally, 
we union all the results from all 7 MVs. If user_id is uniformly distributed given `product_id = 1`, the join amplification in each actor is reduced by a factor of 7.

It all depends on whether we can find such a user_id column, i.e. high cardinality, and as uniformly distributed as possible.

**Comment by lmatz** [comment]
I suggest put it besides the current page about "high_join_amplification"
or a separate page but linked within this page

**Comment by lmatz** [comment]
cc: @hengm3467 @WanYixian 
Wonder if it can be put on the documentation soon as this high join amplification issue is quite common among our customers.

**Comment by WanYixian** [comment]
> I suggest put it besides the current page about "high_join_amplification" or a separate page but linked within this page

Hi @lmatz, is it okay to list this workaround in this [doc](https://docs.risingwave.com/docs/dev/multiple-table-sink/)  or after this [example](https://docs.risingwave.com/docs/dev/troubleshoot-high-latency/#example-high-latency-caused-by-high-join-amplification) ?

**Comment by lmatz** [comment]
Right after the example seems good

Or a separate page also linked within the example.

As long as separated from the "wide table" page, it is good
