### ISSUE TITLE
Document: fix(frontend): fix changelog out_col_change error and add snowflake upsert sink demo

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2336]
This issue tracks the documentation update needed for the merged PR #17515.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17515
Source PR Merged At: 2024-07-02T06:49:30Z

**Comment by neverchanje** [comment]
https://docs.risingwave.com/docs/dev/sink-to-snowflake/

Required doc updates:

- Explain the high-level idea of the sink process.
   The sink process from RisingWave to Snowflake utilizes [Snowpipe](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-rest-apis) for data loading. This process first stages the data in a user-managed S3 bucket in JSON, which is then loaded into the Snowflake table via Snowpipe.

- We need to introduce a new section 'ingesting upsert stream into snowflake'.   
   Snowpipe works in an append-only model, meaning that RisingWave's Snowflake sink can only support the 'append-only' mode. If the RisingWave data to be exported contains not only inserts, then creating the sink will result in an error, because non-append-only tables cannot sink into append-only destinations.
   To be able to sink a RisingWave table or materialized view in the upsert mode, a workaround is to use the `AS CHANGELOG` clause. This syntax turns any stream into append-only changelog. For more details, please read the document [AS CHNAGELOG](https://github.com/risingwavelabs/risingwave-docs/issues/2313).

  ```sql
	CREATE MATERIALIZED VIEW ss_mv AS
	WITH sub AS CHANGELOG FROM user_behaviors
	SELECT
	    user_id,
	    target_id,
	    event_timestamp AT TIME ZONE 'America/Indiana/Indianapolis' as event_timestamp,
	    changelog_op AS __op,
	    _changelog_row_id::bigint AS __row_id
	FROM
	    sub;
  ```
- Document how to create the pipe for data loading.
  ```sql
  CREATE OR REPLACE PIPE example_snowflake_pipe
    AS COPY INTO example_snowflake_sink_table
    FROM @example_snowflake_stage MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
  ```
- Document how to set up authentication to Snowflake. Instructions for RisingWave Cloud should be highlighted, as Snowflake users will likely use the hosted RisingWave as well.
- Document how to create the stage.
  ```sql
  -- snowflake stage, we only supports json as sink format at present
  CREATE OR REPLACE STAGE example_snowflake_stage
    url = '<S3_PATH>'
    credentials = ( AWS_KEY_ID = '<S3_CREDENTIALS>' AWS_SECRET_KEY = '<S3_CREDENTIALS>' )
    file_format = ( type = JSON );
  ```

**Comment by xxhZs** [comment]
other need to update : 
1. More detailed Prerequisite
```
- Ensure you have a s3 bucket that RisingWave can connect to.
- Ensure you have an upstream materialized view or source in RisingWave that you can sink data from.
- Ensure you have a rsa key-value pair for authentication. And set up the credential for the `Snowflake User`
- Ensure you have a `Snowflake table` to store the sink data from RisingWave.
- Ensure you have a `Snowflake stage` to reference the external S3 bucket, which Snowflake will use internally to load the data. Currently only json format is supported.
- Ensure you have a `Snowflake pipe` to receive the loaded data from the pre-defined stage and copy it to the Snowflake table.

Note: RisingWave will not be responsible for deleting data already imported by s3. You can manually set the lifecycle of s3 yourself to clear out useless data. You can see https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-set-lifecycle-configuration-intro.html for more details.
```
2. Correct Required permission
```
To successfully sink data into Snowflake, the S3 user account must have the appropriate permissions. These permissions include:

- For the S3:  You need to ensure that you can `WRITE` to S3

The Snowflake user account must have the appropriate permissions. These permissions include:

- For the pipe: The user must have `OPERATE`permission.
- For the stage: The user must have `USAGE` and `READ` permission.
- For the table: The user must have `INSERT` and `SELECT` permission.
- For the database: The user must have `USAGE` permission.
- For the schema: The user must have `USAGE` permission.
```
3. snowflake.private_key  add `We'll explicitly pass private_key to snowflake , and we'll roll out CREATE SECRET afterward to avoid that`
4. add sink to snowflake with upsert 
  ### Sink data with upsert
  
  Since snowflake table doesn't support update, we import the incremental logs and order of modification for each piece of data into snowflake, which you can merge as you read, or create dynamic tables to read the results of the upserts. 
  
  About dynamic tables, you can see https://docs.snowflake.com/en/user-guide/dynamic-tables-about for more details. See the examples below:
  
  **Create source in RisingWave**
  
  ```sql
  CREATE SOURCE s1_source (id int,name varchar)
  WITH (
	  connector ='datagen',
	  fields.id.kind ='sequence',
	  fields.id.start ='1',
	  fields.id.end ='10000',
	  fields.name.kind ='random',
	  fields.name.length ='10',
	  datagen.rows.per.second ='200'
   ) FORMAT PLAIN ENCODE JSON;
  ```
  
  **Create materialized view in RisingWave**
  
  Here we use RisingWave changelog, It can transform RisingWave streaming data into incremental logs, where `changelog_op` means `Insert/Update/Delete` and `_changelog_row_id` means order of modification. you can see xxx for more details
  
  ```sql
  CREATE MATERIALIZED VIEW ss_mv AS
  WITH sub AS changelog FROM user_behaviors
  SELECT
      user_id,
      target_id,
      event_timestamp AT TIME ZONE 'America/Indiana/Indianapolis' as event_timestamp,
      changelog_op AS __op,
      _changelog_row_id::bigint AS __row_id
  FROM
      sub;
  ```
  
  **Create sink in Risingwave**
  
  ```sql
  CREATE SINK snowflake_sink FROM ss_mv WITH (
	  connector ='snowflake',
	  type ='append-only',
	  snowflake.database ='EXAMPLE_DB',
	  snowflake.schema ='EXAMPLE_SCHEMA',
	  snowflake.pipe ='EXAMPLE_SNOWFLAKE_PIPE',
	  snowflake.account_identifier ='<ORG_NAME>-<ACCOUNT_NAME>',
	  snowflake.user ='EXAMPLE_USER',
	  snowflake.rsa_public_key_fp ='EXAMPLE_FP',
	  snowflake.private_key ='EXAMPLE_PK',
	  snowflake.s3_bucket ='EXAMPLE_S3_BUCKET',
	  snowflake.aws_access_key_id ='EXAMPLE_AWS_ID',
	  snowflake.aws_secret_access_key ='EXAMPLE_SECRET_KEY',
	  snowflake.aws_region ='EXAMPLE_REGION',
	  snowflake.max_batch_row_num ='1030',
	  snowflake.s3_path ='EXAMPLE_S3_PATH',
  );
  ```
  
  **Create dynamic table in Snowflake**
  
  ```sql
  create warehouse test_warehouse;
  ```
  
  **Create dynamic table in Snowflake**
```sql
    CREATE OR REPLACE DYNAMIC TABLE user_behaviors
    TARGET_LAG = '1 minute'
    WAREHOUSE = test_warehouse
    AS SELECT *
        FROM (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY {primary_key} ORDER BY __row_id DESC) AS dedupe_id
            FROM t3
        ) AS subquery
    WHERE dedupe_id = 1 AND (__op = 1 or __op = 3);
```
