### ISSUE TITLE
Document steps for configuring Google Cloud SQL CDC

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2362]
https://risingwave-community.slack.com/archives/C03BW71523T/p1720604180563529

https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/
https://docs.risingwave.com/docs/current/ingest-from-postgres-cdc/

**Comment by WanYixian** [comment]
Related to https://github.com/risingwavelabs/risingwave/issues/17729
