### ISSUE TITLE
Document how to tune reserved memory and cache eviction policy

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2363]
This is an advanced material and we don't expect most users to adjust it. 
We can tune it for RW Cloud users as we have access to the Grafana dashboards. 
But anyway, we can offer some guidelines for open-sourced users.

https://docs.risingwave.com/docs/current/performance-metrics/#memory-usage
One thing that needs to be fixed is that the portion of reserved memory is changed in the kernel. This needs to be aligned with: https://github.com/risingwavelabs/risingwave-docs/pull/2312. I suggest adding a link to it.

https://docs.risingwave.com/docs/dev/rw-faq/#why-is-the-memory-for-compute-nodes-not-fully-utilized
The paragraph told the users that they can adjust reserved memory by `RW_RESERVED_MEMORY_BYTES=8589934592 or --reserved-memory-bytes=8589934592`.

Another factor that affects how much memory users would use is the following configuration variables set in the configuration `toml` file:
```
    #[serde(default = "default::developer::memory_controller_threshold_aggressive")]
    pub memory_controller_threshold_aggressive: f64,

    #[serde(default = "default::developer::memory_controller_threshold_graceful")]
    pub memory_controller_threshold_graceful: f64,

    #[serde(default = "default::developer::memory_controller_threshold_stable")]
    pub memory_controller_threshold_stable: f64,

    #[serde(default = "default::developer::memory_controller_eviction_factor_aggressive")]
    pub memory_controller_eviction_factor_aggressive: f64,

    #[serde(default = "default::developer::memory_controller_eviction_factor_graceful")]
    pub memory_controller_eviction_factor_graceful: f64,

    #[serde(default = "default::developer::memory_controller_eviction_factor_stable")]
    pub memory_controller_eviction_factor_stable: f64,
```

In essence, `memory_controller_eviction_factor_XXX` decides:
1. if the memory usage exceeds `memory_controller_threshold_stable` of the total memory, the memory management mechanism in RW will start to evict data in the operator cache. But the intensity of eviction is mild at the moment.  
2. If the memory usage exceeds `memory_controller_threshold_graceful` of the total memory, the intensity of eviction becomes more aggressive.
3. If the memory usage eventually exceeds `memory_controller_threshold_aggressive`, the intensity of eviction becomes most aggressive.

In terms of the details about how the policy adjusts the intensity, we recommend users to take a look at the code directly: https://github.com/risingwavelabs/risingwave/blob/main/src/compute/src/memory/controller.rs
Increasing the `eviction_factor` will increase the intensity of eviction.

Suppose the reserved memory is 30%, and the `memory_controller_threshold_stable` is 0.8. We expect RW can use 1.0*(1-30%)*0.8 = 0.56 = 56% stably during most of the time. Typically, only when there is a sudden throughput spike or when creating a new materialized view that backfills a large amount of historical data, the memory usage will go beyond 56% and trigger more aggressive memory eviction. 

The best configuration highly depends on the workload and the data pattern. We recommend users tune the parameters based on the metrics on Grafana.

**Comment by ShanlanLi** [comment]
> https://docs.risingwave.com/docs/current/performance-metrics/#memory-usage
One thing that needs to be fixed is that the portion of reserved memory is changed in the kernel. This needs to be aligned with: https://github.com/risingwavelabs/risingwave-docs/pull/2312. I suggest adding a link to it.

@lmatz For this page, actually the portion you see now aligns with the new gradient calculation method of reserved memory. I [update it when doc our new method](https://github.com/risingwavelabs/risingwave-docs/pull/2273/files#diff-e4abad7d57a42f0521ef6744d75c998f30ab00b6139be475804857dd4e6f443e). 

As for this doc issue, I think creating a single page for reserved memory and the information you provided is a good idea. 
Do you have any suggestion on where to add this page in our documentation(like under the Deploy&operate section?)

<img width="228" alt="image" src="https://github.com/user-attachments/assets/7681a293-18f0-467f-b5af-dab169a01cb8">

**Comment by lmatz** [comment]
I see

> under the Deploy&operate section?)

I agree, let's put it under this section
