### ISSUE TITLE
Document: feat(storage): support hummock time travel

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2365]
This issue tracks the documentation update needed for the merged PR #17621.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17621
Source PR Merged At: 2024-07-11T14:07:49Z

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2375
