### ISSUE TITLE
Document: feat(batch): support batch s3 parquet frontend part

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2369]
This issue tracks the documentation update needed for the merged PR #17625.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17625
Source PR Merged At: 2024-07-12T08:21:39Z

**Comment by neverchanje** [comment]
Iceberg source and file_scan are both different from other types of ingestion methods. They are batch ingestion, meaning that there's no continuous jobs running in the background. I suggest adding a sub-folder "Batch load" in the "Ingest Data" folder, differentiating them from streaming sources. We will continue to support more batch sources in future.

Related doc issues:
- https://github.com/risingwavelabs/risingwave-docs/issues/2408

NOTE: `file_scan` is an experimental feature. The syntax is subject to change.

**Comment by WanYixian** [comment]
Resolved by #2610
