### ISSUE TITLE
Document: feat(connector): introduce parquet file source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2371]
This issue tracks the documentation update needed for the merged PR #17201.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17201
Source PR Merged At: 2024-07-12T10:55:24Z

**Comment by ShanlanLi** [comment]
resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2470#event-14010156319 and https://github.com/risingwavelabs/risingwave-docs/pull/2546
