### ISSUE TITLE
Document: feat(batch): support as of now() - interval for time travel

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2376]
This issue tracks the documentation update needed for the merged PR #17665.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17665
Source PR Merged At: 2024-07-12T09:10:55Z

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2375
