### ISSUE TITLE
Document: feat(secret): introduce secret management

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2380]
This issue tracks the documentation update needed for the merged PR #17456.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17456
Source PR Merged At: 2024-07-15T16:48:41Z

**Comment by neverchanje** [comment]
# Secret Management

** NOTE: Secret management is a premium edition feature. **

By default, credentials used to connect external services like MySQL are specified in the WITH clause of CREATE SOURCE / SINK statements in plain text. However, this poses a security risk in leaking secrets, especially for big organizations where the connected services are managed by multiple teams.

To address the issue, we recommend using the CREATE SECRET command to store credentials securely. Admins can create secrets in advance, allowing other team members to reference them using secret identifiers when creating source/sink connections. This ensures that secrets remain protected throughout all phases of access.

Example:

```sql
CREATE SECRET mysql_pwd WITH ( backend = 'meta' ) AS '123';
```

```sql
create source mysql_source with (
 connector = 'mysql-cdc',
 hostname = 'localhost',
 port = '8306',
 username = 'rwcdc',
 password = secret mysql_pwd,
 database.name = 'test',
 server.id = '5601'
);
```

```sql
SHOW CREATE SOURCE mysql_source;

---
--- public.mysql_mydb | CREATE SOURCE mysql_mydb WITH (connector = 'mysql-cdc', hostname = 'mysql', port = '3306', username = 'root', password = secret mysql_pwd, database.name = 'mydb', server.id = '2') FORMAT PLAIN ENCODE JSON
```

The mysql password is hidden, ensuring no secret leaks.

**Comment by yuhao-su** [comment]
### Use secret as file

Some connectors require the credentials options to a file path (e.g. `ssl.ca.location`) where the file content is the secret stored.. RisingWave support reference a secret as a file path. 

```
CREATE TABLE district (
    d_id INTEGER,
    PRIMARY KEY (d_id, d_w_id)
) with (
    connector = 'kafka',
    topic = 'your-topic',
    properties.bootstrap.server = 'your-broker-address:29092',
    ssl.ca.location = SECRET kafka_ca AS FILE,
    ssl.certificate.location = SECRET kafka_cert AS FILE,
    ssl.key.location = SECRET kafka_key AS FILE,
    ssl.key.password = SECRET kafka_password,
) FORMAT DEBEZIUM ENCODE JSON;
```

### Notes for open-source deployment

To use secret management, you need to set the environment variable `RW_SECRET_STORE_PRIVATE_KEY_HEX` to a hex representation of a 128-bit key. (e.g. 0123456789abcdef). This key is used to encrypt secrets in RisingWave. You MUST NOT lose this key, as it is required to decrypt secrets.

Set the temporary secret file directory `RW_TEMP_SECRET_FILE_DIR`. It will only be used when using `as file`.
