### ISSUE TITLE
Document: fix(source): cleanup unused key schema logic & requirements for `format upsert encode avro`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2399]
This issue tracks the documentation update needed for the merged PR #17759.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17759
Source PR Merged At: 2024-07-22T09:35:52Z

**Comment by xiangjinwu** [comment]
I will find out the relevant parts and draft the update accordingly.

**Comment by hengm3467** [comment]
@xiangjinwu Any update here? Thanks.

**Comment by xiangjinwu** [comment]
I will work on this tomorrow
