### ISSUE TITLE
Document: feat(expr): support using scalar functions as aggregates in batch query

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2402]
This issue tracks the documentation update needed for the merged PR #17622.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17622
Source PR Merged At: 2024-07-23T13:10:14Z

**Comment by stdrc** [comment]
Since this feature requires some background knowledge of the kernel, I'll write a draft for this later.
