### ISSUE TITLE
Document: feat(secret): add rw_catalog.rw_secrets table

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2420]
This issue tracks the documentation update needed for the merged PR #17726.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17726
Source PR Merged At: 2024-07-30T06:26:18Z

**Comment by ShanlanLi** [comment]
resolved in https://github.com/risingwavelabs/risingwave-docs/pull/2431#event-13774290097
