### ISSUE TITLE
Document: feat(stream): add two-phase stateless simple approx percentile

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2439]
This issue tracks the documentation update needed for the merged PR #17873.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17873
Source PR Merged At: 2024-08-08T05:25:42Z

**Comment by kwannoel** [comment]
Updated release note https://github.com/risingwavelabs/risingwave/pull/17873
