### ISSUE TITLE
Document: feat(cdc): auto schema change for mysql cdc

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2489]
This issue tracks the documentation update needed for the merged PR #17876.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/17876
Source PR Merged At: 2024-08-20T09:21:49Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by lmatz** [comment]
a preview and premium feature
