### ISSUE TITLE
Document: feat: use opendal as the s3 sdk by default

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2503]
This issue tracks the documentation update needed for the merged PR #18011.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18011
Source PR Merged At: 2024-08-22T15:22:35Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Closed as this is not a user-facing change, mentioning it in Release note is okay
