### ISSUE TITLE
sidebar disappears in some pages

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave-docs-legacy#2558]
For certain reasons, some pages are not referenced by the sidebar. When users click into these pages, the sidebar disappears. At this point, users might feel lost and unsure of their location within the documentation. 

e.g. https://docs.risingwave.com/docs/next/java-client-libraries/ It is because https://github.com/risingwavelabs/risingwave-docs/pull/2170#issuecomment-2109271799

Should we ensure that every page is located at a specific position in the sidebar?
Or can we keep the sidebar in its previous state but not link to any specific page?

**Comment by WanYixian** [comment]
Fixed in new doc site https://docs.risingwave.com/client-libraries/overview
