### ISSUE TITLE
Change required: make mysql cdc schema auto mapping a premium feature

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2559]
I remembered @neverchanje would make this feature to be paid only. Do we need to add some caveat in the doc?

_Originally posted by @StrikeW in https://github.com/risingwavelabs/risingwave-docs/issues/2339#issuecomment-2207866535_
            

This is indeed a premium feature that is already gated in the kernel code base.
Right now, it is not labeled in the documentation

**Comment by WanYixian** [comment]
Hi @lmatz, auto maps upstream table schema is enabled for not only MySQL, also PG tables. We need to label **both MySQL and PG** as premium and public preview right?

**Comment by lmatz** [comment]
Correct
