### ISSUE TITLE
Document: feat(cdc): support constant default value for alter table ADD COLUMN

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2567]
This issue tracks the documentation update needed for the merged PR #18322.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18322
Source PR Merged At: 2024-09-03T05:13:10Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by ShanlanLi** [comment]
will be resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2544/files
