### ISSUE TITLE
Document: feat(source): configure whether to recursively scan file source

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2593]
This issue tracks the documentation update needed for the merged PR #18324.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18324
Source PR Merged At: 2024-09-10T10:55:53Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Close as not needed
