### ISSUE TITLE
Bug: abstract in "SQL functions and operators" is not helpful

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#2594]
### Where's the bug?

https://docs.risingwave.com/docs/next/sql-functions/

### Describe the bug

better to delete or update it

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/e12bf8a1-d29e-49c4-b982-d1767ecbac3f">

**Comment by WanYixian** [comment]
Hi @xxchan, 
Each of card has a one-line description here
![image](https://github.com/user-attachments/assets/c897855f-74c7-4cab-96bc-b4a440920449)
And pages with multiple cards like this act as the overview pages, e.g.
https://docs.risingwave.com/docs/next/sql-commands/
https://docs.risingwave.com/docs/next/query-syntax/
https://docs.risingwave.com/docs/next/sql-functions/
Also, these pages are updated automatically based on the items in the sidebar. So I'd rather keep these pages hmm..WDYT?

**Comment by xxchan** [comment]
Yes, I mean these one-line descriptions are not helpful... They are the same as the title

**Comment by xxchan** [comment]
Oh, I don't mean the index page is not helpful. But just the descriptions..

**Comment by WanYixian** [comment]
> Oh, I don't mean the index page is not helpful. But just the descriptions..

Okay, I'll update the descriptions to display more info, thanks!
