### ISSUE TITLE
Document: chore: make file sink publicly accessible

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2602]
This issue tracks the documentation update needed for the merged PR #18508.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18508
Source PR Merged At: 2024-09-12T08:51:17Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Closed as resolved by https://github.com/risingwavelabs/risingwave-docs/issues/2473
