### ISSUE TITLE
Need a section about "shared source" and update the "Source" entry in glossary

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#2624]
### Related code PR

https://github.com/risingwavelabs/risingwave-docs/pull/2449#discussion_r1766105949

### Which part(s) of the docs might be affected or should be updated? And how?

I see the concept of sources have evolved in RW, and now we need to talk about shared sources frequently. I feel we need to explain the definition and purpose of shared sources, so that we can point to it from elsewhere.

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/69
