### ISSUE TITLE
Document: fix(pg-cdc): fix support for partitioned table

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2629]
This issue tracks the documentation update needed for the merged PR #18456.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18456
Source PR Merged At: 2024-09-22T00:19:37Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by KeXiangWang** [comment]
Done in https://github.com/risingwavelabs/risingwave-docs/pull/2628
