### ISSUE TITLE
Document the criteria of deciding what kind of features fall under premium

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2644]
As discussed on the Slack, this is the draft. cc: @mrayees @neverchanje 

The premium features generally include:
1. Integrations with proprietary data systems or open source systems with extensions which require users to have a license
2. advanced features that are not essential but boost development velocity and improve usability
3. advanced performance enhancement
4. customized features requested by paying customers, e.g. business-aware solutions.

In principle, we ensure that the open-source RW offers a richer feature set compared to other mainstream open-source stream processing systems on the market

Risingwave did not have the premium tier until 2.0.0.
Starting from 2.0.0, Risingwave will not retroactively change an open-source feature to a premium feature.

**Comment by CAJan93** [comment]
> customized features requested by paying customers 

If a customer wants a specific feature I assume this feature will be available for all premium users, right? We don't build a custom image for that customer, right?

**Comment by lmatz** [comment]
> We don't build a custom image for that customer, right?

There seems no such need in the short term. Any feature we delivered in the past and any feature request we have received so far is supposed to benefit all the rest of the users instead of only the customer who requested it. And implementing it does not lead to restructuring our code base in a special and complex way.

I hope we don't have to do this in the future. But anecdotally, some data infra businesses are doing so for on-prem customers.
