### ISSUE TITLE
Document: fix(nats): align offset and property fields between NATS and others for better ux and dx

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2645]
This issue tracks the documentation update needed for the merged PR #18732.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18732
Source PR Merged At: 2024-09-27T04:36:21Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2643
