### ISSUE TITLE
Document: fix(nats): align the semantics of `scan.startup.mode=latest` of NATS with others

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2646]
This issue tracks the documentation update needed for the merged PR #18733.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18733
Source PR Merged At: 2024-09-27T07:33:43Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2647
