### ISSUE TITLE
Document: feat(streaming): plan asof join

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2661]
This issue tracks the documentation update needed for the merged PR #18683.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18683
Source PR Merged At: 2024-09-30T10:35:36Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by fuyufjh** [comment]
Please mark it as experimental since it's not 100% completed yet.
