### ISSUE TITLE
Change required: deprecate the Datastax Astra Streaming support

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2662]
### Related code PR

Seems Datastax has deprioritized their Pulsar solution. Let's remove it from our doc. cc @mrayees 

### Which part(s) of the docs might be affected or should be updated? And how?

- https://docs.risingwave.com/docs/current/connector-astra-streaming/
- https://docs.risingwave.com/docs/current/rw-integration-summary/#message-brokers-or-streaming-services

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs-legacy/pull/2688
