### ISSUE TITLE
Document: feat: improve observability for subscription/cursor SHOW commands

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2680]
This issue tracks the documentation update needed for the merged PR #18896.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18896
Source PR Merged At: 2024-10-14T13:38:53Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Resolved in https://github.com/risingwavelabs/risingwave-docs/pull/2529
