### ISSUE TITLE
Document: refactor: impl ack and migrate to durable consumer for Nats

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2689]
This issue tracks the documentation update needed for the merged PR #18873.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18873
Source PR Merged At: 2024-10-16T03:45:50Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Hi @tabVersion, wonder if this required param is `consumer.durable_name` or `durable_consumer_name` ? 🤔

**Comment by tabVersion** [comment]
> Hi @tabVersion, wonder if this required param is `consumer.durable_name` or `durable_consumer_name` ? 🤔

Let's unify them to `consumer.durable_name`. the fix is in https://github.com/risingwavelabs/risingwave/pull/19090
