### ISSUE TITLE
Document: chore: update package version to 2.2.0-alpha

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2692]
This issue tracks the documentation update needed for the merged PR #18934.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18934
Source PR Merged At: 2024-10-16T10:52:12Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Check done, no doc requires changes
