### ISSUE TITLE
Document: feat(postgres-cdc): support replicating Postgres schema change

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2696]
This issue tracks the documentation update needed for the merged PR #18760.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18760
Source PR Merged At: 2024-10-17T07:10:28Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by lmatz** [comment]
better have the same section as the one in MySQL
https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/#automatically-change-schema
