### ISSUE TITLE
Document: feat: enable shared source in session variable by default, and add cluster-level config to disable

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2733]
This issue tracks the documentation update needed for the merged PR #18749.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18749
Source PR Merged At: 2024-10-21T02:34:30Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Closed as duplicated with https://github.com/risingwavelabs/risingwave-docs/issues/54
