### ISSUE TITLE
Document: Tracking(frontend): explain statement

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2734]
## Context
Source Issue URL: https://github.com/risingwavelabs/risingwave/issues/4856
Created At: 2022-08-24T09:01:19Z
Created By: st1page
Closed At: 2024-10-29T01:53:09Z

**Comment by WanYixian** [comment]
Fixed in https://github.com/risingwavelabs/risingwave-docs/pull/137
