### ISSUE TITLE
Document: refactor: remove private link related connection

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2740]
This issue tracks the documentation update needed for the merged PR #18975.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/18975
Source PR Merged At: 2024-10-30T12:23:43Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by tabVersion** [comment]
pelase remove CONNECTION related stuff in doc, especially when working with private link. https://docs.risingwave.com/docs/current/create-sink-kafka/#create-sink-with-privatelink-connection
