### ISSUE TITLE
Bug: missing FROM <schema> in SHOW SINKS

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave-docs-legacy#2744]
### Where's the bug?

https://docs.risingwave.com/docs/current/sql-show-sinks/

### Describe the bug

https://risingwave-community.slack.com/archives/C06F10ZHT6E/p1730446689292499?thread_ts=1730440154.161129&cid=C06F10ZHT6E

Missing the optional `FROM <schema>` in the docs of SHOW SINKS

**Comment by hzxa21** [comment]
See https://docs.risingwave.com/docs/current/sql-show-tables/

**Comment by WanYixian** [comment]
Resolved by https://github.com/risingwavelabs/risingwave-docs/pull/2745
