### ISSUE TITLE
Document: feat: support swap rename syntax for table/mview/view/source/sink and subscription

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2748]
This issue tracks the documentation update needed for the merged PR #19172.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/19172
Source PR Merged At: 2024-11-04T07:43:02Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Duplicated with https://github.com/risingwavelabs/risingwave-docs/issues/83
