### ISSUE TITLE
Document: feat: support `key encode bytes` for sink 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2751]
This issue tracks the documentation update needed for the merged PR #19243.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/19243
Source PR Merged At: 2024-11-08T08:08:36Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by WanYixian** [comment]
Closed as [Doc](https://docs.risingwave.com/integrations/destinations/apache-kafka#:~:text=When%20specified%2C%20the%20key%20encode%20can%20only%20be%20TEXT%20or%20BYTES.) already updated.
