### ISSUE TITLE
Document: fix(agg): fix `first_value` and `last_value` to not ignore NULLs

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#2757]
This issue tracks the documentation update needed for the merged PR #19332.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/19332
Source PR Merged At: 2024-11-13T04:38:51Z

If it is a major improvement that deserves a new page or a new section in the documentation, please check if we should label it as an experiment feature.

**Comment by stdrc** [comment]
Actually we need to document for each aggregate function whether it ignores NULLs or not, like in PG docs. I'll do this later.
