### ISSUE TITLE
Web: FAQ section in docs

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#286]
[This is not an urgent task. As long as it's tracked, we're good. Please continue to add new ideas and requirements here.]
What we need: An FAQ database in the user docs that is easy to manage and use.
What we expect: 
- FAQ items are easy to add, edit, tag, sort, search, and reference.
- An dedicated FAQ section to show all answered questions.
- Each question can be referenced and previewed on any doc page (like this: https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations, and this: https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-tooltips). 
- Users can propose new questions.

We need to implement the FAQ section with the glossary component https://github.com/risingwavelabs/risingwave-docs/pull/70 in mind, as it delivers most of the functionality we want. We can even make the FAQ and glossary two categories of the same database.

**Comment by hengm3467** [comment]
@CharlieSYH we can include a lot of the questions recorded for the AMA sessions earlier: https://www.notion.so/risingwave-labs/41f1bd0e3fd641eabd9f1d67c196683a?v=30d9a790c21c4570840b13d5d75dd05f

**Comment by hengm3467** [comment]
closing it since the FAQ section will be on the official webiste.
