### ISSUE TITLE
Redirect to Github issues 

### ISSUE THREAD

**Issue by cloudcarver** [risingwavelabs/risingwave-docs-legacy#3]
Add a button component for the layout of the documentation. The button will redirect to a github issue with github template

**Comment by CharlieSYH** [comment]
Also, the issue template should contain the file name/link/dir for locating the file.
Here's an [example](https://docs.pingcap.com/tidb/stable). When clicking the "Request docs changes" button, it redirects to the Issues page with the file name and link.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/100549427/162667487-c05b2ba1-eee4-40eb-8a78-423813fa517a.png">
