### ISSUE TITLE
Website: keep the leftmost column `from` in the page of `sql-data-types` when swiping to the right

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#305]
![SCR-20221017-q28](https://user-images.githubusercontent.com/5791930/196158506-338d562e-ab67-484e-9eaf-cc4746cf426f.png)
Not sure if it is easy to do it.

**Comment by CharlieSYH** [comment]
It would be really handy if the first column can be frozen when the user scrolls the table horizontally. And we thought about doing that when we redesigned the table, but it conflicts with other features like freezing the first row (header) when you scroll down a long table.
@Ad-Bean We can explore how to freeze the first row and column at the same time (for specified tables, not all). But do expect a long time before you see it in action, @lmatz .

**Comment by CharlieSYH** [comment]
@Ad-Bean and I decided to put this request on hold after analyzing the ROI since right now we only have one table that benefits from this feature. We will look into it again in the future.

**Comment by hengm3467** [comment]
@Ad-Bean @CharlieSYH  Thanks for spending time on it. I agree that we can put it on hold. 
In the meantime, we can think about whether it's feasible to present the information in a different way (maybe moving away from using tables?)

**Comment by CharlieSYH** [comment]
A draw.io or Figma diagram in SVG format might be a good choice.
Other options like a toggle list might make the doc page pretty ... long.

**Comment by hengm3467** [comment]
@CharlieSYH can we try either of the options?
