### ISSUE TITLE
Bug: Heading text is not visible in Night mode

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#308]
### Where's the bug?

https://www.risingwave.dev/docs/latest/install-run-connect/

### Describe the bug

When we switched on the night mode, the text on tab is not visible as mentioned in the below diagram:
<img width="1067" alt="Screenshot 2022-10-19 at 11 56 40 AM" src="https://user-images.githubusercontent.com/14886385/196594372-0780865e-aa94-48e5-8171-6e5fcaa89410.png">

**Comment by CharlieSYH** [comment]
@Ad-Bean Please use the same color as the code blocks for the tab button in dark mode.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/100549427/198182796-d5284ca2-1f9c-4b8d-9445-5a3e738567b6.png">
