### ISSUE TITLE
Bug:  replace DEBEZIUM JSON with DEBEZIUM_JSON

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave-docs-legacy#309]
### Where's the bug?

https://www.risingwave.dev/docs/latest/create-source-cdc/

### Describe the bug

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/9352536/196601517-13b66829-bf03-4b3c-a081-b0a875bc6d57.png">

I think we should replace `DEBEZIUM JSON` in the example with `DEBEZIUM_JSON`.

**Comment by hengm3467** [comment]
@chenzl25  This was just fixed in PR #301 .
Please take a look and let me know if any questions.

https://www.risingwave.dev/docs/latest/create-source-cdc/
