### ISSUE TITLE
Bug: twitter link should not redirect to Singularity Data page

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#310]
### Where's the bug?

https://www.risingwave.dev/docs/latest/get-started/

### Describe the bug

While clicking on the twitter symbol it should not redirect to the older [Singularity Data](https://twitter.com/SingularityData) page. It should take user to [Risingwave Labs](https://twitter.com/RisingWaveLabs) twitter account.

<img width="1790" alt="Screenshot 2022-10-19 at 1 18 18 PM" src="https://user-images.githubusercontent.com/14886385/196603967-0f1169f5-6c1b-4425-84ab-7218736e33e0.png">

**Comment by hengm3467** [comment]
@Ad-Bean Please help fix this one. Thanks!
