### ISSUE TITLE
Bug: wrong image put on the centre of the page

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#311]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-data-types/#casts

### Describe the bug

I see the wrong image being shown at the centre of the page on Chrome browser.

<img width="1770" alt="Screenshot 2022-10-19 at 1 25 48 PM" src="https://user-images.githubusercontent.com/14886385/196604694-70936162-1306-4d9b-a684-cf98b8c90ce8.png">

**Comment by hengm3467** [comment]
@sumittal  This is actually an image prompt telling people that the table can be scrolled horizontally. :) But I get the point that it can be a little distracting and confusing. Let me talk with @CharlieSYH about how this can be improved.

**Comment by CharlieSYH** [comment]
@sumittal @hengm3467 We have two options:
- Remove the icon. Make the horizontal scrollbar show all the time to suggest that the table can be scrolled horizontally (but I'm afraid it can be ignored as the scrollbar is easy to miss).
- Improve the design of the icon:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/100549427/198189932-fc072e15-dc23-43f8-af3a-48301a14dfbd.png">

Current:
<img width="137" alt="image" src="https://user-images.githubusercontent.com/100549427/198183822-ede86cc6-9b5d-4a98-a286-73688f285711.png">
