### ISSUE TITLE
Bug: minor typo in the documentation

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#312]
### Where's the bug?

https://www.risingwave.dev/docs/latest/intro/

### Describe the bug

outputing -> outputting

<img width="1787" alt="Screenshot 2022-10-19 at 1 52 30 PM" src="https://user-images.githubusercontent.com/14886385/196608088-0c652434-0f16-4426-8070-bbb7d147df66.png">

**Comment by hengm3467** [comment]
Thanks @sumittal . This is now fixed. https://www.risingwave.dev/docs/latest/intro/
