### ISSUE TITLE
Bug: update the risingwave version in installation steps

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#313]
### Where's the bug?

https://www.risingwave-labs.com/product/

### Describe the bug

We should keep updated the risingwave version in installation command whenever we bump up the stable version.

<img width="1527" alt="Screenshot 2022-10-19 at 2 11 05 PM 1" src="https://user-images.githubusercontent.com/14886385/196610975-09e64561-8592-496c-a540-d3402f962383.png">

**Comment by hengm3467** [comment]
@sumittal This is actually on the website, which is maintained separately. Let me see how this can be automated or easily updated.

**Comment by CharlieSYH** [comment]
Instead of updating the command on the website regularly (or automatically), we should have a command that always checks and installs the latest version of RW on our official website. Is that feasible? @sumittal @hengm3467

**Comment by CharlieSYH** [comment]
We updated the command (both on the official website and the user docs) which now always installs the latest image (from official releases) in https://github.com/risingwavelabs/risingwave-docs/pull/343.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/100549427/199874376-afd0285e-ef2b-4d3a-88ad-b6665cf36320.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/100549427/199960032-7ab36a1a-cac8-46c0-9ec5-0843d711483c.png">
