### ISSUE TITLE
Bug: IS NULL

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave-docs-legacy#315]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-function-comparison/

### Describe the bug

> *** IS NULL causes a crash. Should we show this to users?

How did the crash happen? Do we have an issue with reproduce steps for this?

**Comment by CharlieSYH** [comment]
I'm terribly sorry for this mistake. This software bug was resolved a long time ago, but the doc hasn't removed the info (which is not meant to show to the users). I've created a PR to solve it.
