### ISSUE TITLE
Bug: Missing doc for arithmetics on date/timestamp/time/interval

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave-docs-legacy#316]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-function-datetime/

### Describe the bug

Everything listed in the following issue has been implemented except for `timestamp with time zone`
https://github.com/risingwavelabs/risingwave/issues/924

For reference this is the PostgreSQL document:
https://www.postgresql.org/docs/current/functions-datetime.html#OPERATORS-DATETIME-TABLE

**Comment by xiangjinwu** [comment]
To list the undocumented (and wrongly documented) operators. Maybe we can also organize them in these 3 subsections.

Note that `+` and `*` are commutative.

Timespan operators:
* [x] interval * double precision -> interval
  * current: real * interval -> time
* [x] interval / double precision -> interval
  * current: interval / int -> time | interval / float -> time | interval / decimal -> time
* [ ] interval + interval -> interval
  * example: `interval '20' hour + interval '10' hour` -> `30:00:00` 
* [ ] interval - interval -> interval
  * example: `interval '20' hour - interval '10' hour` -> `10:00:00` 
* [x] time + interval -> time
* [x] time - interval -> time
* [x] time - time -> interval
  * current: time - time -> time 

Offsetting:
* [ ] timestamp + interval -> timestamp
  * example: `'2022-03-13 01:00:00'::timestamp + interval '24' hour` -> `2022-03-14 01:00:00`
* [ ] timestamp - interval -> timestamp
  * example: `'2022-03-14 01:00:00'::timestamp - interval '24' hour` -> `2022-03-13 01:00:00`
* [ ] timestamp - timestamp -> interval
  * example: `'2022-03-13 03:00:00'::timestamp - '2022-03-13 01:00:00'` -> `02:00:00`
* [x] date + int -> date
* [x] date - int -> date
* [ ] date - date -> int
  * example: `date '2020-03-01' - '2020-02-01'` -> `29` 
* [x] date + interval -> timestamp
* [x] date - interval -> timestamp
* [x] date + time -> timestamp

Timestamp with time zone:
* [ ] timestamptz + interval_fixed -> timestamptz
  * example: `'2022-03-13 01:00:00Z'::timestamp with time zone + interval '24' hour` -> `2022-03-14 01:00:00+00:00`
* [ ] timestamptz - interval_fixed -> timestamptz
  * example: `'2022-03-14 01:00:00Z'::timestamp with time zone - interval '24' hour` -> `2022-03-13 01:00:00+00:00`

`interval_fixed` means the interval can only contain hour/minute/second (i.e. fixed length) but not year/month/day (i.e. variable length).

**Comment by bernscode** [comment]
@xiangjinwu Thanks for the subsections recommendation. I've implemented this in the latest commit.
