### ISSUE TITLE
Document case-sensitivity about names

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#319]
### Related code PR

https://github.com/risingwavelabs/risingwave/issues/6051

### Which part(s) of the docs might be affected or should be updated? And how?

add a new page

### Reference

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS:~:text=by%20changing%20the,are%20case%20insensitive

https://materialize.com/docs/sql/identifiers/

**Comment by hengm3467** [comment]
Please also remember to add a note about case-insensitivity of names in create source/table/mv/view etc.
