### ISSUE TITLE
Change required: remove single quotes around keys in `WITH` clause 

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#325]
### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/latest/sql-create-table/:
```
CREATE TABLE taxi_trips(
    id VARCHAR,
    distance DOUBLE PRECISION,
    duration DOUBLE PRECISION
) WITH ('appendonly' = true);
```
to
```
CREATE TABLE taxi_trips(
    id VARCHAR,
    distance DOUBLE PRECISION,
    duration DOUBLE PRECISION
) WITH (appendonly = true);
```

Otherwise:
```
ERROR:  QueryError: sql parser error: Expected identifier, found: 'appendonly'
```

Maybe there are more such occurrences.

**Comment by CharlieSYH** [comment]
The `appendonly` option is only for internal tests. Users are not supposed to use it. We have deleted it in the docs. See: 
https://github.com/risingwavelabs/risingwave-docs/pull/344
