### ISSUE TITLE
Discusson: use a consistent example across all the `Commands` page

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#326]
For example,

on https://www.risingwave.dev/docs/latest/sql-create-table/:
```
CREATE TABLE taxi_trips(
    id VARCHAR,
    distance DOUBLE PRECISION,
    duration DOUBLE PRECISION
) WITH (appendonly = true);
```

on https://www.risingwave.dev/docs/latest/sql-insert/:
```
{
  "id": INT NOT NULL,
  "distance": DOUBLE PRECISION NOT NULL,
  "city": VARCHAR
}

INSERT INTO taxi_trips 
    VALUES 
      (1,16,'Dallas'), 
      (2,23,'New York'), 
      (3,6,'Chicago'), 
      (4,9,NULL);
```

The two examples are not compatible.

I saw two users who want to try RW and look for examples on the Doc page but spent a few seconds to realize that the two examples do not have the same schema.

Maybe there are more inconsistent occurrences.

**Comment by hengm3467** [comment]
@lmatz Thanks for bringing this up. We had an initiative in Q3 to have consistent examples but had to postpone it to this quarter. We'll do a global search and review, and make changes accordingly.

**Comment by lmatz** [comment]
> @lmatz Thanks for bringing this up. We had an initiative in Q3 to have consistent examples but had to postpone it to this quarter. We'll do a global search and review, and make changes accordingly. 

@hengm3467 Thanks, good to know!

**Comment by hengm3467** [comment]
Closing this one as the changes were already merged.
