### ISSUE TITLE
Document distributed mode and local mode

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#338]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/4789

### Which part(s) of the docs might be affected or should be updated? And how?

We need a section to describe what these modes are. 

Dev: @liurenjie1024 

### Reference

https://singularity-data.quip.com/he8QAxynNnzS/Design-Local-execution-mode-for-online-serving-queries

_No response_

**Comment by hengm3467** [comment]
@neverchanje @liurenjie1024 Do we still have these two modes?

**Comment by hengm3467** [comment]
Close this issue as the modes are now automatically switched/enabled.
