### ISSUE TITLE
Use a better way to present the data casting table

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#342]
### Related issue

https://github.com/risingwavelabs/risingwave-docs/issues/305

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/latest/sql-data-types/#casts

and also this https://www.risingwave.dev/docs/latest/sql-function-logical/

**Comment by hengm3467** [comment]
@CharlieSYH  I like the way casting is presented in this big query topic: https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_rules
