### ISSUE TITLE
 Document system catalog schema: `information_schema`

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#363]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/6227
https://github.com/risingwavelabs/risingwave/pull/6259

### Which part(s) of the docs might be affected or should be updated? And how?

This might need a new article/section called Information schema, or other names that are appropriate.
https://www.postgresql.org/docs/current/infoschema-schema.html

Please refer to this PG page as well: https://www.postgresql.org/docs/current/information-schema.html

Please note that we don't want to be that comprehensive. We want the info to be easier to use. Please look at several other DB's docs to get some inspirations. 

### Reference

Here is one article that we can reference:

https://duckdb.org/docs/sql/information_schema

**Comment by hengm3467** [comment]
@bernscode I can take this one if you haven't started already.

**Comment by bernscode** [comment]
@hengm3467 Okay, you can take it. Thanks, Heng!
