### ISSUE TITLE
Bug: install psql without postgres

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#393]
### Where's the bug?

https://www.risingwave.dev/docs/latest/real-time-ad-performance-analysis

### Describe the bug

Psql is an interactive terminal with can be installed independently without full Postgres installation. The link provided in the doc points to https://www.postgresql.org/download/, which describes the steps for installing postgres rather than psql. We may want simpler instructions. You may check https://www.timescale.com/blog/how-to-install-psql-on-mac-ubuntu-debian-windows/ as a reference.

**Comment by hengm3467** [comment]
@CharlieSYH Please create a separate topic about installing psql in different operating systems, and link to it from all relevant places.

**Comment by yingjunwu** [comment]
Any updates on this?
