### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#394]
### Where's the bug?

https://www.risingwave.dev/docs/latest/get-started/

### Describe the bug

As a Windows user, I have no idea how to start with. The `Run locally` page only describes the installation on Linux and macOS. Should I follow `Run in Docker` page and install Docker in Windows? But if Docker in Windows works, how I can `open a new terminal window and run`? Should I use WSL (Windows subsystem for Linux)? If I use WSL, then can I use Docker command? Seems that there's some issue with Docker on WSL, and I am not sure whether that's fixed by Docker officially.

**Comment by CharlieSYH** [comment]
Working on it.

**Comment by yingjunwu** [comment]
I just tried WSL and it works. Not sure whether Docker also works in Windows?
