### ISSUE TITLE
Ambiguity: what is `Materialized`?

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#395]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-create-source

### Describe the bug

In this page, you mentioned a keyword named `Materialized`. I did a search in this page but didn't really find any explanation. Could you please add some descriptions on what is `Materialized`, and why/how it matters? Thanks!

**Comment by hengm3467** [comment]
This is fixed in #472 . Please let me know if you have additional questions. @yingjunwu

**Comment by yingjunwu** [comment]
LGTM. Thanks!
