### ISSUE TITLE
Bug: missing syntax for `create source`

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#397]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-create-source

### Describe the bug

It seems that the page didn't list the syntax of `create source`.

**Comment by hengm3467** [comment]
@yingjunwu Thanks! The syntax is included in each of the supported sources to reduce complexity. For example: https://www.risingwave.dev/docs/latest/create-source-kafka-redpanda/
