### ISSUE TITLE
Bug: sink destination?

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#398]
### Where's the bug?

https://www.risingwave.dev/docs/latest/sql-create-sink

### Describe the bug

I wonder which systems can we deliver data to? I can see from https://www.risingwave.dev/docs/latest/sql-create-source/ we support consuming data from a bunch of upstream systems. Is there any listing of supported downstream systems? Is kafka required to sink data?

**Comment by hengm3467** [comment]
@yingjunwu Thanks for the input! Some background info: The team are redesigning the sink connectors. Currently the only supported sink is Kafka/Redpanda. Please see a summary of the sink support here: https://www.notion.so/risingwave-labs/Summary-of-the-sink-support-draft-2aa06d4f312c418b870b4f9371730393

**Comment by hengm3467** [comment]
Closing this issue as the supported sink destinations are described on this page: https://www.risingwave.dev/docs/upcoming/delivery-overview/
