### ISSUE TITLE
Docs on `ingest data` and `deliver data`

### ISSUE THREAD

**Issue by yingjunwu** [risingwavelabs/risingwave-docs-legacy#399]
### Where's the bug?

https://www.risingwave.dev/docs/latest/intro/

### Describe the bug

I noticed that the `Ingest data` and `Deliver data` pages point to `Create Source` and `Create Sink` pages respectively. I wonder whether this is made deliberately? I think maybe we can create independent pages for `Ingest data` and `Deliver data` and explicitly mention that `Ingest data` requires invoking `create source` command. In fact, `insert into` is another way to "ingest data". Directly redirecting `Ingest data` page to `create source` page sounds like `create source` is the only way to ingest data, which is misleading.

**Comment by hengm3467** [comment]
Revamping these two sections. The issues will be fixed when the revamp is done.
