### ISSUE TITLE
Bug:  content of documentation page(create-source-kinesis) is malformed

### ISSUE THREAD

**Issue by sumittal** [risingwavelabs/risingwave-docs-legacy#403]
### Where's the bug?

https://www.risingwave.dev/docs/latest/create-source-kinesis/

### Describe the bug

e.g. 
 I noticed that there is a inconsistency in [https://www.risingwave.dev/docs/latest/create-source-kinesis/](https://www.risingwave.dev/docs/latest/create-source-kinesis/). 
<img width="1792" alt="Screenshot 2022-11-28 at 10 46 55 PM" src="https://user-images.githubusercontent.com/14886385/204340437-11961d8e-de83-492b-9453-5f37ef3dca20.png">

Browsers: Chrome, Firefox

**Comment by hengm3467** [comment]
@sumittal  Thanks for reporting this issue! Strange issue indeed. Yesterday it was fine.

**Comment by hengm3467** [comment]
@Ad-Bean Please help with this formatting / presentation issue. Thanks.

**Comment by Ad-Bean** [comment]
> @Ad-Bean Please help with this formatting / presentation issue. Thanks.

It seems like the problem is that the token line is too long, we can manually break the token line to solve this issue
