### ISSUE TITLE
Document GRANT command

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#422]
### Which part(s) of the docs might be affected or should be updated? And how?

Need to document GRANT command, which was mentioned in step 4 of the [Use RW to monitor RW metrics tutorial ](https://www.risingwave.dev/docs/latest/use-risingwave-to-monitor-risingwave-metrics/#step-4-add-risingwave-as-a-data-source-in-grafana).

### Reference

This seems to be the initial code PR that added the GRANT command: https://github.com/risingwavelabs/risingwave/pull/3004. There might have been updates/fixes made afterward, but I haven't found any yet.

**Comment by hengm3467** [comment]
This issue is fixed in #435
