### ISSUE TITLE
Character spacing issue of headings

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#45]
The character spacing of all headings (H1, H2, H3, H4) are slightly larger than the body (which is Noto Sans Regular) and should be smaller. Large gap between letters affect the reading experience.
Note that the current paragraph spacing is perfect. No need to change.

Current:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/100549427/162665647-d44e3221-6b85-46a8-900e-62e4422c646d.png">

Expected:
<img width="999" alt="image (1)" src="https://user-images.githubusercontent.com/100549427/162665746-2b65e542-c847-4421-898d-30d950057277.png">

**Comment by Ad-Bean** [comment]
Close by #55
