### ISSUE TITLE
"Edit this page" button should redirect to the source code of file

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#46]
Currently, this button redirects to the pull requests tab of the doc repo.
<img width="166" alt="image" src="https://user-images.githubusercontent.com/100549427/162666155-40cc6c04-330d-4daa-85a0-a8f12c647f86.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/100549427/162666905-815adab1-8ba6-4692-a868-c971ae978810.png">

But imagine when users click this button and only to find that they have to find that particular file in the repo. Sounds a little bit bothering, right? Ideally, when I click the Edit this page button on, let's say, Getting started, it should redirect to [this page](https://github.com/singularity-data/risingwave-docs/blob/main/docs/Getting-Started.md).

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/100549427/162666516-32816b0b-4db8-4db6-a9f0-256d801a52a9.png">

**Comment by Sunt-ing** [comment]
+1
