### ISSUE TITLE
Bug: sql-create-sink "append-only" should be "append_only"

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#503]
### Where's the bug?

https://www.risingwave.dev/docs/current/sql-create-sink/

### Describe the bug

 I noticed that there is a typo in `Allowed formats: ‘append-only’`
 This is incorrect because it should be `append_only`. 
 I think you folks should replace `append-only` with `append_only`. 
 If you take a look at https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/sink/kafka.rs#L71 you will agree with me. 
 Cheers.

**Comment by emile-00** [comment]
Typos will be fixed in https://github.com/risingwavelabs/risingwave-docs/pull/477
