### ISSUE TITLE
Change required: show platform-specific installation page based on the detected platform

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#526]
### Related code PR

We can inject an OS-detection script into our doc page. If it's macOS, then show the macOS manual.

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/risingwave-local/

**Comment by CharlieSYH** [comment]
@Ad-Bean and I will try to implement a mechanism to judge the OS and select the corresponding tab for users.
This is how it'll work: Visit a page with OS-specific content (separated by tabs) -> Get OS info -> Append the URL with the query string for the user's OS.
The query string for tabs is an available Docu feature. For example, if you visit `https://www.risingwave.dev/docs/upcoming/get-started/?method=cloud` (notice that `?method=cloud` is added at the end), the "Run in Cloud" tab will be selected for you.
