### ISSUE TITLE
Document the handling of unsupported cast expressions

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#546]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/7378

### Which part(s) of the docs might be affected or should be updated? And how?

Unsupported cast expressions will be treated as literal expressions. We need to add a note in the topic about casting operators.

**Comment by xiangjinwu** [comment]
Please refer to https://github.com/risingwavelabs/risingwave-docs/pull/600#issuecomment-1443186376

BTW "unsupported cast" can mean two things:
* Unable to cast any values from A to B. For example, a boolean cannot be casted to a date.
* Unable to cast a specific value from A to B. For example, string `abc` cannot be casted to an integer, but string `123` can.

Nonetheless, the casting in that PR is mostly invisible to user and may not need a doc update.

**Comment by hengm3467** [comment]
Closing this issue as there is not need to document the changes in the above-mentioned code PR.
