### ISSUE TITLE
Duplicated "file an issue" button

### ISSUE THREAD

**Issue by Sunt-ing** [risingwavelabs/risingwave-docs-legacy#56]
File: [/main/Introduction.md](https://www.risingwave.dev/docs/latest/intro)

<img width="691" alt="image" src="https://user-images.githubusercontent.com/43040147/164269202-98961db2-0681-4187-b9f8-988c19ff8b7c.png">

**Comment by Ad-Bean** [comment]
I add request docs changes button by #3 , should i replace the `File an issue` button with `Request docs change` or just remove one of them?

**Comment by Sunt-ing** [comment]
I think "file an issue" and "edit this page" is a couple. Some if we choose to remove a button, I prefer to remove "request docs changes". However, the link behind "file an issue" is different from the link behind "request docs changes", and it seems that the link behind "request docs changes" is what we want. 
So, my personal advice is to remove the button "request docs changes" but change the link behind "file an issue" to the link behind "request docs changes". Is this reasonable to you?

**Comment by CharlieSYH** [comment]
Agree with @Sunt-ing.

**Comment by Sunt-ing** [comment]
Closed by https://github.com/singularity-data/risingwave-docs/issues/3. Well done! @Ad-Bean
