### ISSUE TITLE
Bug: broken table in document sql-create-sink

### ISSUE THREAD

**Issue by Ad-Bean** [risingwavelabs/risingwave-docs-legacy#562]
### Where's the bug?

https://www.risingwave.dev/docs/current/sql-create-sink/

### Describe the bug

I noticed that there is missing data or broken formatting in https://www.risingwave.dev/docs/current/sql-create-sink/#parameters.

![image](https://user-images.githubusercontent.com/54789193/218731579-026daa33-94bb-4f31-8df4-c8d091492bba.png)

**Comment by CharlieSYH** [comment]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/100549427/218770604-c4782804-8e97-424d-b5d9-332bfc2a61e6.png">
I think @hengm3467 has corrected it. But there's an extra period in the end. So I opened a new PR for this.
