### ISSUE TITLE
Local cluster building

### ISSUE THREAD

**Issue by JuchangGit** [risingwavelabs/risingwave-docs-legacy#603]
How to set up a local cluster？

**Comment by hengm3467** [comment]
@JuchangGit You can set up a local cluster using Docker Compose or K8s. Detailed instructions can be found at: https://www.risingwave.dev/docs/current/risingwave-docker-compose/
https://www.risingwave.dev/docs/current/risingwave-kubernetes/

Let us know if you run into any issues. You are welcome to join our Slack community space.

**Comment by JuchangGit** [comment]
thank you

**Comment by hengm3467** [comment]
@JuchangGit  Not a problem. Closing this issue now but feel free to let us know if you need help.
