### ISSUE TITLE
Table header should stay on top of the table

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#61]
When scrollling down the page, the user may find it difficult to read the table content because the table header is out of sight:
<img width="657" alt="image (2)" src="https://user-images.githubusercontent.com/100549427/165019980-c8adae33-2adb-435f-8f3c-fb4e696198d6.png">

The solution brought up by @Ad-Bean might be suitable for this case: https://codepen.io/tjvantoll/pen/nxbaMe

**Comment by cloudcarver** [comment]
cc. @Ad-Bean Any updates?

**Comment by CharlieSYH** [comment]
Seems like the tables now have a fixed height and don't show all the rows by default. Users need to scroll to view all content.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/100549427/172136984-74aead10-8c6e-4534-8db1-ecec11fd543b.png">


Expected:

- The table header stays on top of the screen when scrolling down (aka a "sticky header"), while the rest of the table rows move with the webpage.
- Show all table rows in one page.
