### ISSUE TITLE
Bug: "create materialized source" still exists in some pages.

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#618]
### Where's the bug?

https://www.risingwave.dev/docs/current/sql-create-view/

### Describe the bug

There are still mentioning of "CREATER MATERIALIZED SOURCE" on some pages. We need to do a global search and replace with "CREATE TABLE".

**Comment by CharlieSYH** [comment]
All instances of "CREATE MATERIALIZED SOURCE" in version 0.1.16 or later are changed to CREATE TABLE.

**Comment by hengm3467** [comment]
@CharlieSYH Looks like this one was missed: 
![image](https://user-images.githubusercontent.com/100685635/223056457-0d39f3c3-7881-4bda-b861-533cecfea2a8.png)

**Comment by CharlieSYH** [comment]
> @CharlieSYH Looks like this one was missed:
> ![image](https://user-images.githubusercontent.com/100685635/223056457-0d39f3c3-7881-4bda-b861-533cecfea2a8.png)

In which version? I didn't change it in version 0.1.15 or earlier.
