### ISSUE TITLE
Bug: lacking a example to load schema from s3

### ISSUE THREAD

**Issue by tabVersion** [risingwavelabs/risingwave-docs-legacy#628]
### Where's the bug?

https://www.risingwave.dev/docs/current/create-source-kafka

### Describe the bug

> RisingWave supports reading schemas from a Web location in `http://...`, `https://...`, or `S3://...` format, or a Confluent Schema Registry for Kafka data in Avro or Protobuf format.

when loading files from s3, we may face loading a file from a bucket requiring authorization. It is helpful if we provide an example for demonstration.

**Comment by hengm3467** [comment]
@tabVersion Do you think the example for Protobuf is enough?

![image](https://user-images.githubusercontent.com/100685635/231677580-38648602-42d9-4f23-a4a7-d787b558aa44.png)

**Comment by hengm3467** [comment]
If this is not engouh, could you or someone else provide an example? Thanks.
@tabVersion @idx0-dev

**Comment by tabVersion** [comment]
like the example in https://github.com/risingwavelabs/risingwave/pull/8428

```
CREATE SOURCE IF NOT EXISTS source_abc 
WITH (
   connector='kafka',
   topic='demo_topic',
   properties.bootstrap.server='172.10.1.1:9090,172.10.1.2:9090',
   scan.startup.mode='latest',
   scan.startup.timestamp_millis='140000000'

   access_key='replace me with your aws access key',
   secret_access='replace me with your aws secret access'
)
ROW FORMAT AVRO 
ROW SCHEMA LOCATION CONFLUENT SCHEMA REGISTRY 'http://127.0.0.1:8081';
```

all options for s3 auth are:

|field name|note|
|---|---|
|`region`| Optional. AWS service region, eg. `us-east-1`|
|`arn`| Optional. The Amazon Resource Name (ARN) of the role to assume|
|`profile`|Optional. Use profiles to configure multiple access keys in the same credential file.  |
|`access_key`|Conditional. This field indicates the access key ID of AWS. It must appear in pairs with `secret_access`.|
|`secret_access`| Conditional. This field indicates the secret access key of AWS. |
|`session_token`| Optional. The session token associated with the temporary security credentials |
|`endpoint_url`|Optional. URL of the entry point for the AWS S3 service.|

**Comment by hengm3467** [comment]
Closing this issue as we'll be disallowing loading schemas from S3.
