### ISSUE TITLE
Document Primary Key Concept

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#638]
### Which part(s) of the docs might be affected or should be updated? And how?

> we may need an official document to define the concept of **Primary Key** in our system.

_Originally posted by @StrikeW in https://github.com/risingwavelabs/risingwave/issues/8473#issuecomment-1463540667_

BTW, I noticed we have nice explaination docs about `INDEX` in our system. We might have a similar one for primary key.

**Comment by hengm3467** [comment]
@neverchanje Could you please recommend engineers who can help write this topic? Thanks.

**Comment by hengm3467** [comment]
@fuyufjh Could you please recommend engineers who are in the best position to write this topic? Thanks!

**Comment by neverchanje** [comment]
We currently do not support altering table and modifying column's indentifier. So there is no need for dedicated document. 

https://docs.risingwave.com/docs/dev/sql-create-table/
> For tables with primary key constraints, if you insert a new data record with an existing key, the new record will overwrite the existing record.

This should be enough.
