### ISSUE TITLE
Document the support of using Pulsar and Kinesis to transfer CDC data

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#652]
### Which part(s) of the docs might be affected or should be updated? And how?

We mention in the docs that users can use the Kafka connector to convert CDC data to Kafka topics. Actually, both Pulsar and Kinesis can also be used for the same purpose. 
For Pulsar, this connector from Pulsar is needed (on top of the Pulsar connector in RisingWave): https://pulsar.apache.org/docs/2.11.x/io-cdc/
For Kinesis, AWS DMS is needed: https://aws.amazon.com/blogs/big-data/stream-change-data-to-amazon-kinesis-data-streams-with-aws-dms/

The connector settings for transferring CDC data are the same as non-CDC data. The only difference is ROW FORMAT being various JSON formats (Debezium JSON, Maxwell, Canal JSON, etc). Additionally, as ROW FORMAT is various JSON formats, MESSAGE and SCHEMA LOCATION are not needed. 

@tabVersion Please confirm my above description is accurate. Thanks. 

To accommodate the changes, we need to change the title of "CDC via Kafka" to "CDC via message brokers", and fit in the descriptions. 

We'll also need to make changes accordingly in "Ingest data from MySQL" and "Ingest CDC data from PostgreSQL", to say that people can use these three message brokers as intermediate medium to transfer CDC data from databases to RisingWave.

**Comment by tabVersion** [comment]
> For Pulsar, this connector from Pulsar is needed (on top of the Pulsar connector in RisingWave): [pulsar.apache.org/docs/2.11.x/io-cdc](https://pulsar.apache.org/docs/2.11.x/io-cdc/)
For Kinesis, AWS DMS is needed: [aws.amazon.com/blogs/big-data/stream-change-data-to-amazon-kinesis-data-streams-with-aws-dms](https://aws.amazon.com/blogs/big-data/stream-change-data-to-amazon-kinesis-data-streams-with-aws-dms/)

we don't require pulsar plugin or aws dms for producing CDC data. We only cares about the contents in mqs meet the claimed row format. 
rest LGTM

**Comment by emile-00** [comment]
> > For Pulsar, this connector from Pulsar is needed (on top of the Pulsar connector in RisingWave): [pulsar.apache.org/docs/2.11.x/io-cdc](https://pulsar.apache.org/docs/2.11.x/io-cdc/)
> > For Kinesis, AWS DMS is needed: [aws.amazon.com/blogs/big-data/stream-change-data-to-amazon-kinesis-data-streams-with-aws-dms](https://aws.amazon.com/blogs/big-data/stream-change-data-to-amazon-kinesis-data-streams-with-aws-dms/)
> 
> we don't require pulsar plugin or aws dms for producing CDC data. We only cares about the contents in mqs meet the claimed row format. rest LGTM

@tabVersion However, aren't these additional parts needed in order for the message broker to consume the CDC data from MySQL/PG? They're just not directly connected to RisingWave.
