### ISSUE TITLE
Replace the date format with a more universal format.

### ISSUE THREAD

**Issue by Sunt-ing** [risingwavelabs/risingwave-docs-legacy#67]
The format for "last updated date" in this repo is not universal but an American format, which may bring some confusion to people who get used to the British date format. 
I propose to use a more general date format, "April 9, 2022" or "9 April 2022". Either of them will not incur confusion.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/43040147/168246029-975fd0eb-b5f7-44ae-9080-9e22b0034f23.png">

**Comment by phadkesharan** [comment]
I want to help with the issue. Can you please assign me this issue?

**Comment by Sunt-ing** [comment]
@phadkesharan Of course, thank you for your interest in this project.

**Comment by Sunt-ing** [comment]
@phadkesharan If you have any questions, please let me know! We are willing to answer your questions!
