### ISSUE TITLE
enhancement of conluent kafka doc

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#678]
### Where's the bug?

https://www.risingwave.dev/docs/upcoming/confluent-kafka-source/

### Describe the bug

1. The instruction below is just "Locally via Docker".. Nothing special for EC2
<img width="622" alt="image" src="https://user-images.githubusercontent.com/37948597/227046739-9a2f5807-6cc0-432e-b744-af79e0b42ebe.png">

2. Rust client is unnessary. API keys -> new key might be better.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/37948597/227047389-8535e0a4-829a-4c19-a836-632551561e3b.png">

**Comment by hengm3467** [comment]
@xxchan Thanks! For the second one, users can select any language. Right?

**Comment by xxchan** [comment]
Yes, because users are not using a kafka client; RW is the kafka client. And API keys are not related to which language is used.

**Comment by hengm3467** [comment]
@xxchan Following up the first one. I think we should add a bit information about creating an EC2 instance and we recommend choosing ubuntu OS. Correct? Anything else we need to provide? Thanks!

**Comment by xxchan** [comment]
I have no idea. Actually I'm not sure whether we need to provide any specific information about EC2, because it's generally the same as local deployment and besides we won't support on-premises deployment very much. OP users should have that kind of knowledge. 🤔 Please discuss that with others.

**Comment by hengm3467** [comment]
@emile-00 I started a bit, but thought it would be better if you could handle this. Basically, the needed changes include:
1. Remove the EC2 instructions in the "Run RisingWave" section, and just point people to the install and run section. 
2. "Create a new client on Confluent Cloud" is not necessary. Instead, we should go to **Cluster Overview** -> **API Keys**, and create a new key, which then can be used in the create a Kafka source in RisingWave. This new section can be named Create an API key or something similar. Reference: https://materialize.com/docs/integrations/confluent-cloud/
