### ISSUE TITLE
Document the stddev/var function

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#692]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/7952

### Which part(s) of the docs might be affected or should be updated? And how?

SQL -> Functions -> Aggregate

### Reference

https://www.postgresql.org/docs/9.1/functions-aggregate.html

**Comment by CharlieSYH** [comment]
Please prioritize documenting this feature, @bernscode . Thanks.
