### ISSUE TITLE
Document the new string functions

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#697]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8767

### Which part(s) of the docs might be affected or should be updated? And how?

SQL - Functions - String

Please experiment with creating docs for these functions using chatGPT

Adds the following functions:

chr(integer) -> varchar
starts_with(varchar, varchar) -> boolean
initcap(varchar) -> varchar
lpad(varchar, integer) -> varchar
lpad(varchar, integer, varchar) -> varchar
rpad(varchar, integer) -> varchar
rpad(varchar, integer, varchar) -> varchar
reverse(varchar) -> varchar
strpos(varchar, varchar) -> integer
to_ascii(varchar) -> varchar
to_hex(integer) -> varchar
to_hex(bigint) -> varchar

### Reference

Please reference PG's docs for these string functions.

**Comment by xiangjinwu** [comment]
Let's hold on this until next version, as we have found several bugs in them

* https://github.com/risingwavelabs/risingwave/pull/8970
* https://github.com/risingwavelabs/risingwave/pull/9000
* https://github.com/risingwavelabs/risingwave/pull/9321

**Comment by CharlieSYH** [comment]
@bernscode Please continue to update this doc PR as these code PRs are merged for 0.19.0:
https://github.com/risingwavelabs/risingwave/pull/8970
https://github.com/risingwavelabs/risingwave/pull/9000

**Comment by xiangjinwu** [comment]
FYI known issues have been fixed. They should be good to go in v0.19.0.
