### ISSUE TITLE
Document ingesting CDC data from TiDB

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#715]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8708

### Which part(s) of the docs might be affected or should be updated? And how?

Eric created a demo for ingesting CDC data from TiDB to RW. Let's try out the demo and convert it into a use case or tutorial.

**Comment by CharlieSYH** [comment]
Created a [new issue](https://github.com/risingwavelabs/risingwave-docs/issues/762).
