### ISSUE TITLE
Change required: add documents for all join types.

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#717]
### Related code PR

We currently support NATURAL JOIN in both streaming and batch mode. But for CROSS JOIN, we only support it in the batch mode. It's disallowed in the streaming mode because of the expensive cost of nested-loop join.

### Which part(s) of the docs might be affected or should be updated? And how?

Typically, databases have a seperated doc page named 'Joins' that describes the supported join types. 
Examples:
- https://materialize.com/docs/sql/join/
- https://www.cockroachlabs.com/docs/stable/joins.html
- https://crate.io/docs/crate/reference/en/5.2/concepts/joins.html
- https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/joins/

The content mentioned above should be included in this page.

**Comment by neverchanje** [comment]
Here is an internal draft for this document: https://www.notion.so/risingwave-labs/Document-Joins-a220ced199954eaa962d65219a38d2d2?pvs=4

**Comment by chenzl25** [comment]
Here is my draft for the topic `Joins in RisingWave` which includes all joins currently supported in streaming queries and its limitation. 
Hope this will help you. @hengm3467 
https://www.notion.so/risingwave-labs/Joins-in-RisingWave-73d7b7383d554b30887347833dd9dfeb?pvs=4

**Comment by hengm3467** [comment]
@neverchanje and @chenzl25 Thanks a lot for the initial drafts. I'm working on this one now.
