### ISSUE TITLE
Discussion: accompany use cases by a video or a playground demo

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#744]
@abhyuday26 has tested the integration of RisingWave and Superset.
He summarized his testing procedure and findings at https://www.notion.so/risingwave-labs/Superset-integration-with-Risingwave-248c932937ab438690871359b8c69cf7

And in the end, he made a video to show the use case https://www.risingwave.dev/docs/current/fast-twitter-events-processing/ on superset. It gives the user a real sense of stream processing/real-time updates. (although the checkpoint period in the video is long, the changes are not as frequent as possible. but we can adjust it)

Video or not, just an approach, or it can be the playground https://playground.risingwave.dev/ embedded in the doc, or it can be some animation (but I guess this requires a huge effort). The key point is that by doing so, users experience `stream processing` more concretely.

And by showing a real demo of superset, we linked two pages of documentation together and thus encourages users to have more interaction on the website and discover more content.

Just a random idea, up to you folks to decide if it fits into our style.

**Comment by hengm3467** [comment]
Closing this issue but will keep this suggestion (accompany use cases with visuals and videos) as an ongoing effort.
