### ISSUE TITLE
Document the relationship between the primary key and upsert sink

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#745]
The original Slack thread is in Chinese, let me translate it:
https://risingwave-labs.slack.com/archives/C04F4RB1AHF/p1678950795647739

1. If the downstream system supports the primary key, then RW does not allow users to define the primary key in the sink.
2. If the downstream system does not support the primary key, then RW forces users to define the primary key in the sink.
3. If the table in the downstream system has no primary key, then RW does not allow users to define an `upsert` sink.

@xx01cyx Correct me if I am wrong thanks!

~I think these are a set of general rules that apply to all kinds of sinks/downstream systems,
therefore it seems that it can be mentioned in some `overview` page
and have a table that lists whether each type of downstream system supports the primary key or not~

**Comment by xx01cyx** [comment]
When we talk about a sink's primary key, we're always talking about the **upsert** sink. So the statement below would be better.

1. If the downstream system supports the primary key, then RW does not allow users to define the primary key in ~~the~~ an upsert sink.
2. If the downstream system does not support the primary key, then RW forces users to define the primary key in ~~the~~ an upsert sink.
3. If the downstream system supports the primary key but the table in the downstream system has no primary key, then RW does not allow users to define an upsert sink.

**Comment by hengm3467** [comment]
In the sink topics, mention the three scenarios above.
