### ISSUE TITLE
Document SET SESSION CHARACTERISTICS AS TRANSACTION and SHOW TRANSACTION ISOLATION LEVEL

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#757]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8497

issue: https://github.com/risingwavelabs/risingwave/issues/7976

### Which part(s) of the docs might be affected or should be updated? And how?

SQL references - Commands

Add `SET SESSION CHARACTERISTICS AS TRANSACTION` and `SHOW TRANSACTION ISOLATION LEVEL` commands.

This might be a missed out code change in 0.18.0. Need to confirm if it's supposed to expose to users with @neverchanje.

### Reference

The isolation level is important because it determines how transactions in the database can interact with each other. The issue arose because some libraries treat read-uncommitted isolation level as read-committed, which can cause unexpected behavior.

**Comment by hengm3467** [comment]
Discussed with @lmatz , this is an internal feature, and doesn't need to be documented.
