### ISSUE TITLE
Change required: Adds support for SET BATCH_PARALLELISM

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#758]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8552

issue: https://github.com/risingwavelabs/risingwave/issues/7558

### Which part(s) of the docs might be affected or should be updated? And how?

Release notes

Adds support for SET BATCH_PARALLELISM. You can use this session variable to configure parallelism for batch queries.

This is from v0.18.0.

@hengm3467 Other than mentioning it in the release notes, do we need to document them (like SET STREAMING_PARALLELISM, set batch_parallelism, SET VISIBILITY_MODE) on a reference page?

### Reference

Adding the support for SET BATCH_PARALLELISM in the batch query jobs in RisingWave.

**Comment by hengm3467** [comment]
@neverchanje Do we need to document how to configure these meta settings?

**Comment by hengm3467** [comment]
Now we have all the runtime parameters documented on this page: https://www.risingwave.dev/docs/current/view-configure-runtime-parameters/

Close as completed.
