### ISSUE TITLE
Document proctime()

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#759]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9088

This PR is part of the new [generated columns](https://github.com/risingwavelabs/risingwave/issues/8699).

### Which part(s) of the docs might be affected or should be updated? And how?

- Add a new function proctime() in [SQL references - Functions and operators - Date/time](https://www.risingwave.dev/docs/current/sql-function-datetime/) 

- Document the proctime() attribute in [CREATE TABLE](https://www.risingwave.dev/docs/current/sql-create-table/) & [CREATE SOURCE](https://www.risingwave.dev/docs/current/sql-create-source/)

### Reference

https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/concepts/time_attributes/#processing-time

Introduction (generated by AI, edited):

PROCTIME() allows users to specify a processing time on SOURCE/TABLE. The function returns the current system time when a record is processed, which can be useful for several purposes, including auditing and tracking data changes over time.

To use PROCTIME(), you can define a new table with a column of type `timestamptz` and set its default value to PROCTIME(). For example:

`CREATE TABLE t1 (proc_time Timestamptz as PROCTIME());`

This creates a new table named t1 with a column named `proc_time` of type `timestamptz`. Whenever a new record is inserted into the table, the value of `proc_time` is automatically set to the current processing time using the PROCTIME() function.

**Comment by hengm3467** [comment]
@yuhao-su Could you please confirm if "generated documents" are fully ready now? If not, we should hold on documenting this feature. Thanks.

**Comment by yuhao-su** [comment]
The major feature of generated columns is completed now. The left issue is to support more syntax and functionality (e.g. delete a generated column, alter column).

**Comment by huangjw806** [comment]
https://github.com/risingwavelabs/risingwave/issues/9460
