### ISSUE TITLE
Lack of data type usage method for each source/sink

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave-docs-legacy#760]
Right now we only have a table `Overview of data types`: https://www.risingwave.dev/docs/current/sql-data-types/

I think this is not enough. This table can only show the summary of the data types we support. It is difficult for customers to know which data types each source supports and which types correspond to them. 

I think we should increase the use of data types in the doc of each source.

**Comment by huangjw806** [comment]
cc @fuyufjh @lmatz @sumittal @hengm3467 @xiangjinwu @tabVersion @StrikeW

**Comment by lmatz** [comment]
It's a good suggestion, 

RW is compatible with PostgreSQL's data types, but our upstream system may not be PG-compatible. We may need to specify which data type in upstream can(`cannot` may also be explicitly pointed out if that particular mapping is very misleading) mapped to which data type in RW, or RW mapped to downstream.

Welcome more suggestions

**Comment by fuyufjh** [comment]
Agree. Need a detailed table telling which data types are mapped (or not supported) for each of these sources/sinks.

**Comment by StrikeW** [comment]
For CDC connectors supported by the Debzium, they will first be mapped to Debzium’s data types. So maybe I can try to write a type mapping guide for MySQL and Postgres by extending the [Debzium data type mappings](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-data-types).

**Comment by StrikeW** [comment]
@WillyKidd contributed a [document](https://www.notion.so/risingwave-labs/Debezium-Datatype-Mappings-a79f9c1f8ab94e39beba565edc1cb11b) that describing the data type mapping from MySQL and Postgres Debezium connector to our data type. You can use this doc as a guideline for the data type compatibility test. And we can refine the doc according to the test results. cc @huangjw806

**Comment by tabVersion** [comment]
@wugouzi is working on the sink part.
from risingwave types to debezium types and to pg/mysql types

related https://github.com/risingwavelabs/risingwave/issues/9376

**Comment by hengm3467** [comment]
@tabVersion @wugouzi any update? Thanks.

**Comment by hengm3467** [comment]
Related doc is here: https://www.notion.so/native/risingwave-labs/Datatype-mapping-for-Kafka-Sink-Debezium-format-JDBC-Sink-9a970498bd924e0f95dd4cfe13f43ee6?deepLinkOpenNewTab=true
