### ISSUE TITLE
Document `int256`

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#775]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9028

### Which part(s) of the docs might be affected or should be updated? And how?

Data types

**Comment by lmatz** [comment]
For `int256` and it related functions,
they are considered `experimental`,
which means we don't provide any guarantee to users, e.g. whether it will exist in the future, whether it provides any back-compatibility.

The support is still in early stage. There could be many unsupported cases and potentially errors.

**Comment by CharlieSYH** [comment]
Closing this issue since it's still experimental
