### ISSUE TITLE
Discussion: add experimental features into Doc

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#782]
Recently, we added a new data type called `rw_int256`. As its implementation may not be as robust as we think, and we are not sure if it will be replaced by UDT(User-defined types) in the future, we consider it as an experimental data type. We don't want to provide any guarantee, e.g. whether it will exist in the future, whether its backward-compatibility will be broken.
We can search the related issues/PRs by https://github.com/risingwavelabs/risingwave/issues?q=label%3Aexperimental+int256.

Besides, we also has other experimental features such as the privatelink support for source//sink, its syntax/configuration parameters may be greatly modified before settling it down.

My reasoning is that for visibility (e.g. some users would be happy that we supported it, not just features `in the roadmap`), these experimental features is good to be documented. But we want to make it clear that there is no guarantee to precisely manage users' expectation.

Thanks @StrikeW for bring this up.

**Comment by CharlieSYH** [comment]
Great point!

We can use admonition to warn users of the beta features.
Or we can explore the feasibility of introducing a label component and adding "beta labels" for features (documented on a new page/section/paragraph/sentence/note) that are not ready for use. Maybe as simple as a GitHub-like label that can be added to any place in the doc content. The label shall have a hover-over tooltip that shows a description. And before each release, we shall be able to search the label and check if beta labels are ready to be removed.

Example: https://squidfunk.github.io/mkdocs-material/reference/tooltips/
<img width="722" alt="image" src="https://user-images.githubusercontent.com/100549427/233305261-b935f2d0-691f-451f-8464-da7e4c9cbcc0.png">

References: https://mui.com/material-ui/react-chip/, https://ant.design/components/tag, https://carbondesignsystem.com/components/tag/usage

**Comment by CharlieSYH** [comment]
Please help confirm, @lmatz:
All PRs labelled "experimental" should be documented in the user docs with each release, and the experimental features should be explicitly annotated as beta in the docs. 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/100549427/234518452-a0606b2d-ab8f-4da9-8239-212ab34c343a.png">

**Comment by lmatz** [comment]
The PRs shown in the figure all need to be documented and documented as experimental features.

I can help confirm for each release in the future.


Whether it should be annotated as Beta? 
I have no strong opinion on this. Feel free to do so. Thanks!

**Comment by hengm3467** [comment]
We can use an admonition (Warning type?) mentioning that these features are experimental. That means they can be changed or removed in the future.  @CharlieSYH

**Comment by CharlieSYH** [comment]
We decided to use admonition to warn users of the beta features.
For example:
```
:::caution Experimental feature
`rw_int256` is an experimental feature and is subject to change. There is no guarantee that this feature will be maintained in future versions.
:::
```
