### ISSUE TITLE
Bug: 'pg_conversion' has a different style than other columns

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#786]
### Where's the bug?

https://www.risingwave.dev/docs/current/release-notes/#administration

### Describe the bug

![SCR-20230422-m6c](https://user-images.githubusercontent.com/5791930/233771108-17a7b51b-b152-4124-8c81-67e93385e0b3.png)

Cheers

**Comment by hengm3467** [comment]
Just fixed (committed already). Closing it now.
