### ISSUE TITLE
Document data type mapping for connectors

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#790]

**Comment by neverchanje** [comment]
I created a related issue for Debezium + Postgres/MySQL. We still lack the support for some data types: https://github.com/risingwavelabs/risingwave/issues/9820 Once they are done, we can write the document based on this table.

**Comment by StrikeW** [comment]
Hi @hengm3467, since we have release the v1.0 version, which is an important milestone. Could we priorities the data type mapping doc to ease the usage of RW?

**Comment by emile-00** [comment]
> Hi @hengm3467, since we have release the v1.0 version, which is an important milestone. Could we priorities the data type mapping doc to ease the usage of RW?

We're working on the data type mappings for MySQL and PostgreSQL now. Please let us know if there's anything else to document.

**Comment by hengm3467** [comment]
@neverchanje @fuyufjh @StrikeW Do we have mapping tables for other sources/sinks?

**Comment by StrikeW** [comment]
Here is data type mapping for Kafka sink (debezium-pg format) and JDBC sink. @hengm3467 
https://www.notion.so/risingwave-labs/Datatype-mapping-for-Kafka-Sink-Debezium-format-JDBC-Sink-9a970498bd924e0f95dd4cfe13f43ee6

We may need to prepare data type mapping for iceberg sink @liurenjie1024.
