### ISSUE TITLE
Document k8s + HDFS deployment

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#796]
### Related code PR

<img width="906" alt="Screenshot 2023-04-25 at 14 30 27" src="https://user-images.githubusercontent.com/6970676/234192850-30bfe360-0f6d-4c53-b8ab-e6b14fd300e9.png">

We only documented minio and s3. HDFS is also required. @wcy-fdu 

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/risingwave-kubernetes

**Comment by yufansong** [comment]
I think the previous time, using HDFS has some [problem](https://github.com/risingwavelabs/risingwave/issues/9147) in OpenDal and it seems solved today. But I have not tried it.

**Comment by hengm3467** [comment]
@yufansong Thanks for the input. Could you or someone else help test it? Thanks!

**Comment by wcy-fdu** [comment]
I will talk with @CharlieSYH to finish the kernel part of this doc.

**Comment by neverchanje** [comment]
@wcy-fdu @CharlieSYH Any updates?

**Comment by wcy-fdu** [comment]
> @wcy-fdu @CharlieSYH Any updates?

I have written a [guidance doc ](https://github.com/risingwavelabs/risingwave/blob/main/docs/multi-object-store.md)in kernel side, and in this repo the main work is about the k8s deploying.
Now @yufansong is working on deploying hdfs with k8s, will finish this doc after operator side is done.

**Comment by yufansong** [comment]
For cloud parts, I provide a docs at [here](https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/general/storage.md#hdfs)

**Comment by CharlieSYH** [comment]
Closed by https://github.com/risingwavelabs/risingwave-docs/pull/889
