### ISSUE TITLE
Use codeblocks for function examples

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave-docs-legacy#805]
### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/sql-functions/

### Reference

https://risingwave-labs.slack.com/archives/C034XCYJPSN/p1682499058593389

**Comment by CharlieSYH** [comment]
We've updated the Aggregate functions page with the new layout. https://www.risingwave.dev/docs/current/sql-function-aggregate/.
We'll update other pages as well in future releases.
