### ISSUE TITLE
Document the support for array range access

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#807]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9362

### Which part(s) of the docs might be affected or should be updated? And how?

SQL - Data types - Array
Add to the topic saying that this type of expression is supported.

**Comment by lmatz** [comment]
May consider adding this part https://github.com/risingwavelabs/risingwave/blob/main/e2e_test/batch/types/array_ty.slt.part#L109-L124 as Risingwave behaves differently from PG.
