### ISSUE TITLE
Document the syntax of `Dynamic Filter` and `Temporal Filter`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#821]
We have the syntax section for group top-n, https://www.risingwave.dev/docs/current/sql-pattern-topn/, which is nice.

But `Dynamic Filter` and `Temporal Filter` have examples only.
Users may be confused about some other usage which is not the same as but similar to the examples, which may or may not work.

**Comment by hengm3467** [comment]
@lmatz Thanks for the input. Could you please provide details about other usage of these two types of filters?

**Comment by lmatz** [comment]
Temporal filter:
https://github.com/risingwavelabs/rfcs/pull/18/files
https://github.com/risingwavelabs/risingwave/issues/6346

may check with @soundOfDestiny 

other references:
https://materialize.com/docs/sql/patterns/temporal-filters/

**Comment by lmatz** [comment]
Dynamic filter:
https://github.com/risingwavelabs/risingwave/issues/3419

may also check with @jon-chuang

**Comment by soundOfDestiny** [comment]
In short, temporal filter is a dynamic filter of which the right side is `NOW()` (or an offset of `NOW()`)

**Comment by st1page** [comment]
- This pattern is expected used in streaming queries (create materialized view or create sink). But current example is a batch query.
- Currently RisngWave do not support `week` as the unit of an interval, but the example use it and RW will give an error. https://github.com/risingwavelabs/risingwave/issues/10669
- current restriction for temporal filter
   - the condition must have at least one lower bound with now expr
   ```SQL
    /* do now have now related lowerbound*/
    dev=> explain create materialized view mv as select * from t where ts < now();
    ERROR:  QueryError: internal error: All `now()` exprs were valid, but the condition must have at least one now expr as a lower bound.
    /* Ok */
    dev=> explain create materialized view mv as select * from t where ts < now() AND ts > now() - interval '1 hour';
   ```
   - the now() side's expression must be with the pattern `now() [+- const_expr]`
   ```SQL
    /* unsupported patten in the now side*/
    dev=> explain create materialized view mv as select * from t1 where now() -  additional_time_to_live < ts;
    ERROR:  QueryError: internal error: Conditions containing now must be of the form `input_expr cmp now() [+- const_expr]` or `now() [+- const_expr] cmp input_expr`, where `input_expr` references a column and contains no `now()`.
    /* Ok */
    dev=> explain create materialized view mv as select * from t1 where now() < ts - additional_time_to_live;  
   ```

**Comment by neverchanje** [comment]
https://docs.risingwave.com/docs/dev/sql-pattern-temporal-filters/
https://docs.risingwave.com/docs/dev/sql-pattern-dynamic-filters/

I think the pages here should be pretty enough.
