### ISSUE TITLE
Enhance the `Back up and restore meta service` page

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#831]
When one user asked me about the backup and restore, I found several issues:
1. It is unclear where `storage_url` and `storage_directory` are configured.
2. `risectl` is referred back to `For details, see [Run RisingWave locally]`(https://www.risingwave.dev/docs/upcoming/risingwave-local/). But on that page, `risectl` is never mentioned.
3. `risectl` has a few other commands also. A separate page maybe better.
4. `risectl is included in the pre-built RisingWave binary.` But for deployment by Docker or Kubernetes, there is no binary. I guess we need some help from Cloud folks. In short, actionable steps, i.e. command lines, are much clear, compared to only descriptive text.

**Comment by hengm3467** [comment]
We need a section or topic about `risectl`. @lmatz please help find devs for this tool and note down the key points: how to start, its main function, and the commands available.

**Comment by hengm3467** [comment]
`meta-node` is the source of truth for all system parameters.
To summarize, the interface for managing RisingWave configurations are:
- risingwave.toml 
- risedev.yaml (for local deployment)
- risingwave operator (how to configure)
- `risectl`
- `meta-node` 

Thanks @lmatz for summarizing the differences and when to use these entry points.

**Comment by lmatz** [comment]
If users are deploying Risingwave via k8s, then https://github.com/risingwavelabs/risingwave-operator/blob/main/docs/manifests/risingwave/risingwave-customize-config.yaml#L1-L25
is the reference `yaml` file that includes customized RisingWave config.

This file serves the same purpose as the file below: 
![SCR-20230519-g3m](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/6f564f05-00a7-4730-a00e-9145fca56be3)



This is how these two configs
![SCR-20230519-g20](https://github.com/risingwavelabs/risingwave-docs/assets/5791930/55f1ca19-d59b-46ef-a73d-3896c3b5fb11)

can be specified.

**Comment by hengm3467** [comment]
@lmatz In a separate PR, I have updated the instructions about how to change `storage_url` and `storage_directory`. It seems that there is no need to mention `risectl` now. Can you confirm? If so, I think we can close this issue.

**Comment by hengm3467** [comment]
Close as completed:

<img width="727" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100685635/384fc939-0e6a-4faa-b1ad-a1f6b87173e7">
