### ISSUE TITLE
Document `hex_to_int256`()

### ISSUE THREAD

**Issue by bernscode** [risingwavelabs/risingwave-docs-legacy#835]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9146

https://github.com/risingwavelabs/risingwave/pull/9184

### Which part(s) of the docs might be affected or should be updated? And how?

Perhaps SQL -> Functions -> Mathematical. However, we need to explicitly mention that this is an experimental feature and we may change its behavior or abandon it. Since we may change it or abandon it, it may make sense that we host all the related functions, operators in one topic.

### Reference

Review PR's and e2e_test's

**Comment by hengm3467** [comment]
@bernscode Closing this one as it's covered in #804
