### ISSUE TITLE
Document count/min/max/first aggregation functions for `Int256`

### ISSUE THREAD

**Issue by bernscode** [risingwavelabs/risingwave-docs-legacy#836]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9186

### Which part(s) of the docs might be affected or should be updated? And how?

We need to explicitly mention that this is an experimental feature and we may change its behavior or abandon it. Since we may change it or abandon it, it may make sense that we host all the related functions, operators in one topic.

### Reference

Review PR and e2e_test

**Comment by hengm3467** [comment]
@bernscode closing this one as it's already covered in #804
