### ISSUE TITLE
Bug: 0.18.0 binary links to 0.1.17

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#853]
### Where's the bug?

https://www.risingwave.dev/docs/current/risingwave-local/

### Describe the bug

> Download the pre-built binary.
>
> wget https://github.com/risingwavelabs/risingwave/releases/download/v0.1.17/risingwave-v0.1.17-x86_64-unknown-linux.tar.gz

**Comment by hengm3467** [comment]
Fixed. Please take a look and let me or Charlie know if additional changes are needed.
