### ISSUE TITLE
Document trigonometric functions

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#854]
### Related code PR
pr1: https://github.com/risingwavelabs/risingwave/pull/8838

pr2: https://github.com/risingwavelabs/risingwave/pull/8918
issue2: https://github.com/risingwavelabs/risingwave/issues/9675

pr3: https://github.com/risingwavelabs/risingwave/pull/9203

pr4: https://github.com/risingwavelabs/risingwave/pull/9259

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/docs/upcoming/sql-function-mathematical/#trigonometric-functions

### Reference

See `e2e_test/batch/functions/trigonometric_funcs.slt.part` in the code repo.

**Comment by CharlieSYH** [comment]
@bernscode, the code author @CAJan93 has added a few more functions: cosh, tanh, coth, asinh, acosh, atanh, sinh.

e2e:
`e2e_test/batch/functions/trigonometric_funcs.slt.part`

Source: https://github.com/risingwavelabs/risingwave/blob/a62abc631d431716ed9cd9aabb654e9a60f57afc/src/frontend/src/binder/expr/function.rs#L402C1

**Comment by CAJan93** [comment]
Thanks for opening this PR. 

They will be added in [sql-functions.mathematical](https://github.com/risingwavelabs/risingwave-docs/blob/f8480ff8492153de3c6b777b8fb6ee348b411f9a/docs/sql/functions-operators/sql-function-mathematical.md?plain=1#L2), right? The doc also misses most of the functions in degrees, e.g. `simd` and `tand`. All these functions are listed in the `function.rs`

**Comment by CharlieSYH** [comment]
@CAJan93 We have opened an issue for degrees. https://github.com/risingwavelabs/risingwave-docs/issues/891. Thanks.
