### ISSUE TITLE
Document scaling in/out

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#857]
### Related code PR

@shanicky @BugenZhao  Please help on this issue, thanks! The engineer can first draft a document so that our tech writers can help refine.

### Which part(s) of the docs might be affected or should be updated? And how?

I expect it to be standalone page, answering the questions:

1. Does RisingWave support scale in and out? 
2. Does RisingWave scale automatically?
3. Do we remove the unnecessary state from the old operator after scaling?

You can briefly describe the internals of how we achieve this. For instance, we can talk a bit about consistent hashing, which is the mechanism under the hood. For readers who want to dig more into it, we can refer them to this developer doc: https://github.com/risingwavelabs/risingwave/blob/main/docs/consistent-hash.md

**Comment by hengm3467** [comment]
Close as completed in #1367. See the publish page:

https://docs.risingwave.com/docs/current/k8s-cluster-scaling/
