### ISSUE TITLE
Document: DEBEZIUM_AVRO

### ISSUE THREAD

**Issue by adevday** [risingwavelabs/risingwave-docs-legacy#861]
### Where's the bug?

https://www.risingwave.dev/docs/current/create-source-cdc/

### Describe the bug

The `DEBEZIUM_AVRO` is supported in our main branch, but we have not documented it yet. Some users from our community run into troubles for leaking documentation.

Here's an example of it.
```
CREATE TABLE orders (order_id INT PRIMARY KEY) with (
    connector = 'kafka',
    kafka.topic = 'mysql.mydb.orders',
    kafka.brokers = 'message_queue:29092',
    kafka.scan.startup.mode = 'earliest'
) ROW FORMAT DEBEZIUM_AVRO ROW SCHEMA LOCATION CONFLUENT SCHEMA REGISTRY 'http://message_queue:8081';
````

And we need to notice our users to run the command below when using together with PostgreSQL Debezium.
```
ALTER TABLE $TABLE_NAME REPLICA IDENTITY FULL;
```

Besides, the `DEBEZIUM_AVRO` row format have a feature which DEBEZIUM_JSON not, that it can infer the table schema from the SCHEMA REGISTRY, so that user can leave columns part empty or specify the primary key columns.

**Comment by neverchanje** [comment]
We do have a document here: https://github.com/risingwavelabs/risingwave-docs/pull/783/files Can you list out the confusion parts? https://www.risingwave.dev/docs/upcoming/create-source-cdc/#kafka

**Comment by hengm3467** [comment]
Now I see, the format `DEBEZIUM_AVRO` is not documented in the supported sources and formats 

https://www.risingwave.dev/docs/upcoming/sql-create-source/

And the syntax and diagram syntax are not updated with this format either. 

https://www.risingwave.dev/docs/upcoming/create-source-cdc/#kafka

cc: @emile-00
