### ISSUE TITLE
Document: bool_and, bool_or, jsonb_agg, jsonb_object_agg

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#863]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9452

### Which part(s) of the docs might be affected or should be updated? And how?

Document the `bool_and`, `bool_or`, `jsonb_agg`, `jsonb_object_agg` functions under SQL -> Functions -> Aggregate

### Reference

https://www.postgresql.org/docs/9.5/functions-aggregate.html

**Comment by CharlieSYH** [comment]
Implemented in https://github.com/risingwavelabs/risingwave-docs/pull/947.
