### ISSUE TITLE
Document: Window Functions

### ISSUE THREAD

**Issue by emile-00** [risingwavelabs/risingwave-docs-legacy#869]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9597
https://github.com/risingwavelabs/risingwave/pull/9622
https://github.com/risingwavelabs/risingwave/pull/9701

### Which part(s) of the docs might be affected or should be updated? And how?

New reference page under `Functions and operators` on Window functions. Cover the `OVER()`  clause and the `EMIT ON WINDOW CLOSE` clause. Document the `lag()` and `lead()` window functions.

### Reference

Overview of window functions and `lag()` and `lead()`: https://www.sqltutorial.org/sql-window-functions/
Also document `EXCLUDE CURRENT ROW` and `EXCLUDE NO OTHERS` support for window functions

**Comment by hengm3467** [comment]
Close as completed in #1077
