### ISSUE TITLE
Document: Update dbeaver's status in the integration page

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#899]
### Related code PR

Thanks to @hzxa21 's work https://github.com/risingwavelabs/risingwave/pull/9954 DBeaver is now basically production-ready. Please mark it as available in our upcoming branch.

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/upcoming/rw-integration-summary/

**Comment by hengm3467** [comment]
Updated. Please refresh the page to see the changes.

<img width="853" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100685635/48268bc4-8e92-4772-a785-834cab6f55b5">

**Comment by hengm3467** [comment]
Close as completed.
