### ISSUE TITLE
Improve the structure of the setup section

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#914]
### Which part(s) of the docs might be affected or should be updated? And how?

<img width="300" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100685635/a8c570cd-77d1-4eff-a753-830fc25eb68a">
Run locally and run in cloud are a bit confusing. Locally can mean local host to someone, not including K8s.

**Comment by CharlieSYH** [comment]
Closed with https://github.com/risingwavelabs/risingwave-docs/pull/948
