### ISSUE TITLE
Expand the Grafana page and document available metrics

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#927]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/9874

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/upcoming/grafana-integration/
https://www.risingwave.dev/docs/upcoming/use-risingwave-to-monitor-risingwave-metrics/

Release note:
Two new metrics on the user Grafana dashboard and dev Grafana dashboard.
- One records the throughput of each actor of a materialized view.
- The other records the aggregated throughput of all the actors of a materialized view.

**Comment by hengm3467** [comment]
Since we have no plans to document the metrics available on Grafana, I think we can close this issue. As a side note, the topic about how to monitor K8s RingWave instance is now published: 

https://www.risingwave.dev/docs/current/monitor-risingwave-cluster/
