### ISSUE TITLE
Document Sinks Overview lacks an introduction about Apache Iceberg

### ISSUE THREAD

**Issue by Ad-Bean** [risingwavelabs/risingwave-docs-legacy#937]
### Where's the bug?

https://www.risingwave.dev/docs/current/delivery-overview

### Describe the bug

The [overview page](https://www.risingwave.dev/docs/current/delivery-overview) might need some introduction about Apache Iceberg https://www.risingwave.dev/docs/current/sink-to-iceberg/.

**Comment by emile-00** [comment]
I've added an intro for Apache Iceberg in this PR: https://github.com/risingwavelabs/risingwave-docs/pull/905. Please take a look and leave any suggestions.
