### ISSUE TITLE
Document configuring the docker compose cluster to use external s3 services instead of minio 

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#939]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10074

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/risingwave-docker-compose/#minio

The minio section can be marked as optional. Instead, we can add another section that describes how to connect to an external s3.

**Comment by hengm3467** [comment]
@neverchanje Please review the related PR #942 by @wcy-fdu
