### ISSUE TITLE
 Document configuring the docker compose cluster to use GCS

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#953]
https://github.com/risingwavelabs/risingwave/issues/10169

**Comment by hengm3467** [comment]
@wcy-fdu Could you please help summarize the configurations / steps for using GCS? Thanks a lot!

**Comment by wcy-fdu** [comment]
> @wcy-fdu Could you please help summarize the configurations / steps for using GCS? Thanks a lot!

Just open a [pr](https://github.com/risingwavelabs/risingwave/pull/11749) on kernel side to summarize the configurations, and I guess you can refer to this.

**Comment by wcy-fdu** [comment]
@hengm3467 Could you please help to review this [PR](https://github.com/risingwavelabs/risingwave/pull/11749), and refer to this PR to implement https://github.com/risingwavelabs/risingwave-docs/issues/953 and #954 ?

**Comment by hengm3467** [comment]
@wcy-fdu Thanks a lot for putting this together. Will look at the changes ASAP.

**Comment by wcy-fdu** [comment]
Any update?

**Comment by hengm3467** [comment]
Will update the docs today. @wcy-fdu
