### ISSUE TITLE
Document configuring the docker compose cluster to use Azure Blob

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#954]
https://github.com/risingwavelabs/risingwave/issues/10167

**Comment by hengm3467** [comment]
@wcy-fdu Could you please help summarize the configurations / steps needed for using Azure Blob? Thanks a lot!

**Comment by wcy-fdu** [comment]
> @wcy-fdu Could you please help summarize the configurations / steps needed for using Azure Blob? Thanks a lot!

no problem.
