### ISSUE TITLE
Document the Prometheus + Grafana setup for the Kubernetes deployment

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#973]
### Related code PR

https://github.com/risingwavelabs/risingwave-operator/blob/main/monitoring/README.md 

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/risingwave-kubernetes/

It can either be a separate page titled "Monitoring" or a embedded section in the k8s page, given that only the k8s mode require the self-hosted Grafana + Prometheus. Other modes, such as cloud or docker compose, have the monitoring stack integrated. Local modes like docker or single-binary are unlikely require monitoring.

**Comment by arkbriar** [comment]
Note that the dashboard used in https://github.com/risingwavelabs/risingwave-operator/blob/main/monitoring/README.md is unmaintained and might have been broken. We should use the one generated in the kernel repo.

https://github.com/risingwavelabs/risingwave/tree/main/grafana

**Comment by neverchanje** [comment]
Hi, @Nebulazhang 

Please offer some advice regarding this issue. I believe the doc team will need some inputs which the developer doc https://github.com/risingwavelabs/risingwave-operator/blob/main/monitoring/README.md  doesn't provide.

**Comment by Nebulazhang** [comment]
> Hi, @Nebulazhang
> 
> Please offer some advice regarding this issue. I believe the doc team will need some inputs which the developer doc https://github.com/risingwavelabs/risingwave-operator/blob/main/monitoring/README.md doesn't provide.

I will move the remote-write part to another dir, and ensure that new users do not have too much confusion

**Comment by Nebulazhang** [comment]
I have updated the operator `README.md` and created a PR https://github.com/risingwavelabs/risingwave-operator/pull/460.

After that, you can add the monitoring part for the in k8s page, and just need to run the `monitoring/install.sh`

A Little tip, pls update the cert-manager link to `https://cert-manager.io/docs/installation/kubectl/`

@hengm3467

**Comment by hengm3467** [comment]
Testing the steps now. Somehow the dashboard doesn't load data. 

![image](https://github.com/risingwavelabs/risingwave-docs/assets/100685635/4d59c937-8c2d-4041-9979-14170ec1f740)
