### ISSUE TITLE
Document Java UDF

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#978]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10320
https://github.com/risingwavelabs/risingwave/pull/10095

### Which part(s) of the docs might be affected or should be updated? And how?

UDF

**Comment by emile-00** [comment]
Update: array type inputs and outputs are supported
https://github.com/risingwavelabs/risingwave/pull/10446
