### ISSUE TITLE
Return a warning message when creating sink with ORDER BY

### ISSUE THREAD

**Issue by bernscode** [risingwavelabs/risingwave-docs-legacy#984]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/10239

### Which part(s) of the docs might be affected or should be updated? And how?

SQL -> Commands - > CREATE SINK

### Reference

Review PR

**Comment by hengm3467** [comment]
This one doesn't need doc updates. Users will get a message when they enter a query this way, then they'll learn about it.
